### ISSUE TITLE
etx: External Launch Error: Could not launch JNLP file. (could not find any suitable runtime)

### ISSUE THREAD

**Issue by JavaUser20** [karakun/OpenWebStart#100]
I'm trying to replace Oracle's Java with an opensource solution. I'm using DHL's silent.jnlp for Zebra printing. When I try running the .jnlp they supply I get the following:

ERROR
netx: External Launch Error: Could not launch JNLP file. (could not find any suitable runtime)
netx: External Launch Error: Could not launch JNLP file. (could not find any suitable runtime)
result: null
arg: net.sourceforge.jnlp.JNLPFile@26ab59ca
call privileged method: checkSingleInstanceRunning
Acceptable title tag found, contains: DHL Silent print
Jars not ready to provide attribute Application-Name
Acceptable title tag found, contains: DHL Silent print
Jars not ready to provide attribute Application-Name
Acquired shared lock on C:\Users\ucs\AppData\Local\Temp\ucs\netx\locks\netx_running to indicate javaws is running
UNIQUEKEY=1574275082304-150677184-file:/C:/Users/ucs/Desktop/silent.jnlp
Acceptable vendor tag found, contains: EPAM
Acceptable title tag found, contains: DHL Silent print
Jars not ready to provide attribute Application-Name
Description: null
Homepage: null
Using MalformedXMLParser
UNIQUEKEY=1574275082304-1125424811-file:/C:/Users/ucs/Desktop/silent.jnlp
Acceptable vendor tag found, contains: EPAM
Acceptable title tag found, contains: DHL Silent print
Jars not ready to provide attribute Application-Name
Description: null
Homepage: null
Using MalformedXMLParser
JNLP file location: C:\Users\ucs\Desktop\silent.jnlp
Proceeding with jnlp
Unable to use Firefox''s proxy settings. Using "DIRECT" as proxy type.
Starting security dialog thread
Forcing of offline set to: false
JvmLauncher set to com.openwebstart.launcher.OwsJvmLauncher.
ITW Boot called with custom OwsJvmLauncher and args [-verbose, -jnlp, C:\Users\ucs\Desktop\silent.jnlp].
Saving runtime cache to filesystem
Adding runtime definition
Saving runtime cache to filesystem
Adding runtime definition
Saving runtime cache to filesystem
Adding runtime definition
Saving runtime cache to filesystem
Adding runtime definition
Saving runtime cache to filesystem
Clearing runtime cache
Loading runtime cache from filesystem
RelevantJavawsArgs: '[-verbose, -jnlp, C:\Users\ucs\Desktop\silent.jnlp]'
Checking if installation time (1574273505241) is after last initial config time (1574273513635)
Property 'ows.install4j.propertyUpdate' is unknown.
Loading USER level properties from: file:/C:/Users/ucs/.config/icedtea-web/deployment.properties
Property 'ows.install4j.propertyUpdate' is unknown.
Loading USER level properties from: file:/C:/Users/ucs/.config/icedtea-web/deployment.properties
Ico provider registered correctly.
Ico provider registered correctly.
OS detected: Win[true], MacOS[false], Linux[false]
OpenWebStartLauncher called with args [-verbose, -jnlp, C:\Users\ucs\Desktop\silent.jnlp].
Starting OpenWebStart 1.0.0
ITW Boot called with custom OwsJvmLauncher and args [-verbose, -jnlp, C:\Users\ucs\Desktop\silent.jnlp].

**Comment by sclassen** [comment]
Could you please attach the JNLP file to this ticket.
As the reason for the error is most likely to be found there

**Comment by JavaUser20** [comment]
[silent.zip](https://github.com/karakun/OpenWebStart/files/3871230/silent.zip)

I attached the JNLP file here. Please let me know if it doesn't work.

**Comment by sclassen** [comment]
Here the plain text:

```
<?xml version="1.0" encoding="UTF-8"?><jnlp spec="6.0+" codebase="https://mydhl.express.dhl:443">
    <information>
        <title>DHL Silent print</title>
        <vendor>EPAM</vendor>
        <offline-allowed>true</offline-allowed>
    </information>

    <resources>
        <jar href="https://mydhl.express.dhl/content/dam/dhl/print/silent-print.jar" main="true" />
    </resources>

    <application-desc main-class="com.dhl.ewf.sprint.SilentPrintApplication" >
        <argument>agrs</argument>
    </application-desc>

    <security>
        <all-permissions />
    </security>

    <update check="always" policy="always" />
</jnlp>
```

**Comment by sclassen** [comment]
OK the problem is that the JNLP file is missing the required Java version.
Add the following line to `<resources>'

```
        <java version="1.8*"/>
```

This will select a java 1.8. If you replace the `*` with `+` it will take the newest java available.

**Comment by JavaUser20** [comment]
That definitely seems like that's the problem. I was able to edit the JNLP and run it from the desktop and the app ran. 

I'm so close, yet so far away from getting this to work. 

The problem I have now is that DHL has a "Print Waybill" icon, which downloads the JNLP which is in the original form (doesn't have the <java version="1.8*"/> tag. So naturally, it doesn't work. :(

Is there any way I can work around that with OpenWebsStart? Is there a way to have OpenWebStart ignore the missing tag? Oracle's webstart must ignore that tag missing since it works ok with Oracle's non-opensource friendly version.

**Comment by sclassen** [comment]
I implemented a fallback to 1.8+ in #101 next version of OWS will have this issue fixed

**Comment by JavaUser20** [comment]
I'm sorry for my ignorance, I just found out about OWS a few days ago. When will the next release be available? OWS seems like a very viable solution to my Oracle problem.

**Comment by sclassen** [comment]
have a look at https://openwebstart.com/#openwebstart-roadmap
It will be early December but a date is not yet fixed

**Comment by JavaUser20** [comment]
I will be waiting for the next release eagerly. 

Thank you for all the hard work you put into this project. :)
