### ISSUE TITLE
Second start fails with error

### ISSUE THREAD

**Issue by SaschaJostock** [karakun/OpenWebStart#102]
When I launch an application for the second time, it fails with the following error message:
net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could not initialize application. The application has not been initialized, for more information execute javaws from the command line.
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:669)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:411)
	at net.sourceforge.jnlp.Launcher.access$300(Launcher.java:69)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:756)
Caused by: net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Unknown Main-Class. Could not determine the main class for this application.
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:760)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.<init>(JNLPClassLoader.java:347)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.createInstance(JNLPClassLoader.java:420)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:492)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:465)
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:661)
	... 3 more

Log from Java-Console:

Thu Nov 21 09:39:24 CET 2019 [ERROR  ] net.sourceforge.jnlp.Launcher: ERROR net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could not initialize application. The application has not been initialized, for more information execute javaws from the command line.     at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:669)     at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:411)     at net.sourceforge.jnlp.Launcher.access$300(Launcher.java:69)     at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:756) Caused by: net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Unknown Main-Class. Could not determine the main class for this application.     at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:760)     at net.sourceforge.jnlp.runtime.JNLPClassLoader.<init>(JNLPClassLoader.java:347)     at net.sourceforge.jnlp.runtime.JNLPClassLoader.createInstance(JNLPClassLoader.java:420)     at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:492)     at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:465)     at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:661)     ... 3 more 
 
Thu Nov 21 09:39:24 CET 2019 [ERROR  ] net.sourceforge.jnlp.AbstractLaunchHandler: netx: Initialization Error: Could not initialize application. (Fatal: Initialization Error: Unknown Main-Class. Could not determine the main class for this application.) net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could not initialize application. The application has not been initialized, for more information execute javaws from the command line.     at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:669)     at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:411)     at net.sourceforge.jnlp.Launcher.access$300(Launcher.java:69)     at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:756) Caused by: net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Unknown Main-Class. Could not determine the main class for this application.     at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:760)     at net.sourceforge.jnlp.runtime.JNLPClassLoader.<init>(JNLPClassLoader.java:347)     at net.sourceforge.jnlp.runtime.JNLPClassLoader.createInstance(JNLPClassLoader.java:420)     at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:492)     at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:465)     at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:661)     ... 3 more 
Thu Nov 21 09:39:24 CET 2019 [INFO  ] net.sourceforge.jnlp.cache.NativeLibraryStorage: Activate native: https://rubin-fvt-01/rubin/webstart/lib/org.eclipse.swt.win32.win32.x86_64-3.105.3.jar 
Thu Nov 21 09:39:24 CET 2019 [DEBUG  ] net.sourceforge.jnlp.runtime.JNLPClassLoader: Activate jar: https://rubin-fvt-01/rubin/webstart/lib/org.eclipse.swt.win32.win32.x86_64-3.105.3.jar 
Thu Nov 21 09:39:24 CET 2019 [INFO  ] net.sourceforge.jnlp.JNLPFile: Acceptable title tag found, contains: RUBIN-Client

### With Version 0.x works fine.

Cheers,
Sascha

**Comment by sclassen** [comment]
does this happen on every second start or was this a one time incident?
I cannot reproduce it here out of the box so was wondering if this reliably reproducable

**Comment by SaschaJostock** [comment]
Yes the error is reproduce, after cache clear the application start successful. After  the first start comes again and again the error.

**Comment by SaschaJostock** [comment]
With a fresh Installation in a Citrix Test Environment, 
the error also occurs.

**Comment by sclassen** [comment]
ok, could you post the JNLP file and the entire log files of a failed start

**Comment by SaschaJostock** [comment]
We have a special feature, we create the jnlp on the fly with a servlet.
I will post the jnlp-file

**Comment by SaschaJostock** [comment]
The jnlp file
[PGopPresentationApp.zip](https://github.com/karakun/OpenWebStart/files/3874051/PGopPresentationApp.zip)

**Comment by sclassen** [comment]
Could you try the following SNPASHOT version to verify that the problem is solved with the fix from AdoptOpenJDK/IcedTea-Web#524

https://cloud.karakun.com/index.php/s/7P43naEYDeDQxgd
