### ISSUE TITLE
Remove an app from OpenWebStart Settings

### ISSUE THREAD

**Issue by aPollO2k** [karakun/OpenWebStart#105]
I have removed some apps from the cache by using the openwebstart settings gui. The apps are gone but the desktop and menu shortcuts created on first installation are still there.
I remember on Oracle  Control Center in the cache viewer i was able to remove apps one by one and the shortcuts related to this apps are removed also.

Do i have to remove shortcuts for removed apps manually or ist this a bug?

I'm using Linux Ming 19.2 with OWS 1.0.0 and Zulu Community Edition 1.8.0_222. I tested the same apps on Windows 10 with exact same Version of OWS and Zulu. In Windows 10 the SHortcuts was removed with the apps. I don't have to do it manually.

**Comment by sclassen** [comment]
We plan on adding this missing feature in version 1.2 or 1.3
Until then you need to remove shortcuts by hand
