### ISSUE TITLE
Start a JNLP file via browser leads to a warning: Loads the following resources from a foreign domain

### ISSUE THREAD

**Issue by mazze5** [karakun/OpenWebStart#106]
The start of my application, the JNLP file, is done via the browser. There is a page with a link to the JNLP file. The user clicks on the link and confirm that he really wants to execute it.
The JNLP file is downloaded and started with OpenWebstart.

Now there is always a warning: Load the following resources from a foreign domain: file://C:/Users/...jnlp

Is this behavior desired? This problem does not exist with Oracle Webstart.

An ad-hoc solution is to check "Local file system is part of the codebase" in OpenWebstart settings.

If I run "javaws.exe <URL-to-Remote-JNLP>" it works without this warning.

Using windows10 and version 1.0.0 of OpenWebstart.

**Comment by hendrikebbers** [comment]
Hi @mazze5 the "Local file system is part of the codebase" is the correct option. By default OpenWebStart is more restrictive than Oracle WebStart in this case (based on the underlying IcedTeaWeb). We decided to not make this property active by default for now. Maybe this will change in a future version since several users already had this problem. 
@sclassen should we create an issue to active the property by default?

**Comment by sclassen** [comment]
We need to discuss this with @judovana as it is located within ITW

**Comment by mazze5** [comment]
Hi @hendrikebbers thanks for this information. Please comment your final dicission about the default value of this property in this issue so that I will be notified.

**Comment by judovana** [comment]
Hello!

In trusted environments, the  "Local file system is part of the codebase" being true should be super safe. However outside of trusted environment, you open ITW to possible attack.

Ida on fix of this is, to find where jnlp file is saved by browser (in case of "open by", those are usually scary locations like /run/uid/firefox/tnp and simialrly)  and to enable only this as part of the codebase. Thougts?

Thank you for patience  and sorry for (again) delayed reply, I spotted it right when fliying for week away.

**Comment by sclassen** [comment]
There is a setting in OWS to include the local file system into the trusted sources
