### ISSUE TITLE
no clear instructions on how to build on linux

### ISSUE THREAD

**Issue by undergraver** [karakun/OpenWebStart#121]
I made a git clone of the project but I am unable to compile.

This is what I did:

~/Work/OpenWebStart$ ./mvnw clean install

but I get this error (some parts were removed):
....
[INFO] Building OpenWebStart 1.2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for net.adoptopenjdk:icedtea-web-all-dependencies:jar:2.0.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] OpenWebStart Parent ................................ SUCCESS [  3.647 s]
[INFO] Resource Transformer for ITW ....................... SUCCESS [  4.329 s]
[INFO] OpenWebStart ....................................... FAILURE [  0.348 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
....
[ERROR] Failed to execute goal on project openwebstart: Could not resolve dependencies for project com.openwebstart:openwebstart:jar:1.2.0-SNAPSHOT: Failure to find net.adoptopenjdk:icedtea-web-all-dependencies:jar:2.0.0-SNAPSHOT in https://jcenter.bintray.com/ was cached in the local repository, resolution will not be reattempted until the update interval of jcenter has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :openwebstart

~/Work/OpenWebStart$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

~/Work/OpenWebStart$ javac -version && java -version
javac 11.0.4
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)
~/Work/OpenWebStart$ mvn --version
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.4, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.0.0-36-generic", arch: "amd64", family: "unix"

I can create a INSTALL file with what is needed

**Comment by sclassen** [comment]
You need to first clone icedtea-web you find it on github under AdoptOpenjdk.
Then do a mvn clean install of icedtea-web. Afterwards you can build openwebstart.

Most of the code is located in icedtea-web. Also the parts you are looking into...
