### ISSUE TITLE
Find Local JVM On Launch

### ISSUE THREAD

**Issue by nstrauss** [karakun/OpenWebStart#126]
Currently if update strategy is set to "Use local if available" via GUI or ows.jvm.manager.updateStrategy=DO_NOTHING_ON_LOCAL_MATCH via response.varfile, that local JVM is not automatically discovered on launch.  

<img width="629" alt="Screen Shot 2019-12-10 at 9 21 31 AM" src="https://user-images.githubusercontent.com/17690356/70542577-8dd1bd80-1b2e-11ea-9ec5-5a92426f3829.png">

That means no JVM is available to launch JNLP and as a result load fails. If no JVM is defined and "use local" is set then OpenWebStart should automatically scan local Java paths and use the first available.

Repro on Mac...

1. Install OpenWebStart unattended using a response.varfile where ows.jvm.manager.updateStrategy=DO_NOTHING_ON_LOCAL_MATCH `/OpenWebStart.app/Contents/MacOS/JavaApplicationStub -q -varfile /response.varfile`
2. Launch a JNLP file. 
3. OpenWebStart fails to run because there's no discovered JVM. 

If no JVM is available then equivalent function to clicking "Find local" on JVM Manager settings page should run and then attempt to launch JNLP using the first discovered JVM.

**Comment by sclassen** [comment]
Maybe the labels are a bit miss-leading, but the update strategy is about downloading JVMs from a central server.
It is behaving as designed. In order to detect local JVMs there is a button "Find local JVMs" below the list of known JVMs

**Comment by nstrauss** [comment]
Thank you for the clarification @sclassen Guess I'm not trying to say the feature as is doesn't work. As designed it does. I'm poking a little more at the end user workflow for getting their JNLP running as fast as possible. Consider this scenario...

1. User installs OpenWebStart
2. Double-click JNLP file
3. OpenWebStart launches and then... does nothing. It closes. 😦 

There's no JVM discovered by OpenWebStart and as a result nothing to run from. That's a bit confusing for most standard users. By default a Zulu build downloads when there's no JVM available, but that's not the correct workflow for many users either. For example, when the JNLP file requires a specific or older Java version. In my case I specifically install the latest build of Amazon Corretto 11 and then prefer OpenWebStart use that local JVM. Except there's no way to automate that or set it via the response.varfile except for manually opening settings and clicking "Find local". This isn't terrible, but it's an extra step that I'd like to be able to remove. Two possibilities I can think of...

- Search for local JVM on launch and use that if found as long as it matches the preferred vendor
- Add a preference in response.varfile for a specific JVM search path

I understand if you're happy with the current implementation, but I'd like to know your thoughts. Thank you!

**Comment by ousudrs** [comment]
@sclassen any update on @nstrauss [comments](https://github.com/karakun/OpenWebStart/issues/126#issuecomment-564161296)?

**Comment by netopyr** [comment]
Apparently we have a different understanding of our standard users. :)

OpenWebStart was designed with primarily having non-technical people in mind. They do not know what Java is and they could not care less about the vendor and version of the JVM that is used to run their application. For them, the default workflow should work. They double-click a JNLP-file, eventually a JDK is downloaded, and the application is started. Other workflows are possible, but they need some configuration. 

In our opinion using a specific JVM, that is already installed, will be rarely used and only by technical people (e.g. by developers during development or your QA-department while testing your application with a new version of Java). This, plus the fact that your JDK could be installed anywhere and added/removed anytime, drove the decision, that some manual configuration is good enough for this kind of workflow.

I hope this clarified our design decision a bit.

**Comment by douph1** [comment]
Some exemple : Our standard users who have used JNLP for a while have already choosed a alternative JVM since Oracle has changed is licencing model.
They all have installed one since 11 month with Icedtea OJDKBuild/AdoptOpenJDK or other

My understanding is that many of standard user have already a jvm installed (not only tech people).
If OpenWebStart was out/ready last year it will not be the case and you workflow to download a jvm will bee good. ( Uninstall Oracle / install OpenWebStart and you get a JVM )

I'm agree with @nstrauss that having 
>Search for local JVM on launch and use that if found as long as it matches the preferred vendor
will be a great choice

**Comment by nstrauss** [comment]
Thanks for your thoughts @netopyr It is only a few additional steps for our fringe case. If most user workflows prefer the design as is then I don't expect changes. 

Since I can't dedicate time to contributing to this project I'll close the issue. 😀
