### ISSUE TITLE
multiple java version selection problem

### ISSUE THREAD

**Issue by fmeili1** [karakun/OpenWebStart#128]
Hi,
I've tried to use two different java version sections in the JNLP like in the following example:

```
... 
<java version="12+" java-vm-args="-showversion
      --add-modules=java.sql,java.management
      --add-exports=java.base/sun.net.www.protocol.http=ALL-UNNAMED
      --add-exports=java.base/sun.net.www.protocol.https=ALL-UNNAMED
      --add-opens=java.sql/java.sql=ALL-UNNAMED
      --add-opens=java.base/java.lang=ALL-UNNAMED
      --add-opens=java.base/java.util=ALL-UNNAMED"/>
<java version="1.8+" java-vm-args="-showversion"/>
...
```

The JNLP spec "https://docs.oracle.com/javase/10/deploy/jnlp-file-syntax.htm" has the following note:

> The j2se element specifies what Java Platform, Standard Edition Runtime Environment (JRE) versions an application is supported on and standard parameters to the Java Virtual Machine.  If several JREs are specified, then this indicates a prioritized list of the supported JREs, with the most preferred version first

(java an be used instead of j2ee)

I've installed OpenJDK 12.0.2 and activated it in the OpenWebStart JVM Manager. Together with the Java 1.8.0_222 AdoptOpenJDK version which is included in the OpenWebStart installation, the JVM Manager shows two entries and both are activated:

![image](https://user-images.githubusercontent.com/58776610/70624054-a13b6200-1bdc-11ea-894a-48cf38cf99ff.png)

When I launch the application, it uses OpenJDK 12.0.2 as expected. But when I deactivate OpenJDK 12.0.2, I thought it should run with Java 8.

![image](https://user-images.githubusercontent.com/58776610/70624248-2757a880-1bdd-11ea-8923-0f8fb5e23f50.png)
![image](https://user-images.githubusercontent.com/58776610/70624860-6b977880-1bde-11ea-8d66-4c645990c97e.png)

But first the following dialog will appear:
![image](https://user-images.githubusercontent.com/58776610/70624447-80bfd780-1bdd-11ea-84aa-59c86c92688e.png)
And when I select "No" I get the following error:
![image](https://user-images.githubusercontent.com/58776610/70624482-9af9b580-1bdd-11ea-869d-0984c445207d.png)
with the following details:
![image](https://user-images.githubusercontent.com/58776610/70624558-c2e91900-1bdd-11ea-9788-06cb3e167f30.png)
Here are the last entries from the console:

> Error: Error while handling download for 12+ (url=null)
Error while handling download for 12+ (url=null)
Trying to find local Java runtime. Requested version: '12+' Requested vendor: '*' requested os: 'WIN64' active: 'false'
Received 14 possible runtime definitions from server
Using NO_PROXY
Using NO_PROXY
Endpoint to request for Java runtimes: https://download-openwebstart.com/jvms
Trying to find remote Java runtime. Requested version: '12+' Requested vendor: '*' requested os: 'WIN64'
No local runtime found, will try to find remote runtime
Trying to find local Java runtime. Requested version: '12+' Requested vendor: '*' requested os: 'WIN64' active: 'true'
Trying to find Java runtime. Requested version: '12+', vendor: '*', os: 'WIN64', server-url: 'null'
searching for JRE with version string '12+'
Saving runtime cache to filesystem
Adding runtime definition
Saving runtime cache to filesystem
Adding runtime definition
Saving runtime cache to filesystem
Clearing runtime cache
Loading runtime cache from filesystem
result: null
arg: net.sourceforge.jnlp.JNLPFile@2dfe59ed
call privileged method: checkSingleInstanceRunning
Jars not ready to provide attribute Application-Name
Jars not ready to provide attribute Application-Name
Acquired shared lock on C:\Users\test\AppData\Local\Temp\test\netx\locks\netx_running to indicate javaws is running
UNIQUEKEY=1576069986530-2018528061-http://test:8080/test/test.jnlp
good - your JRE - 1.8.0_212 - match requested JRE - 1.8+
Warning - your JRE - 1.8.0_212 - does not match requested JRE - 12+
Acceptable vendor tag found, contains: private
...

What I've expected is the following behavior: When OpenJDK 12 is installed and activated on the system, the application should run with Java 12. If Java 12 will not be available (deactivated or completely removed), the application should run with Java 8.

I don't know how to achieve this. Maybe I've missed something and do something wrong in JNLP file.

The test was done on Windows 10.

Thank's in advance for your feedback.
Frank

**Comment by hendrikebbers** [comment]
what happens if you remove Java 12 from your system? Is it than running with 8?

**Comment by fmeili1** [comment]
No, OpenWebStart tries to download "Java 12+" which fails. The logfile shows that Java 8 was found, but it was not used and the same error occurs.
