### ISSUE TITLE
Desktop Menu , Desktop Application Name Issue

### ISSUE THREAD

**Issue by ywuliu** [karakun/OpenWebStart#136]
openwebstart version 1.1

Issue: application name like: DEV (DEV})
what it is supposed to be: DEV

How to reproduce it:
1: in launch.jnlp:
<title>DEV</title>
2: I used maven to create web app:
                     <manifestEntries>
                            <Application-Name>DEV</Application-Name>
                        </manifestEntries>

**Comment by sclassen** [comment]
Could you tell where you see the string "DEV (DEV})"?
Window title, log file, ???

**Comment by ywuliu** [comment]
Most likely, it works in openwebstart version 1.0.

**Comment by ywuliu** [comment]
In windows: Menu name,  Desktop Application name.
In Mac:  /Applications/DEV (DEV}).app ( it does not work anyway)

**Comment by ywuliu** [comment]
![Untitled](https://user-images.githubusercontent.com/39272732/70942354-7d34b200-201c-11ea-9643-8d59130f2015.jpg)

**Comment by ywuliu** [comment]
By the way, when I use maven to create Web Application:
code is: 
            < manifestEntries >                            
                            < Application-Name>DEV< /Application-Name>
                        < /manifestEntries >
I add " " after < to make sure you can see it

**Comment by ywuliu** [comment]
actually, the name under menu: "All Programs" is right.
![Untitled2](https://user-images.githubusercontent.com/39272732/70944267-b707b780-2020-11ea-8696-fc8af38ece2a.jpg)

**Comment by sclassen** [comment]
Could you paste the JNLP file for the DEV application.
We are especially interested in the `<information>` part.
Also can you check in the manifest of the main jar if there is an entry for `Application-Name`

**Comment by sclassen** [comment]
Most likely this is caused by the implementation of ITW `WindowsDesktopEntry`
The methods `getDesktopIconFileName()` and `createWindowsMenu()` use different data to generate the name of the corresponding *.lnk file

**Comment by ywuliu** [comment]
thanks , @sclassen . It is not an issue. there is no Application-Name in manifest but it is in maven-jar-plugin and webstart-maven-plugin config. I found that getTitleFromManifest()  used Application-Name in webstart-maven-plugin (it is DEV} )

**Comment by sclassen** [comment]
reopening this issue, because we need to make sure that both menu and desktop entry use same logic to name the *.lnk file

**Comment by ywuliu** [comment]
OK, thanks, @sclassen.
