### ISSUE TITLE
Forward debug options to the JVM

### ISSUE THREAD

**Issue by jantz** [karakun/OpenWebStart#138]
Hello,
with the Oracle JRE 8 I have used debug options to debug our WebStart application remotely.
With the following lines (git bash on Windows) I was able to do that:

```bash
export JAVAWS_VM_ARGS="-Xdebug -Dnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,address=8001,suspend=y"

/c/Program\ Files\ \(x86\)/Java/jre1.8.0_202/bin/javaws.exe -Xnofork sps_client.jnlp
```
I can't find anything in the documentation about that.
Is that not implemented or do miss something?

Best Regards

**Comment by sclassen** [comment]
It is currently undocumented. We will make this more visible in the future.
Until then you can do the following:

`javaws.exe -DOWS_REMOTE_DEBUGGING_PORT=8001 sps_client.jnlp`
This will suspend the application and wait for a debugger to attach to the port (you can change the port number if you like)
