### ISSUE TITLE
Can not add local VMs in OpenWebStart 1.1.1 under Windows.

### ISSUE THREAD

**Issue by sMOTIVEEd** [karakun/OpenWebStart#142]
Hello support team,
I just installed OpenWebstart 1.1.1. But I can't add locally installed VM under JVM-Manager-tab in the settings application.
I can choose a directory containing a JDK, but when i select it, nothing happen.
 
![OpenWebStart-Settings](https://user-images.githubusercontent.com/58225182/71025989-813dfe00-2108-11ea-96c1-741920d356f4.png)

Kind regards
Eduard

**Comment by sclassen** [comment]
This was fixed with #137 will be delivered with next release
