### ISSUE TITLE
Missing certificate: Digicert Global CA G2

### ISSUE THREAD

**Issue by don-vip** [karakun/OpenWebStart#147]
This is an upstream bug report for
https://josm.openstreetmap.de/ticket/18390

Our application (JOSM) tries to access remote files hosted on cloudfront.net, for example:
https://d1cuyjsrcm0gby.cloudfront.net/tO-u2htM0aYh-aewXJ6zkA/thumb-320.jpg

When we run it with OpenWebStart 1.1.1 and default JRE (Azul Community 11.0.5-LTS) we face a security warning stating Digicert Global CA G2 is untrusted. Indeed, I can't find it in the "Certificates" OWS settings.

I don't really know if:
- OWS uses certificates from the running JRE (in this case Azul Community) and so it would be a problem on Azul side?
- OWS uses internal JVM for the certificate (in this case AdoptOpenJDK 8u212) and so it would be a problem on AdoptOpenJdk side? I found https://github.com/AdoptOpenJDK/openjdk-build/issues/563 which might be related
- OWS ships its own certificates and so the bug happens here?

**Comment by hendrikebbers** [comment]
In general I assume that AdoptOpenJDK does not affect the certificates of the running application since the Adopt JVM is not used here. It is only used to start the Settings App from OWS and trigger an app start (download JNLP, create class path, find matching Java version...)

As far as I understand you the file is loaded at runtime and is not part of the JNLP file (as a resource or something), right?

Have you ever tried to start your application with the Azul JVM "by hand" (without OWS)?

Is it possible to get a small Sample JNLP app to test the issue?

**Comment by don-vip** [comment]
> As far as I understand you the file is loaded at runtime and is not part of the JNLP file (as a resource or something), right?

You're perfectly right.

> Have you ever tried to start your application with the Azul JVM "by hand" (without OWS)?

I just tried and I can't reproduce the issue. So it appears Azul is not at fault. The images load fine this way.

> 
> Is it possible to get a small Sample JNLP app to test the issue?

Not exactly a small JNLP file but it's not too much complicated:
1. Launch https://josm.openstreetmap.de/download/josm-latest.jnlp
2. F12 to open preferences
3. Click on fourth tab (plugins), click on "Download list", then search for "Mapillary" plugin, select it and click on "OK" to install the plugin
4. When asked for restart, click Yes
5. Select File -> Download Data (Ctrl-Shift-Down)
6. Click on "Areas around places" tab, then type "Wettsteinbrücke, Basel" and click on "Search..."
7. Select the first result, then click on "Download"
8. You now have OSM data around Wettsteinbrücke. Press Ctrl+comma shortcut to download Mapillary images from Cloudfront CDN
9. Move your mouse to hlighlight a green or blue circle to display the image. You will notice the security warning suggesting the Digical Global CA G2 certificate has not been loaded by the running JVM

**Comment by hendrikebbers** [comment]
@don-vip THX for the description. We will check that later.

**Comment by hendrikebbers** [comment]
@don-vip 
My first idea is to create a sample that just tries to download https://d1cuyjsrcm0gby.cloudfront.net/tO-u2htM0aYh-aewXJ6zkA/thumb-320.jpg

By doing so I would have a small example for debugging. Do you do some specific things with the Java Keystore in your application or do you assume that such sample should show the error.

**Comment by hendrikebbers** [comment]
@don-vip in addition: Can you try it with AdoptOpenJDK?

**Comment by don-vip** [comment]
@hendrikebbers  I've tested directly with Adopt and don't get the issue, it happens only when running from OWS. We're doing some stuff with the Java Keystore on Windows, but the bug report is from macOS, so it's not relevant. Other certificate stuff we do is that we load additional native certificates from the OS for a few web servers that use CA not included in the JDK, but it's mainly for offficial government websites and Digicert is not concerned by this. So the small sample you have in mind should reproduce the problem, I will look into it.

**Comment by hendrikebbers** [comment]
@don-vip looks like the error can not be reproduced this way. A colleague created a minimal sample and just wrote that the image is loaded and shown on windows. Will add more information later.

**Comment by hendrikebbers** [comment]
@don-vip while it is working fine on windows I get a "untrusted certificate" dialog.
<img width="1048" alt="cert-error" src="https://user-images.githubusercontent.com/9443847/71885069-e13d2880-3139-11ea-85d5-dcf350d90942.png">

**Comment by hendrikebbers** [comment]
looks like it only happens when starting the app with WebStart. By starting the app with Azul or Adopt manually the problem do not happen.

**Comment by sclassen** [comment]
debugging this is a pain.
So far we notice the following:
the certificate chain is cross signed with a Verisign certificate. This seams to be causing some troubles.
![certs](https://user-images.githubusercontent.com/1795224/71903426-5b82a280-3164-11ea-8a36-3fca4dee67b5.png)
Others have reported that this can cause problems:
https://discussions.qualys.com/thread/18356-symantec-distrust-warning-shown-for-new-digicert-certificate

**Comment by sclassen** [comment]
Also we see that the trust store is created slightly different when running OWS compared to executing the application in a plain JVM.
Concretely this means the class `X509TrustManagerImpl` is initialized with the following values:
* OWS: `validatorType="Simple"`
* PlainJava: `validatorType="PKIX"`

Finally we see the following exception (which is not presented to the UI or the log)...
```
sun.security.validator.ValidatorException:
TLS Server certificate issued after 2019-04-16 and anchored by a distrusted legacy Symantec root 
CA: CN=VeriSign Class 3 Public Primary Certification Authority - G5, OU="(c) 2006 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
```
and the corresponding certificate
```
[
[
  Version: V3
  Subject: CN=VeriSign Class 3 Public Primary Certification Authority - G5, OU="(c) 2006 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
  Signature Algorithm: SHA1withRSA, OID = 1.2.840.113549.1.1.5

  Key:  Sun RSA public key, 2048 bits
  params: null
  modulus: 22109471102059671383796642714942393631149792360856487955190294587841800871022486252652612163196360832938367608763978013876844944237576704237206902072810376180366897841695320192789360300658269712766474225042097261456189264772686300705672328691871464945536513831768596383894122798581104077921511815271705394605095257256954381366139644740877956016759414080557948459417160074173313082409422023967584984099389949088073277478112907997447136173994433125025479812790590943737038696590266840534396683337181295383175344548120097700121250428676269067140626584500149856482388498317203907790209503513966223821253856296202557465877
  public exponent: 65537
  Validity: [From: Wed Nov 08 01:00:00 CET 2006,
               To: Thu Jul 17 01:59:59 CEST 2036]
  Issuer: CN=VeriSign Class 3 Public Primary Certification Authority - G5, OU="(c) 2006 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
  SerialNumber: [    18dad19e 267de8bb 4a2158cd cc6b3b4a]

Certificate Extensions: 4
[1]: ObjectId: 1.3.6.1.5.5.7.1.12 Criticality=false
Extension unknown: DER encoded OCTET string =
0000: 04 61 30 5F A1 5D A0 5B   30 59 30 57 30 55 16 09  .a0_.].[0Y0W0U..
0010: 69 6D 61 67 65 2F 67 69   66 30 21 30 1F 30 07 06  image/gif0!0.0..
0020: 05 2B 0E 03 02 1A 04 14   8F E5 D3 1A 86 AC 8D 8E  .+..............
0030: 6B C3 CF 80 6A D4 48 18   2C 7B 19 2E 30 25 16 23  k...j.H.,...0%.#
0040: 68 74 74 70 3A 2F 2F 6C   6F 67 6F 2E 76 65 72 69  http://logo.veri
0050: 73 69 67 6E 2E 63 6F 6D   2F 76 73 6C 6F 67 6F 2E  sign.com/vslogo.
0060: 67 69 66                                           gif


[2]: ObjectId: 2.5.29.19 Criticality=true
BasicConstraints:[
  CA:true
  PathLen:2147483647
]

[3]: ObjectId: 2.5.29.15 Criticality=true
KeyUsage [
  Key_CertSign
  Crl_Sign
]

[4]: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 7F D3 65 A7 C2 DD EC BB   F0 30 09 F3 43 39 FA 02  ..e......0..C9..
0010: AF 33 31 33                                        .313
]
]

]
  Algorithm: [SHA1withRSA]
  Signature:
0000: 93 24 4A 30 5F 62 CF D8   1A 98 2F 3D EA DC 99 2D  .$J0_b..../=...-
0010: BD 77 F6 A5 79 22 38 EC   C4 A7 A0 78 12 AD 62 0E  .w..y"8....x..b.
0020: 45 70 64 C5 E7 97 66 2D   98 09 7E 5F AF D6 CC 28  Epd...f-..._...(
0030: 65 F2 01 AA 08 1A 47 DE   F9 F9 7C 92 5A 08 69 20  e.....G.....Z.i 
0040: 0D D9 3E 6D 6E 3C 0D 6E   D8 E6 06 91 40 18 B9 F8  ..>mn<.n....@...
0050: C1 ED DF DB 41 AA E0 96   20 C9 CD 64 15 38 81 C9  ....A... ..d.8..
0060: 94 EE A2 84 29 0B 13 6F   8E DB 0C DD 25 02 DB A4  ....)..o....%...
0070: 8B 19 44 D2 41 7A 05 69   4A 58 4F 60 CA 7E 82 6A  ..D.Az.iJXO`...j
0080: 0B 02 AA 25 17 39 B5 DB   7F E7 84 65 2A 95 8A BD  ...%.9.....e*...
0090: 86 DE 5E 81 16 83 2D 10   CC DE FD A8 82 2A 6D 28  ..^...-......*m(
00A0: 1F 0D 0B C4 E5 E7 1A 26   19 E1 F4 11 6F 10 B5 95  .......&....o...
00B0: FC E7 42 05 32 DB CE 9D   51 5E 28 B6 9E 85 D3 5B  ..B.2...Q^(....[
00C0: EF A5 7D 45 40 72 8E B7   0E 6B 0E 06 FB 33 35 48  ...E@r...k...35H
00D0: 71 B8 9D 27 8B C4 65 5F   0D 86 76 9C 44 7A F6 95  q..'..e_..v.Dz..
00E0: 5C F6 5D 32 08 33 A4 54   B6 18 3F 68 5C F2 42 4A  \.]2.3.T..?h\.BJ
00F0: 85 38 54 83 5F D1 E8 2C   F2 AC 11 D6 A8 ED 63 6A  .8T._..,......cj
]
```

**Comment by sclassen** [comment]
It looks like if the `validatorType="Simple"` is set then the certificate validator does not recognize that there exists a shorter certificate chain which leads to a different root which is not un-trusted.

But we need to research more to understand what the side effects would be if we change the validator type to PKIX...

**Comment by don-vip** [comment]
@sclassen thanks for the investigation! I will take a look too, now we have a clue :)

**Comment by don-vip** [comment]
@sclassen the PKIX TrustManagerFactory is registered [here](https://github.com/openjdk/jdk/blob/6d4ef5aaf3a66eec5a54bda2371a9a34d332ba74/src/java.base/share/classes/sun/security/ssl/SunJSSE.java#L94) and is available with "PKIX", "SunPKIX", "X509" "X.509" names.

The simple (legacy) TrustManagerFactory is only registered under "SunX509" name. ITW explicitly loads the SunX509 trust manager [here](https://github.com/AdoptOpenJDK/IcedTea-Web/blob/452627e045356e630e3e1c817cf47228eb29a7b9/core/src/main/java/net/sourceforge/jnlp/security/VariableX509TrustManager.java#L136).

The [JSSE reference guide](https://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/JSSERefGuide.html#InstallationAndCustomization) indicates that PKIX is the "Default trust manager factory algorithm name" so ITW should probably switch to it.

**Comment by sclassen** [comment]
fix in https://github.com/AdoptOpenJDK/IcedTea-Web/pull/564
