### ISSUE TITLE
JNLP installers?

### ISSUE THREAD

**Issue by ameenross** [karakun/OpenWebStart#150]
I'm trying to get an application to run in OWS, and it exits with this error:

    net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Unknown Main-Class. Could not determine the main class for this application.

The jnlp file points to another jnlp which is an installer. When I try to run the installer directly, I get this error.

    net.sourceforge.jnlp.LaunchException: Fatal: Unsupported Feature: Installers not supported. JNLP installer files are not yet supported.

Is that the reason of the failure? Any plans on implementing them?

**Comment by netopyr** [comment]
Hi @ameenross,

we currently have no plans to support installers, because none of our sponsors requires them. Would you be interested in sponsoring the implementation?

Not sure though, if that is the reason for the first exception.

**Comment by ameenross** [comment]
Hi @netopyr,

The first error is the deepest exception in a chain that contains `Exception while initializing extension installer.jnlp`. I also saw a logline that installer.jnlp was registered as classloader. Is that enough information to determine what's going wrong or should I send complete logs? I'd rather not have to sanitize so many loglines, so I hope to avoid that :)

I'm not the developer of the application, but the company developing it might be interested in sponsoring. I don't know if they're willing to invest in moving away from javaws, IMO you might as well get the app working in OpenWS and support that.

**Comment by netopyr** [comment]
Hi @ameenross,
I do not think that it makes to investigate this any further, if installer support is mandatory for your application, because this will definitely not work. Do you know what the company that developed your tool suggests?

**Comment by eracknaphobia** [comment]
Noticing the same error here. Funny part is if i go back to version 0.4.0 it works. Anything newer produces the same error screen?

**Comment by ameenross** [comment]
It appears the developers have written a ClickOnce version. So now the application requires dotNET *and* Java :man_facepalming:
