### ISSUE TITLE
OpenWebStart ignores JVM configuration setting and always uses default JVM

### ISSUE THREAD

**Issue by pkeusem** [karakun/OpenWebStart#156]
We have a couple of different installations of OpenWebStart 1.1.1 both on Windows 10.  We are trying to test OpenWebStart with Azul Systems Java 8.  We are able to add the JVMs in the JVM manager tab of the OpenWebStart settings app and start our test application but it always starts running on the builtin AdopOpenJDK 1.8.0_212 JRE.

**Comment by sclassen** [comment]
How do you determine if your application is started with AdopOpenJDK 1.8.0_212?

OWS will always lunch a JVM using the mentioned JRE to parse the JNLP file.
Once it has completed this it will spawn a second JVM according to the information it found in the JNLP. This second JVM will use a different JRE.

**Comment by pkeusem** [comment]
Our test application logs information about the JVM it is running on. 

The test client application logs the following JVM information:
[MESSAGE_ALL][Tue Jan 14 20:18:19 IST 2020] 1/14/20 20:18:19.391 [AWT-EventQueue-1] Java Version = 1.8.0_212
[MESSAGE_ALL][Tue Jan 14 20:18:19 IST 2020] 1/14/20 20:18:19.391 [AWT-EventQueue-1] Java VM version = 25.212-b03
[MESSAGE_ALL][Tue Jan 14 20:18:19 IST 2020] 1/14/20 20:18:19.392 [AWT-EventQueue-1] Java VM name = OpenJDK 64-Bit Server VM
[MESSAGE_ALL][Tue Jan 14 20:18:19 IST 2020] 1/14/20 20:18:19.392 [AWT-EventQueue-1] Java Vendor = AdoptOpenJDK
[MESSAGE_ALL][Tue Jan 14 20:18:19 IST 2020] 1/14/20 20:18:19.392 [AWT-EventQueue-1] Java VM vendor = 
[MESSAGE_ALL][Tue Jan 14 20:18:19 IST 2020] 1/14/20 20:18:19.392 [AWT-EventQueue-1] Java home = c:\users\administrator\appdata\local\openwebstart\jre

I am attaching a screen snapshot and the logs from a recent run.

Screen snapshot of the OpenWebStart JVM config tab with settings:
[OWS-JVM-Selection](https://user-images.githubusercontent.com/13780640/72373107-37c3dd00-36cd-11ea-9bed-b5113ce79a29.png)

The test client application log:
[itw-clienta-2020-01-14_20_18_19.384.log] (https://github.com/karakun/OpenWebStart/files/4060808/itw-clienta-2020-01-14_20_18_19.384.log)

OpenWebStart logs:
[itw-javantx-2020-01-14_20_18_06.742.log](https://github.com/karakun/OpenWebStart/files/4060809/itw-javantx-2020-01-14_20_18_06.742.log)
[itw-javantx-2020-01-14_20_18_06.910.log](https://github.com/karakun/OpenWebStart/files/4060810/itw-javantx-2020-01-14_20_18_06.910.log)

**Comment by sclassen** [comment]
OK your application is an applet.
Applet are currently not supported in OWS. Consider migrating to a regular application

**Comment by pkeusem** [comment]
OK, where is this documented?

**Comment by sclassen** [comment]
https://openwebstart.com/feature-table/  AM-18

**Comment by pkeusem** [comment]
How do you get to that from the main page?

I cannot find any references to requirements, documentation or even downloads on the main page.

**Comment by sclassen** [comment]
we do currently have some issues with the homepage on a mobile device.
try visiting using a desktop browser and the links should be properly accessable

**Comment by pkeusem** [comment]
I am view the page from a desktop browser, Vivaldi in this case but it looks the same in Firefox.

**Comment by netopyr** [comment]
Can you please provide a screenshot? When I open the webpage in Firefox, I see the whole menu at the top of the page.

**Comment by pkeusem** [comment]
I just discovered that if I maximize my browser window, the menu appears.  If I restore the window to its normal size, the menu disappears.  This occurs in Chrome, Firefox, IE 11 and Vivaldi.

Screenshots from Vivaldi attached
![OWS-MainPage](https://user-images.githubusercontent.com/13780640/72989607-3624a400-3db4-11ea-81a1-78a154601148.png)
![OWS-MainPage-Max](https://user-images.githubusercontent.com/13780640/72989611-3886fe00-3db4-11ea-80e7-6d14e4964b8c.png)

**Comment by sclassen** [comment]
the homepage has been updated to fix the issue with the github banner
