### ISSUE TITLE
javaws process does not exit when the Java application is closed

### ISSUE THREAD

**Issue by pkeusem** [karakun/OpenWebStart#158]
We are able to start and run our Java test application using OpenWebStart 1.1.1 successfully but when we close/exit from the test app, the javaws process continues running.

**Comment by sclassen** [comment]
Would you be able to share your test application in order to help us fix this issue?

**Comment by sclassen** [comment]
@pkeusem it would be really appreciated if you could provide us your test application

**Comment by janakmulani** [comment]
CAN NOT reproduce with following steps:

0. Using itw-settings set deployment.console.startup.mode=DISABLE

1. Start the OWS Sample's server.

2. Have the local file webstart-monitor.jnlp

3. >javaws webstart-monitor.jnlp

4. App starts. Close the window. DefaultCloseOperation is EXIT_ON_CLOSE.

5. In task manager the javaws.exe process keeps running.

6. **after few seconds the process ends.**

If in the above case console startup mode is SHOW

4. App starts. Two console windows are shown. Close the window. DefaultCloseOperation is EXIT_ON_CLOSE.

5. The client app console window closes with the app. The OWS console keeps showing. The javaws.exe process is shown  running.

6. **Close the OWS console window. The javaws.exe process  ends immediately.**

**Comment by reinpeter** [comment]
Same issue here, OWS 1.1.6
Console: SHOW, then javaws exits after console closed manually, after application exits.
Console: HIDE/DISABLE, javaws.exe keeps running after application exits
Java: latest zulu.
OWS Settings: default, except custom jvm download URL.

**Comment by sclassen** [comment]
@reinpeter Would be great to have access to your application so we can finally reproduce this issue and maybe find a fix

**Comment by reinpeter** [comment]
@sclassen  will it work if you can just 'start' the app from our site or will you need sources?

**Comment by sclassen** [comment]
will try with the first one.
If we find that there are threads hanging in your code we can come back to you for further debugging

**Comment by reinpeter** [comment]
@sclassen can i send you a test link by private message somehow? Or can i reach you at openwebstart@karakun.com

**Comment by sclassen** [comment]
Yes the above mail reaches the entire OWS team

**Comment by undergraver** [comment]
Hi,

We are facing the same issue: after we close the application javaws.exe remains active and consumes quite some CPU.

Please let us know if you need anything and we will provide. We are using OpenWebStart 1.1.6 (latest to date).

Thanks!

**Comment by janakmulani** [comment]
We have fixed this issue. It will be available in the next release (1.1.7) of OWS.

**Comment by AndreasEhret** [comment]
Fixed with current release 1.1.7
