### ISSUE TITLE
JVM Manager: settings: adoptOpenJDK fail

### ISSUE THREAD

**Issue by ywuliu** [karakun/OpenWebStart#160]
I tried:
https://adoptopenjdk.net/?jvmVariant=hotspot
https://adoptopenjdk.net
https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=hotspot

**Comment by sclassen** [comment]
Where did you enter these values?

**Comment by ywuliu** [comment]
@sclassen : In JVM Manager->Settings->Default update server URL

**Comment by sclassen** [comment]
OWS expects to find an xml describing the available JVMs at the given location.
Have a look at http://download-openwebstart.com/jvms

Also the mentioned zip archives are expected to contain the JDK in the root folder.

We will improve this and the number of available JVMs in the future
