### ISSUE TITLE
OpenJfx with OpenWebstart lets crash the whole app

### ISSUE THREAD

**Issue by AM-Xdev** [karakun/OpenWebStart#162]
After getting OpenJfx working with OpenWebstart. we have now the problem that the OWS-App completely crashes without any hint why.

[openwebstart-openfx-test.zip](https://github.com/karakun/OpenWebStart/files/4071372/openwebstart-openfx-test.zip)

Unzip
run mvn clean package -P deployment
unzip /target/openwebstart-openfx-test-0.0.1-SNAPSHOT.zip to an localhost webserver of your choice.
open Openwebstart-OpenFx-Test.jnlp : App crashes without any hint.
open openfx-classpath-start.cmd : its works

**Comment by AM-Xdev** [comment]
Does anyone had an Idea.
Update to Openjfx 13.0.2 doesnt work either.

**Comment by hendrikebbers** [comment]
Hi,
we are currently working on a complete new class loader for OpenWebStart that fixes several problems with native content and os specific resources. Since this is a big change we still need some time to get this done and integrated.

**Comment by AndreasEhret** [comment]
Please try 3.0.0-alpha1

**Comment by AM-Xdev** [comment]
For me 3.0.0-alpha1 doesn't work.

For my Test with 3.0.0-alpha1 i have to replace the buildin jre with JDK 11.07 then it OWS find an JDK 11 for my JNLP.

To reproduce the error download
[openwebstart-openfx-13-test.zip](https://github.com/karakun/OpenWebStart/files/4620372/openwebstart-openfx-13-test.zip)

Unzip
run "mvn clean package -P deployment"
unzip /target/openwebstart-openfx-test-0.0.1-SNAPSHOT.zip to an localhost webserver of your choice.
open Openwebstart-OpenFx-Test.jnlp : App crashes without any hint.
open openfx-classpath-start.cmd : its works

**Comment by janakmulani** [comment]
Please see this. https://github.com/karakun/OpenWebStart/blob/master/documentation/faq/FAQ.adoc#how-to-run-openjfx-based-javafx-applications-with-openwebstart

I have tested the class with browser that you sent.

**Comment by AM-Xdev** [comment]
My cmd is working fine.

I Have tried the FAQ and made the following changes:
Using HelloWorld11Launcher.
removing native lib

here the Code:
[openwebstart-openfx-test-with-HelloWorld11Launcher-OpenJFX-13.0.2.zip](https://github.com/karakun/OpenWebStart/files/4683159/openwebstart-openfx-test-with-HelloWorld11Launcher-OpenJFX-13.0.2.zip)

but it crashed: 
[log_openjavafx_13.0.2.zip](https://github.com/karakun/OpenWebStart/files/4683169/log_openjavafx_13.0.2.zip)

changing to OpenJFX11.0.2
but it crashes:
[log_openjavafx_11.0.2.zip](https://github.com/karakun/OpenWebStart/files/4683172/log_openjavafx_11.0.2.zip)

**Comment by AM-Xdev** [comment]
After Remote Debugging the OpenWebstart I've get sich error:
![2020-05-27_14h36_41](https://user-images.githubusercontent.com/40858279/83019851-eab32880-a027-11ea-97fa-c14c80acb688.png)

**Comment by janakmulani** [comment]
Please see https://board.karakun.com/viewtopic.php?f=21&t=44

Let's continue the discussion there.

**Comment by hendrikebbers** [comment]
@AM-Xdev @janakmulani the discussion should happen here as it was started as a GitHub issue and is easily accessible by everyone.

**Comment by hendrikebbers** [comment]
I had a deeper look in the JFX bug this morning. From my point of view this issue is a clone of https://github.com/karakun/OpenWebStart/issues/125 @AM-Xdev can you please confirm? In that case we can close this issue and continue in https://github.com/karakun/OpenWebStart/issues/125 I will add some new information to https://github.com/karakun/OpenWebStart/issues/125

**Comment by AM-Xdev** [comment]
After my debugging I agree it all about the DLL's and com.sun-Packages. So we can close this Issue
