### ISSUE TITLE
Interims release fixing issue #142 available?

### ISSUE THREAD

**Issue by btreut** [karakun/OpenWebStart#163]

**Comment by btreut** [comment]
being hitten by similar problems as described (and hopefully solved) in issue #142 I am searching for an interims release, which fixes #142 

background: we are using since quite some time the Alex Kaskos ojdkbuild version with the webstart launcher, but some of our customers have obscure problems, which appear to be connected to badly matched proxy settings.  

In the release announcement of 17-Dec-2019 there was a note about better support for the proxy settings, so started testing it.

**Comment by netopyr** [comment]
We plan to do a bugfix release either tomorrow or in the beginning of next week.
