### ISSUE TITLE
how to install open jws on Oracle linux server OS

### ISSUE THREAD

**Issue by yuvraj18yadav** [karakun/OpenWebStart#165]
I am not able to install open jws setup on my Linux . 
My linux details are as follows: 
Name: Oracle Linux Server
Version: 7.5 
ID="ol"
home_url="https://linux.oracle.com/"

**Comment by netopyr** [comment]
Our setup would allow us to build an installer for Linux. But as this has no priority for our current sponsors, we do not have the resources to maintain another installer. Would you be interested in sponsoring this?

**Comment by yuvraj18yadav** [comment]
You have already provided setup for Linux Platform in the form of Debian Package. We are not able to install Debian Installer for Oracle Linux . Can you please provide steps for how to install Open JWS in Oracle Linux Platform .

**Comment by sclassen** [comment]
we support debian because some of our devs are using and testing on it.
other linux distributions are currently not supported, as we do not have the funding to setup and maintain them
