### ISSUE TITLE
JVM Manager not working in v1.1.1 (Windows 10)

### ISSUE THREAD

**Issue by swildt** [karakun/OpenWebStart#169]
Under Windows 10 it is no longer possible with version 1.1.1 to add a local JVM in the JVM Manager. I have tried this on different Windows 10 machines. With version 1.0.0 this feature was working.

**Comment by sclassen** [comment]
Any log or failure message to help us tackle this?

**Comment by swildt** [comment]
[MESSAGE_DEBUG][Thu Jan 23 17:21:04 CET 2020] Loading runtime cache from filesystem
[MESSAGE_DEBUG][Thu Jan 23 17:21:04 CET 2020] Clearing runtime cache
[MESSAGE_DEBUG][Thu Jan 23 17:21:04 CET 2020] Saving runtime cache to filesystem
[MESSAGE_DEBUG][Thu Jan 23 17:21:04 CET 2020] Adding runtime definition
[MESSAGE_DEBUG][Thu Jan 23 17:21:04 CET 2020] Saving runtime cache to filesystem
[MESSAGE_DEBUG][Thu Jan 23 17:21:04 CET 2020] Adding runtime definition
[MESSAGE_DEBUG][Thu Jan 23 17:21:04 CET 2020] Saving runtime cache to filesystem
[MESSAGE_DEBUG][Thu Jan 23 17:21:30 CET 2020] About to look for local jdks at the following locations: [F:\Programme\AdoptOpenJDK\jdk8u242-b08-jre\bin]
[MESSAGE_ALL][Thu Jan 23 17:21:30 CET 2020] No local JVMs added to the JVM Manager
[MESSAGE_DEBUG][Thu Jan 23 17:22:19 CET 2020] About to look for local jdks at the following locations: [F:\Programme\AdoptOpenJDK]
[MESSAGE_ALL][Thu Jan 23 17:22:19 CET 2020] trying to get definition of local JVM at 'F:\Programme\AdoptOpenJDK\jdk8u242-b08-jre'

**Comment by sclassen** [comment]
Can you please retry this with the current version 1.1.4

**Comment by swildt** [comment]
Thank you, with v1.1.4 it's working for me!
