### ISSUE TITLE
JVM Manager does not support SAPJVM

### ISSUE THREAD

**Issue by Jens-Schwendemann** [karakun/OpenWebStart#170]
Dear all,
I want to use SAPJVM 8.1 (8.1.060 --> relates to Oracle JDK 8u231) with OpenWebStart. I want specifically use that JVM because I'd like to run SAP PI Swing Tools (Enterprise Service Builder / Integration Builder) with it and the hosting SAP PI server only supports Java 8

Unfortunately this JVM does not get recognized when I click JVM Manager --> Add local --> <Folder of the JVM where there is subfolder bin (for JDK) and jre/bin (for JRE)>.

Here's the excerpt of the log (two tries, one for bin of JDK, one for bin of JRE)
> [MESSAGE_DEBUG][Fri Jan 24 07:56:04 CET 2020] About to look for local jdks at the following locations: [C:\Program Files\SAP\sapjvm_8\8.1.060]
> [MESSAGE_ALL][Fri Jan 24 07:56:04 CET 2020] trying to get definition of local JVM at 'C:\Program Files\SAP\sapjvm_8\8.1.060
> [MESSAGE_DEBUG][Fri Jan 24 08:00:34 CET 2020] About to look for local jdks at the following locations: [C:\Program Files\SAP\sapjvm_8\8.1.060\jre]
> [MESSAGE_ALL][Fri Jan 24 08:00:34 CET 2020] trying to get definition of local JVM at 'C:\Program Files\SAP\sapjvm_8\8.1.060\jre''

Here's the folder structure of "sapjvm_8\8.1.060"
- bin (folder)
- include (folder)
- jre (folder)
- lib (folder)
- buildinfo.txt (file)
- COPYRIGHT (file)
- src.zip (file)
- THIRDPARTYLICENSEREADME.txt (file)

Interestingly, when I try to add SAPMachine JRE 11.0.3 at C:\Program Files\SAP\sapmachine-jre\11.0.3 this was possible without problem.
- bin (folder)
- conf (folder)
- legal (folder)
- lib (folder)
- release (file)

Cheers
Jens

**Comment by sclassen** [comment]
Looks like OWS fails to detect the exact version.
Can you run the following command in the bin folder of the failing SAPJVM 8.1:
`java -XshowSettings:properties -version`
And post the output here.

**Comment by Jens-Schwendemann** [comment]
The SAPJVM includes a JDK and a JRE. Important for me would be the JRE. Here's the output of JRE\bin

C:\Program Files\SAP\sapjvm_8\8.1.061\jre\bin>java -XshowSettings:properties -version
Property settings:
    awt.toolkit = sun.awt.windows.WToolkit
    com.sap.vm.codeline = 81_REL
    com.sap.vm.compressedoops = true
    com.sap.vm.profilingserver = true
    com.sap.vm.type = opt
    com.sap.vm.version = 10
    file.encoding = Cp1252
    file.encoding.pkg = sun.io
    file.separator = \
    java.awt.graphicsenv = sun.awt.Win32GraphicsEnvironment
    java.awt.printerjob = sun.awt.windows.WPrinterJob
    java.class.path = .
    java.class.version = 52.0
    java.endorsed.dirs = C:\Program Files\SAP\sapjvm_8\8.1.061\jre\lib\endorsed
    java.ext.dirs = C:\Program Files\SAP\sapjvm_8\8.1.061\jre\lib\ext-sap
        C:\Program Files\SAP\sapjvm_8\8.1.061\jre\lib\ext
        C:\windows\Sun\Java\lib\ext
    java.home = C:\Program Files\SAP\sapjvm_8\8.1.061\jre
    java.io.tmpdir = C:\Users\schwendj\AppData\Local\Temp\
    java.library.path = C:\Program Files\SAP\sapjvm_8\8.1.061\jre\bin
        C:\windows\Sun\Java\bin
        C:\windows\system32
        C:\windows
        C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\
        C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\
        C:\ProgramData\Oracle\Java\javapath
        C:\windows\system32
        C:\windows
        C:\windows\System32\Wbem
        C:\windows\System32\WindowsPowerShell\v1.0\
        C:\windows\System32\OpenSSH\
        C:\Program Files (x86)\OpenText\Viewer\bin
        C:\Program Files (x86)\Notes
        C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
        C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
        C:\windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps
        C:\Program Files (x86)\LANDesk\Shared Files
        C:\Program Files (x86)\Hansgrohe\_Servicedesk
        C:\Program Files (x86)\Hansgrohe\_Servicedesk\WinMagic_SecureDoc_AutoLogin
        C:\Users\schwendj\AppData\Local\Microsoft\WindowsApps

        .
    java.runtime.name = Java(TM) SE Runtime Environment
    java.runtime.version = 8.1.061
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 1.8
    java.vendor = SAP AG
    java.vendor.url = http://www.sap.com/
    java.vendor.url.bug = https://support.sap.com
    java.version = 1.8.0_241
    java.vm.compressedOopsMode = 32-bit
    java.vm.info = Jan 14 2020 18:06:43 - 81_REL - optU - windows amd64 - 6 - bas2:317685 (mixed mode)
    java.vm.name = SAP Java Server VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 1.8
    java.vm.vendor = SAP AG
    java.vm.version = 8.1.061 10.0.2+000
    jdk.boot.class.path.append =
    jdk.debug = release
    line.separator = \r \n
    os.arch = amd64
    os.name = Windows 10
    os.version = 10.0
    path.separator = ;
    sun.arch.data.model = 64
    sun.boot.class.path = C:\Program Files\SAP\sapjvm_8\8.1.061\jre\lib\resources.jar
        C:\Program Files\SAP\sapjvm_8\8.1.061\jre\lib\rt.jar
        C:\Program Files\SAP\sapjvm_8\8.1.061\jre\lib\sunrsasign.jar
        C:\Program Files\SAP\sapjvm_8\8.1.061\jre\lib\jsse.jar
        C:\Program Files\SAP\sapjvm_8\8.1.061\jre\lib\jce.jar
        C:\Program Files\SAP\sapjvm_8\8.1.061\jre\lib\charsets.jar
        C:\Program Files\SAP\sapjvm_8\8.1.061\jre\lib\jfr.jar
        C:\Program Files\SAP\sapjvm_8\8.1.061\jre\classes
    sun.boot.library.path = C:\Program Files\SAP\sapjvm_8\8.1.061\jre\bin
    sun.cpu.endian = little
    sun.cpu.isalist = amd64
    sun.desktop = windows
    sun.io.unicode.encoding = UnicodeLittle
    sun.java.launcher = SAP_STANDARD
    sun.jnu.encoding = Cp1252
    sun.management.compiler = HotSpot 64-Bit Tiered Compilers
    sun.os.patch.level =
    sun.stderr.encoding = cp850
    sun.stdout.encoding = cp850
    user.country = DE
    user.dir = C:\Program Files\SAP\sapjvm_8\8.1.061\jre\bin
    user.home = C:\Users\schwendj
    user.language = de
    user.name = schwendj
    user.script =
    user.timezone =
    user.variant =

java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 8.1.061)
SAP Java Server VM (build 8.1.061 10.0.2+000, Jan 14 2020 18:06:43 - 81_REL - optU - windows amd64 - 6 - bas2:317685 (mixed mode))

Please mind that with 1.1.4 it seems be working (again?)

**Comment by sclassen** [comment]
I ran your props through a test case and they produce no error.
with the upcoming release (1.1.5 or 1.2.0) we have added more information to the log in case a JVM cannot be added.

I close this for now. Please feel free to re-open if you continue to have this issue.
