### ISSUE TITLE
java.lang.ClassNotFoundException: java.sql.Time

### ISSUE THREAD

**Issue by mmostowsski** [karakun/OpenWebStart#172]
**OpenWebstart version:** 1.1.2
**Java version:** openjdk version "13.0.1" 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9)
OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
**OS:** Windows 10
Hi,
I've got a issue with java.sql module and gson library when I launch my webstart app by OpenWebStart:
java.lang.ClassNotFoundException: java.sql.Time
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at com.google.gson.Gson.<init>(Gson.java:265)
	at com.google.gson.Gson.<init>(Gson.java:186)

The issue is correlated with JNLPClassLoader (IcedTea Web).
OpenWebstart is launching my app with args:

_About to launch external with commands: '[C:\workspace\tools\openjdk\jdk-13.0.1\bin\java.exe, "**-Xbootclasspath/a:C:\Program Files\OpenWebStart\openwebstart.jar**", -Xms64m, -Xmx256m, "@C:\Program Files\OpenWebStart\itw-modularjdk.args", net.sourceforge.jnlp.runtime.Boot, -Xnofork, -verbose, C:\workspace\temp\javawebstart (23).jnlp]'_

This causes the classes from java modules aren't loaded by PlatformClassLoader. When I add openwebstart.jar as _classpath_ instead of _bootclasspath_ then it works fine (it's use PlatformClassLoader to find/load java.sql.Time class).

**Comment by sclassen** [comment]
Sorry, the support for Java modules is not part of JSR-56.
Therefore we only have same basic support in OWS and cannot really help you.

**Comment by mmostowsski** [comment]
We have to misunderstand - our app isn't modular.. We have got a problem to load classes from basic java modules (ex. java.sql). 
It's a classloader issue. We've got a classloader hierarchy in Java 9+:
- app classloader
- platform classloader
- bootstrap classloader
(details: https://stackoverflow.com/questions/46494112/classloaders-hierarchy-in-java-9)

In class: net.sourceforge.jnlp.Launcher is set a thread context classloader as an instance of class: net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.

When app is run with openwebstart.jar as bootclasspath, then parent of JNLPClassLoader is null and it can't find any class from java modules.

When app is run with openwebstart.jar as simple classpath, then parent of JNLPClassLoader is AppClassLoader -> PlatformClassLoader and there is no problem.

If I'm not convince you, then I'll prepare very simple app with this issue

**Comment by sclassen** [comment]
we are reworking class loading for version 1.2.0.
before this release we will not investigate this issue as any finding would be invalidated by the new implemenation

**Comment by AndreasEhret** [comment]
could you give 3.0.0-alpha1 a try for your problem?

**Comment by mmostowsski** [comment]
We try 3.0.0-alpha1. And problem is solved. We are planning extended test our app with this version. Thanks!!!

**Comment by sclassen** [comment]
Greate to hear that. But be advised that this version is an alpha release and not fit for production.
See the releasenotes for known limitations

**Comment by reshmi-1** [comment]
I am facing 
[Utils] [ERROR] [Error] java.lang.NoClassDefFoundError: java/sql/Time
	at gherkin.deps.com.google.gson.Gson.&lt;init&gt;(Gson.java:232) when I have tried to send mail from the pom.
Could you help me?
