### ISSUE TITLE
-Xnosplash- not work in OpenWebStart 1.1.1 on Windows 10.

### ISSUE THREAD

**Issue by alslw** [karakun/OpenWebStart#176]
Hi
    From code path
![image](https://user-images.githubusercontent.com/12932352/73341893-258e9500-42b0-11ea-8946-5afa3c270ed9.png)

    I try to test by run command "C:\Program Files\OpenWebStart\javaws.exe" "http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp" -Xnosplash- to hide splash screen of OpenWebStart but it still display splash screen of OpenWebStart.
Log from Java Console:
About to launch external with commands: '["C:\Users\somphong\.cache\icedtea-web\jvm-cache\Zulu Community Edition-1.8.0_222\bin\java.exe", "-Xbootclasspath/a:C:\Program Files\OpenWebStart\openwebstart.jar", net.sourceforge.jnlp.runtime.Boot, -Xnofork, -verbose, http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp, -Xnosplash-]'
using java runtime at 'C:\Users\somphong\.cache\icedtea-web\jvm-cache\Zulu Community Edition-1.8.0_222' for launching managed application
Found JVM JavaRuntime{version=1.8.0_222, vendor=Zulu Community Edition, operationSystem=WIN64}
Received 14 possible runtime definitions from server
Using NO_PROXY
Using NO_PROXY
Endpoint to request for Java runtimes: https://download-openwebstart.com/jvms
Trying to find remote Java runtime. Requested version: '1.8*' Requested vendor: '*' requested os: 'WIN64'
Local runtime JavaRuntime{version=1.8.0_222, vendor=Zulu Community Edition, operationSystem=WIN64} found but remote endpoint is checked for newer versions
Trying to find local Java runtime. Requested version: '1.8*' Requested vendor: '*' requested os: 'WIN64' active: 'true'
Trying to find Java runtime. Requested version: '1.8*', vendor: '*', os: 'WIN64', server-url: 'https://download-openwebstart.com/jvms'
searching for JRE with version string '1.8*'
Saving runtime cache to filesystem
Adding runtime definition
Saving runtime cache to filesystem
Adding runtime definition
Saving runtime cache to filesystem
Clearing runtime cache
Loading runtime cache from filesystem
result: null
arg: net.sourceforge.jnlp.JNLPFile@7bba1d19
call privileged method: checkSingleInstanceRunning
Jars not ready to provide attribute Application-Name
Jars not ready to provide attribute Application-Name
Acquired shared lock on C:\Users\somphong\AppData\Local\Temp\somphong\netx\locks\netx_running to indicate javaws is running
UNIQUEKEY=1580287064385-309026374-http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp
good - your JRE - 1.8.0_212 - match requested JRE - 1.8*
Acceptable vendor tag found, contains: Refinitiv
Jars not ready to provide attribute Application-Name
Description: Refinitiv Trade Affirmation
Homepage: http://10.42.39.207:8080/test-open-webstart/null
Using MalformedXMLParser
Downloading file: http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp into: C:\Users\somphong\.cache\icedtea-web\cache\0\5\test_prod.jnlp
Will use no content-unpacker for 'http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp'
Will use no compression-unpacker for 'http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp'
isUpToDate: http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp - (v: null) = false
http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp - version null: isCached false
Using NO_PROXY
Downloading location=http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp version=null state=INCOMPLETE from http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp
Invalidating resource in cache: http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp / null
Found best URL for location=http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp version=null state=INCOMPLETE: url:http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp; responseCode:200; location: null; version: null; lastModified: 1580283433000; contentLength: 1379;
needsUpdate: http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp -> true
isUpToDate: http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp - (v: null) = false
http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp - version null: lastModified cache:1580275575000 actual:1580283433000 -> false
http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp - version null: isCached true
isCached: remote size:1375 cached size:1375 -> true
Best url for location=http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp version=null state=INCOMPLETE is http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp by HEAD
URL connection 'http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp' header fields: {Keep-Alive=[timeout=20], Accept-Ranges=[bytes], null=[HTTP/1.1 200], ETag=[W/"1379-1580283433000"], Connection=[keep-alive], Last-Modified=[Wed, 29 Jan 2020 07:37:13 GMT], Content-Length=[1379], Date=[Wed, 29 Jan 2020 08:37:43 GMT], Content-Type=[application/x-java-jnlp-file]}
Using NO_PROXY
Using NO_PROXY
Candidate URLs for location=http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp version=null state=INCOMPLETE: [http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp]
needsUpdateCheck: http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp -> true
isCached: http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp - (v: null) = true
isCached: remote size:1375 cached size:1375 -> true
result: null
call privileged method: getCodeBase
JNLP file location: http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp
Proceeding with jnlp
Selected ProxyProvider : OPERATION_SYSTEM
Starting security dialog thread
using com.openwebstart.extensionpoint.OwsExtensionPoint extension point
Calling ITW Boot with args [-verbose, http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp, -Xnosplash-].
RelevantJavawsArgs: '[-verbose, http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp, -Xnosplash-]'
Checking if installation time (1579771864788) is after last initial config time (1579771866663)
Property 'ows.install4j.propertyUpdate' is unknown.
Loading USER level properties from: file:/C:/Users/somphong/.config/icedtea-web/deployment.properties
Property 'ows.install4j.propertyUpdate' is unknown.
Loading USER level properties from: file:/C:/Users/somphong/.config/icedtea-web/deployment.properties
Ico provider registered correctly.
Ico provider registered correctly.
OS detected: Win[true], MacOS[false], Linux[false]
OpenWebStartLauncher called with args [-verbose, http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp, -Xnosplash-].
Starting OpenWebStart 1.1.1
OWS main args [-verbose, http://10.42.39.207:8080/test-open-webstart/test_prod.jnlp, -Xnosplash-].

**Comment by hendrikebbers** [comment]
Hi,
the code hides the splash screen from IcedTeaWeb. This is already happen in OpenWebStart (otherwise you would have 2 splash screens). The splash screen of OpenWebStart can not be removed at the moment.
