### ISSUE TITLE
JVM Manager doesn't use the parameters in deployment.properties at first start

### ISSUE THREAD

**Issue by deamn** [karakun/OpenWebStart#179]
I have prepared a internal web server for the JVM Manager update processes.
On Windows 10 (I doesn't tested other OSes), on first start only (when the C:\Users\xxx\.config doesn't exist) the JVM Manager doesn't use the parameters in deployment.properties to download a JVM but the default value (hardcoded?)

[deployment.properties.txt](https://github.com/karakun/OpenWebStart/files/4128945/deployment.properties.txt)

**Comment by sclassen** [comment]
Which version do you use?
We fixed such a bug with 1.1.3 or 1.1.4

**Comment by deamn** [comment]
Sorry I forget the version! It's the 1.1.1. I quickly tested the 1.1.4 today and it's seems that it's the same behaviour but I will test tomorrow more in details

**Comment by deamn** [comment]
Ok the bug was fixed in 1.1.4, thanks
