### ISSUE TITLE
Run unsigned application

### ISSUE THREAD

**Issue by glauber-experian** [karakun/OpenWebStart#181]
I need to run a very old application, which is not signed (Java 6 era).

Is there a way to configure an exception so it can run?

`net.sourceforge.jnlp.LaunchException: Fatal: Application Error: Cannot grant permissions to unsigned jars. Application requested security permissions, but jars are not signed`

Thank you,

glauber

**Comment by sclassen** [comment]
Signature check cannot be disabled. This is a core feature.
You can try to run with the `-nosecurity` maybe you need to remove the `<security>` from your JNLP.
