### ISSUE TITLE
JVM-Update strategy no honored

### ISSUE THREAD

**Issue by AlBundy33** [karakun/OpenWebStart#183]
I've set the jvm update strategy to use only the local jvms (and also tried to ask before download).

But OWS autoamtically downloads a version if the jnlp-file conains more than one java-setting.

In my example I have following entries:
```
    <j2se version="9+" java-vm-args=" --add-modules=ALL-SYSTEM" initial-heap-size="40m" max-heap-size="512m" />
    <j2se version="1.8+" java-vm-args="" initial-heap-size="40m" max-heap-size="512m" />
```

So we need at least Java 8 which is added to my JVMs.
But OWS starts to download a new openJDK becuase version 9+ was found in the jnlp-file.

Workaround: Change JVM-Update-URL to a not existing URL.

**Comment by AlBundy33** [comment]
In #185 there was a hint: "The JNLP tells OWS that 9+ is prefered over 1.8+"
If I remember correctly we hat to use this order to ensure that Oracle Java uses the correct arguments for the use jvm.
Ordering vom lowest to highest version did not work as expected for Oracle-JVMs.

In my opinion OWS should maybe check what is the highest local available version and check if there is a matching j2se-entry.

**Comment by sclassen** [comment]
We talked this issue over and decided to leave the strategy as it is today.
The order of the j2se/java tags in the JNLP takes precedence and OWS will try everything to start the application with the top most j2se/java tag it can find

**Comment by AlBundy33** [comment]
@sclassen but in my opinion this is wrong.
Our jnlp has currently thee j2se-tags
```
    <j2se version="9+" java-vm-args=" --add-modules=ALL-SYSTEM" initial-heap-size="40m" max-heap-size="512m" />
    <j2se version="1.8+" java-vm-args="" initial-heap-size="40m" max-heap-size="512m" />
    <j2se version="1.7+" java-vm-args=" -XX:MaxPermSize=256m" initial-heap-size="40m" max-heap-size="512m" />
```
becuase each of this version need different arguments.
since 1.8 MaxPermSize was removed and since java 9 we have to add the modules.

Our software runs with all of this versions (because there are some old java-installations out there) and if and admin decides to use a specific version (mostly java 8) ows always tries to download java 9 even if there is a company policy to use a specific java version from a specific vendor.

So at least an option to completly disable the automatic download would be nice.
