### ISSUE TITLE
Option to delete jnlp after start would be nice

### ISSUE THREAD

**Issue by AlBundy33** [karakun/OpenWebStart#184]
Latest Oracle-Javas automatically delete the launched jnlp-file so it would be nice if OWS would support this to.

**Comment by janakmulani** [comment]
@AlBundy33  This has been answered in the Support Forum https://board.karakun.com/viewtopic.php?f=21&t=61 .

**Comment by AlBundy33** [comment]
@janakmulani the linked thread seems to be another question.
