### ISSUE TITLE
OWS tries to start highest Version even if a lower supported version exists.

### ISSUE THREAD

**Issue by AlBundy33** [karakun/OpenWebStart#185]
see #183
Our jnlp contains different jvm-arguments like this:
```
    <j2se version="9+" java-vm-args=" --add-modules=ALL-SYSTEM" initial-heap-size="40m" max-heap-size="512m" />
    <j2se version="1.8+" java-vm-args="" initial-heap-size="40m" max-heap-size="512m" />
```
So we are able to start with Java 8 and later Versions.

In my local JVMs I have already a Java 8 JVM but OWS tries to download a current Java 11 Version.

Expected behavior is to use the best matching existing JVM.

**Comment by sclassen** [comment]
The JNLP tells OWS that `9+` is prefered over `1.8+`
So this is why it is trying to download 11.

We will be adding an option to completely disable downloading of JVMs.

**Comment by AlBundy33** [comment]
@sclassen "The JNLP tells OWS that 9+ is prefered over 1.8+"
If I remember correctly we hat to use this order to ensure that Oracle Java uses the correct arguments for the use jvm.
Ordering vom lowest to highest version did not work as expected for Oracle-JVMs.

In my opinion OWS should maybe check what is the highest local available version and check if there is a matching j2se-entry.
