### ISSUE TITLE
OpenWebstart as URL-handler

### ISSUE THREAD

**Issue by vnashkev** [karakun/OpenWebStart#188]
Oracle webstart registered itself as a URL-handler for JNLP & JNLPS schemas.

So an attempt to open any jnlp://... or jnlps://... url results in start of webstart application.

Are there any plans regarding this feature?

Thank you in advance,
Vitali

**Comment by netopyr** [comment]
OpenWebStart registers itself for the JNLP-MIME-Type in the OS. How a browser handles this information is specific to the OS and browser. There are currently no plans to change the existing functionality.
