### ISSUE TITLE
ows for mac os does not start with jnlp url

### ISSUE THREAD

**Issue by vnashkev** [karakun/OpenWebStart#194]
mac os Catalina.
ows does not start if url to jnlp is supplied.

open -a "OpenWebstart javaws" http://host/path/app.jnlp 

ows for windows resolves the url and starts an application.

**Comment by vnashkev** [comment]
Seems to be fixed in 1.1.8

**Comment by sclassen** [comment]
yes, this was fixed in 1.1.8
