### ISSUE TITLE
OpenWebStart does not support custom jnlp urls via protocol handler

### ISSUE THREAD

**Issue by macgibbon** [karakun/OpenWebStart#199]
The most recent version of Oracle Java with Webstart, Java 10, supported custom URI schemes via a protocol handler  as described here:

[https://docs.oracle.com/javase/10/deploy/overview.htm](https://docs.oracle.com/javase/10/deploy/overview.htm)

The advantage of this approach was that it worked very cleanly with the Chrome browser in that the protocol handler using jnlp:// URI scheme launched the webstart app immediately while the http:// url using a file association of the .jnlp extension downloaded the file, renumbered it, then asked if the user wished to open it. On a frequently used app, the download directory clutters up with hundreds of copies of the jnlp file.

**Comment by rafik777** [comment]
Is there a chance to add this feature in the near future?
This is very needed thing.

**Comment by vnashkev** [comment]
I also vote for this. Absolutely needed!
I would like to participate.

**Comment by sclassen** [comment]
thanks for your offer vnashkev
Unfortunately registering the types is part of the installer which is built using a special install4j license. This part of the code is currently not public as it contains license keys and other secrets for signing

**Comment by rafik777** [comment]
@sclassen I see the same issue is closed in IcedTea-Web 
https://github.com/AdoptOpenJDK/IcedTea-Web/issues/473
and in the `installer.json.in` file there are coresponding parts:
https://github.com/AdoptOpenJDK/IcedTea-Web/blob/master/launchers/win-installer/installer.json.in#L40

I don't know if this file is used by install4j.
If not I found that install4j supports this mechanism "natively":
https://www.ej-technologies.com/products/install4j/whatsnew8.html

> Cross-platform support for URL handlers has been added. The "Register a URL handler" action works on Windows, macOS and Linux and can associate custom URL schemes with a launcher.
> 
> For example, a custom scheme hello will match URLs like hello://world. The entire URL will be passed to the main method or can be obtained via the StartupNotification API in the launcher on macOS or if the launcher is in single instance mode.

**Comment by sclassen** [comment]
fixed in version 1.1.8
