### ISSUE TITLE
Where is the source code? 

### ISSUE THREAD

**Issue by ChristianCiach** [karakun/OpenWebStart#2]
You are releasing alpha builds as binaries and the project is GPL, but this repo only contains a readme. So, where is the source?

**Comment by sclassen** [comment]
OpenWebStart is based on IcedTea-Web (https://github.com/AdoptOpenJDK/IcedTea-Web)
Almost all our contribution and code can be fount in the ITW project. We currently added only one class and a new installer.

The repo unfortunatly contains keys and licences from an internal build tool. We will clean this up and release the code (maybe some of the installer config as well) in the next weeks.

**Comment by AndreasEhret** [comment]
Source code is now provided with the latest release 0.3.0.
