### ISSUE TITLE
OpenWebstart 1.1.1 on Windows 10 load file that is not defined in jnlp file into cache.

### ISSUE THREAD

**Issue by alslw** [karakun/OpenWebStart#200]
Hi
    I try to install java app. from jnlp file by OpenWebstart 1.1.1 on Windows 10, it can launch this java app but it loaded some file that is not defined in jnlp file into cache of OpenWebstart. Is this expected the result ?
<img width="746" alt="loadunexpectedfile" src="https://user-images.githubusercontent.com/12932352/74627579-ea340780-5185-11ea-9dc4-8e92aeda2c58.png">

**Comment by sclassen** [comment]
can you use a zip program to look into the content of the 2 jars.
There should be a folder `meta-inf` in there you will find MANIFEST.MF and LIST.INDEX (optional)

Theses files may define additional resources. Check if you find an entry for the `tstuder-cust.jar` in one of the files.

**Comment by alslw** [comment]
Yes, There are tstuder-cust.jar and rta2.jar in LIST.INDEX of rta2-signed.jar that was define in jnlp file  but why rta2.jar was not downloaded into cache the same as tstuder-cust.jar.
<img width="293" alt="INDEX LIST" src="https://user-images.githubusercontent.com/12932352/74701307-eca36980-5238-11ea-9521-d67799016ae3.png">

**Comment by sclassen** [comment]
Because the LIST.INDEX is used as a lookup file.
So if the classloader tries to load a class it uses this file as to find out in which jar to search first.
e.g: if you want to load a class in the package `tstuder.java.lib.component` then it will find this entry in the index file and the corresponding jar is `tstuder-cust.jar`

**Comment by AndreasEhret** [comment]
You can also try with 3.0.0-alpha1.
