### ISSUE TITLE
Win32 Java11

### ISSUE THREAD

**Issue by DaveDevelop** [karakun/OpenWebStart#202]
I have Win32 users, my jnlp has Java8+ and Java11+
The Java 8 is only there to allow existing users with Java 8 (Oracle) installed to continue to use the software, but my goal is to eventually move everyone to Java11
But when I have them install OpenWebStart it downloads Java8 (Zulu) , and my client dies because it does not include JavaFX
#151 

I see that Adopt/Zulu have Win32 Java11 versions available
Is it possible to add one of these to the JVMs list?

https://download-openwebstart.com/jvms

https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.6%2B10/OpenJDK11U-jdk_x86-32_windows_hotspot_11.0.6_10.zip

https://cdn.azul.com/zulu/bin/zulu11.37.17-ca-jdk11.0.6-win_i686.zip

**Comment by sclassen** [comment]
I think this may be the same issue as: #185 #183

**Comment by DaveDevelop** [comment]
I think for me the issue is that when OWS check your JVMs list, the only Win32 option is Java8.

- https://download-openwebstart.com/jvms

For Win64 it finds the Java11 Option and downloads it.

**Comment by janakmulani** [comment]
We will discuss about adding more JVMs to our JVM server. Until we provide the required JVM for download, you have the option to install it locally and make it available to OWS using the settings tool > JVM Manager.

**Comment by janakmulani** [comment]
32 bit Zulu JVM now provided.

**Comment by DaveDevelop** [comment]
Thank you
