### ISSUE TITLE
Command-line for running JNLP with remote debugging

### ISSUE THREAD

**Issue by SonicSunset** [karakun/OpenWebStart#206]
In order to analyze another issue (#201 ) I'd like to start a JNLP locally with remote debugging enabled.

I have enabled it with itw-settings where it states that the application will be started with remote-debugging settings `suspend=n`. 

However, in the OWS-Webstart Logs it is stated that remote-debugging is started with `suspend=y`. When connecting via a remote debugger (Eclipse) the application continues to load, which is the `suspend=y` behaviour

**Comment by sclassen** [comment]
We need your jnlp file, the deployment.properties and a screenshot of your jvm manager from the settings to help you best

**Comment by SonicSunset** [comment]
I have edited my request in the meantime since I don't need to start via command line anymore.
I was confused because of the suspend=y setting when enabeling remote debugging and thought the application wouldn't start because I oversaw the "do you want to download this webstart application"-window

I'll close this ticket now
