### ISSUE TITLE
Dynamic URLs in jvms-file

### ISSUE THREAD

**Issue by grammets** [karakun/OpenWebStart#207]
Hi,

is it possible to define the `href`-URL in the **jvms** configuration file dynamically, e.g. by a relative path or by using a variable?

Use case:
My application needs a specific jre. The **jvms**-file and the zipped jre are deployed to different servers. The structure is something like: 
```
http://<myserver>/
├── jvms.json
└── java/jre.zip
```
Unfortunately I’m not able to deploy individual **jvms** files for each server.  

Instead of referencing the absolute path
`"href“:“http://<myserver>/java/jre.zip“`
I would like to do something like
`"href“:“./java/jre.zip“`
or alternatively work with some variable.

Thanks!

**Comment by sclassen** [comment]
Currently there are only absolute URLs supported

**Comment by sclassen** [comment]
Feel free to open a pull request.
Good place to start looking is `RemoteJavaRuntime` and `JavaRuntimeSelector#installRemoteRuntime`

**Comment by grammets** [comment]
Thank you for your quick response. I will take a look at the code.

**Comment by janakmulani** [comment]
@grammets Did you get a chance to look at it? Otherwise we plan to close this issue.

**Comment by grammets** [comment]
@janakmulani sorry I didn't have the time yet. I would close the issue then.
