### ISSUE TITLE
 Draining page file on WS 2008 R2

### ISSUE THREAD

**Issue by GregN92** [karakun/OpenWebStart#210]
We have a problem with draining page file on WS 2008 R2 - 14 core / 100GB RAM / 40 users .
Max. Load during rush hour - CPU and RAM - 50%
Before installation OpenWebStart our page file was set on 8GB.
After installation and trying to use OpenWebStart,  page file grow up to 52GB ( we manually raised the limit).
When page file is full , OWS does not start.
Question1: Why OpenWebStart use so much virtual memory when RAM is free ?
Question2: How to configure OpenWebStart to not use the paging file / or define max size page file to use ?

**Comment by sclassen** [comment]
Can you give us some more insight?
Does the application start?
Can you send us the JNLP file and the Log files?

**Comment by GregN92** [comment]
The application starts correctly if the page file is not exhausted.
Link  to JNLP and logs
https://grupawrobel-my.sharepoint.com/:f:/g/personal/grzegorz_nawracala_wrobel_mercedes-benz_pl/Ej7VGY2xb1ZEreCtktIw-BwBrX7BNJSPaY5znUjCfMaWUA?e=sahfwa

**Comment by GregN92** [comment]
Something new in this case?

**Comment by sclassen** [comment]
Logs show nothing. The application is running on Windows only.
@janakmulani can you try the app on your Windows box. The JNLP is attached to this message
[ewaToken.jnlp.txt](https://github.com/karakun/OpenWebStart/files/4291624/ewaToken.jnlp.txt)

**Comment by janakmulani** [comment]
On running the jnlp I am getting Auth error
![error](https://user-images.githubusercontent.com/655389/75963202-158b5600-5eeb-11ea-8aa7-00ae5788324b.PNG)

**Comment by GregN92** [comment]
You don`t need analize jnlp file.
When i start this app in classic Java Web Start Launcher , RAM usage is normal.
Problem occurs only with Open Web Start.

**Comment by GregN92** [comment]
In this case, the problem only applies to the application, not jnlp file.

**Comment by GregN92** [comment]
Something new in this case?

**Comment by sclassen** [comment]
Do you get an `OutOfMemoryException` with a small page file?

The difficulties is that without the application we cannot reproduce or analyze the problem

**Comment by GregN92** [comment]
No, server with small page file still load at 50 % of RAM

**Comment by sclassen** [comment]
Can you profile the application using "your kit" or any other java memory profiler?

**Comment by AndreasEhret** [comment]
Can you please test with 3.0.0-alpha1.

**Comment by GregN92** [comment]
I have done both tests 
3.0.0-alpha1 - application does not start.
1.1.7  - application still draining page file.


Sorry, I can't submit the application for testing because it is an daimler application - EVA, VIS, ASRA.
Authorization is through a company account.

**Comment by GregN92** [comment]
Strange, on  this same server,  classic Java Web Start Launcher works correct.
That's why I think that the problem is not in the daimler application.

**Comment by sclassen** [comment]
Sorry, but without more info we have a hard time to help here.
OWS does not cache many things and they are always limited (e.g. metadata to all jars, classes, etc.)
Thus it is more realistic that the application is the source of the memory leak. But without more data we are blindly guessing what the root cause is.

**Comment by AndreasEhret** [comment]
Consider to post more details to the OpenWebStart Support Forum (https://board.karakun.com/viewforum.php?f=4). Daimler has a private forum space there for exchanging company internal details.
