### ISSUE TITLE
a way to keep session in openwebstart - maybe via jnlp/xjnlp?

### ISSUE THREAD

**Issue by undergraver** [karakun/OpenWebStart#214]
Hi,

We are in the phase of testing openwebstart for our applet legacy code and we've encountered the following problem: when we login to our web-site we keep the session via some cookie. The problem is that the jars we want to use are need authentication to be downloaded.

Is there a way for openwebstart to keep the session needed to download the required jars?

**Comment by sclassen** [comment]
There exists currently no possibility to pass session data while downloading jars.
