### ISSUE TITLE
ECMAScript Engine not found

### ISSUE THREAD

**Issue by jmestizo** [karakun/OpenWebStart#217]
My project makes use of nashorn script engine but it is not found, only the rhino engine is found.  I am using the Corretto 8 JDK and see the nashorn jar available under jre/lib/ext.  I see a similar [issue](https://github.com/AdoptOpenJDK/IcedTea-Web/issues/588) in the ITW project.  Would a fix have to be applied here separately or would ITW have to fix?

**Comment by sclassen** [comment]
We are currently re-working how the class loading works.
We plan on releasing a preview release which may solve your problem in the near future.
Be advised that this release will not be production ready but can help to further narrow down the problem. Best is to watch this github project so you get notified about the preview release

**Comment by sclassen** [comment]
related to https://github.com/AdoptOpenJDK/IcedTea-Web/issues/588

**Comment by AndreasEhret** [comment]
Can you try the Pre-release 3.0.0-alpha1 for this: 
https://github.com/karakun/OpenWebStart/releases/tag/v3.0.0-alpha1 
It should be fixed there.

**Comment by jmestizo** [comment]
I was able to successfully load the Nashorn script engine with the 3.0.0-alpha1 version.  Looking forward to the production ready release.

Thank you!
