### ISSUE TITLE
Open JWS support with Open JAVA 11

### ISSUE THREAD

**Issue by yuvraj18yadav** [karakun/OpenWebStart#219]
Dear team , 

Can you please confirm whether Open JWS plugin is compatible with Open JDK 11 . 
If yes then which version of open JWS shall we use and in case it is not compatible in that case any plans for matching the compatibility with open jdk 11 in near future .

**Comment by AndreasEhret** [comment]
I'm not sure if I get your question right in terms of what you mean by "Open JWS plugin".
OpenWebStart is providing an easy to use JVM Manager that allows you to choose an Open JDK from your preferred vendor (Oracle, Azul, Adopt, ...). To make things easy, a default download server is provided by OpenWebStart that allows you to choose between a couple of Open JDKs version 11. Which one you prefer to run your JNLP application is up to you by activating the preferred one in the JVM Manager. If the default download server does not host your preferred JVM you can download your favorite and add it locally in the JVM Manager.

**Comment by yuvraj18yadav** [comment]
OpenWebStart is installed on user machine . If the machine on which OpenWebstart is being installed has open Java 11 installed on it , will openwebstart get installed properly or not ?

**Comment by sclassen** [comment]
OpenWebStart brings a bundled JVM.
This JVM is used to run OWS but not the jnlp application. The JVM Manager will manage the JVMs for the jnlp applications.

To answer your question. OWS does not depend on any JVM being installed on the client. It brings its own and can download JVMs for the jnlp application
