### ISSUE TITLE
How can we configure open JWS to download zulu community edition jdk which includes open jfx as well 

### ISSUE THREAD

**Issue by yuvraj18yadav** [karakun/OpenWebStart#221]
I have selected zulu community edition as vendor under JVM manager . Open JWS downloads zulu zulu8.44.0.11 version for MAC OS but this bundle doesnt contain open jfx with it . How can i configure the Open JWS to automatically download the zulu8.44.0.13 version which contains open jfx bundled with open jdk.

**Comment by sclassen** [comment]
We do not provide all versions of all jdk vendors on our download server. Especially there is currently no way to specify that javafx should be included.

We also do not plan to add such a feature as newer jvms are never bundled with javafx.
So the recomendation is to include jfx as a dependency of your application
