### ISSUE TITLE
A lot of ERROR in openwebstart console but not in the log

### ISSUE THREAD

**Issue by undergraver** [karakun/OpenWebStart#225]
We are trying to port some applets to OpenWebStart and in the log we get a lot of ERROR (with red). They don't come from our logging system and we're curious what are they all about since it might be needed to update our ancient applet code.

We are talking about hundreds of thousands of errors in the openwebstart console.

A bad thing about this is that the console is blocked (probably due to the number of messages) , then comes back again being responsive, and then blocks again and so on.

Can you offer some suggestions?

We can surely help you testing, just tell us what to do. See images below:

![image(1)](https://user-images.githubusercontent.com/4649413/78104172-50ec4800-73f7-11ea-8984-de6769055048.png)

![image(2)](https://user-images.githubusercontent.com/4649413/78104185-5a75b000-73f7-11ea-936f-c3eb464aa61a.png)

**Comment by sclassen** [comment]
Do the errors appear just by running the applets or do they appear when you click a button in the console?
Do you also see the errors in the log file?
Maybe you need to enable logging to file in the open webstart settings

**Comment by Mannclaudiu** [comment]
Hello !

There are three scenarios:
   - ERROR appears at short time after applet begins execution (This doesn't happen for any applet)
   - ERROR appears at some more time after applet begins execution (This doesn't happen for any applet) 
   - ERROR appears when I close the applet by clicking x button (I have this issue on every single applet). Clicking any other functionality buttons that I have embedded in my applets does not generate this ERROR (in many cases I don't even have time to click any button, ERROR is already there).

It seems that this ERROR message is generated in a loop. For example, in a single run, I can have 500.000 more or less ERROR messages.

These ERROR messages are not logged into any log. By running any applet, it generates 2 logs: itw-clienta and itw-javantx. None of them have ERROR in it. 

I checked the logs to be enabled, and they are.

![image](https://user-images.githubusercontent.com/22660140/78214147-28c71c80-74bd-11ea-94be-0e61b9590906.png)

Thank you

**Comment by sclassen** [comment]
OK. Can you enable in the console the headers (checkbox "show headers").
This should add the information where the error is coming from.

**Comment by Mannclaudiu** [comment]
Yes, sure.

Here we go
![image](https://user-images.githubusercontent.com/22660140/78219781-eb688c00-74c8-11ea-80e8-28c2af6260c4.png)

**Comment by sclassen** [comment]
We think this loop of errors is triggered because writing to the file somehow fails.
Can you disable logging to file and see if the errors still appear in the console

**Comment by Mannclaudiu** [comment]
It worked ! All error messages are gone now.

Thank you very much for help !

**Comment by sclassen** [comment]
ok, we will implement a permanent fix so you can enjoy both file an console logging

**Comment by undergraver** [comment]
Hi,

I just want to thank for the quick response. We have finally managed to run some applets that were only possible until now with the Web Start from Oracle Java.

So I can confirm that fixing this issue clearly helps, at least in our case. If you require additional tests that we can perform we will be glad to help you, just let us know.

I can also say that the memory consumption is again low. Before it used to go up to 4GB and stay there while our application weren't able to work, they actually were blocked.

We will keep you updated.

Thank you once again!

**Comment by AndreasEhret** [comment]
There will be a permanent fix for this in the upcoming 1.1.7 release.

**Comment by AndreasEhret** [comment]
1.1.7 is available now
