### ISSUE TITLE
OpenWebStart V1.1.6: Fails to read or display the server white list configured at response.varfile

### ISSUE THREAD

**Issue by jramakrishnan** [karakun/OpenWebStart#227]
1. Download the latest version of OpenWebStart V1.1.6 for Windows OS V10
2. Install and launch "OpenWebStart" configuration window (hence it will auto-create response.varfile as per the documentation at https://openwebstart.com/configuration/)
3. Open the response.varfile generated at .intelliJ folder with administrator privilege at Windows 10 OS 
4. Add the configuration to whitelist a locally hosted service URL i.e. deployment.security.whitelist=http://localhost:8080
5. Restart OpenWebStart Settings
6. Expect to see the saved configuration but no URLs shown

**Comment by sclassen** [comment]
localhost is treated specially and is always in the whitelist.
Try some other host/IP

**Comment by jramakrishnan** [comment]
Thanks for the update. Just tried with different configurations but its the same. The server whitelist is empty...

The content of "response.varfile"

# install4j response file for OpenWebStart 1.1.6
installationDate$Long=1585739812305
sys.adminRights$Boolean=true
sys.fileAssociation.extensions$StringArray="jnlp","jnlpx"
sys.fileAssociation.launchers$StringArray="313","313"
sys.installationDir=C\:\\Program Files\\OpenWebStart
sys.languageId=en
userMode$Integer=1
deployment.security.whitelist=http://197.34.34.45,https://www.google.co.uk

Screenshot of "OpenWebStart Settings"

![openwebstart-error](https://user-images.githubusercontent.com/7903524/78157872-73528580-7438-11ea-8f22-f2576b6a7346.png)

**Comment by sclassen** [comment]
Sorry, I was reading your initial post to quickly.
Modifying response.varfile is only helpful if you plan to do unattended installations on other computers.
If you simply want to change the settings for the current computer you can do this in the file `%USER_HOME%\.config\icedtea-web\deployment.properties`

You can add the line `deployment.security.whitelist=http://197.34.34.45,https://www.google.co.uk` there

**Comment by jramakrishnan** [comment]
Yes, it works. Thanks @sclassen 👍
