### ISSUE TITLE
Flag to restrict downloadable runtimes to those shipping OpenJFX

### ISSUE THREAD

**Issue by don-vip** [karakun/OpenWebStart#230]
As per https://github.com/AdoptOpenJDK/TSC/issues/27#issuecomment-607663428, AdoptOpenJDK refuses to ship OpenJFX.

So for our Java 8 => Java 11 migration, we are no longer interested by their binary distribution. We will rather focus on [Zulu](https://www.azul.com/downloads/zulu-community/) and [Liberica](https://bell-sw.com/pages/java-11.0.6/).

Is there a way to declare in our .jnlp file that we need a Java runtime providing OpenJFX, so that OpenWebStart would honor it by making sure to download a compatible runtime? If not, could it an OpenWebStart extension to the official JNLP standard?

**Comment by sclassen** [comment]
yes, there is a custom attribute `vendor` for the `java` tag.
But it needs to be enabled in the settings under JVM Manager -> Settings -> allow vendor from JNLP

If you always want the same vendor you can also set it in the JVM Manager Settings

**Comment by don-vip** [comment]
Can this attribute be repeated several times?

**Comment by sclassen** [comment]
no you can only specify a single vendor

**Comment by AndreasEhret** [comment]
Future of JavaFX is JavaFX as a library.
