### ISSUE TITLE
Resize applet window

### ISSUE THREAD

**Issue by Mannclaudiu** [karakun/OpenWebStart#239]
Hello,

We wonder if in the next releases, will be possible to resize the main applet window. Currently our applets can't be resized because the resize option seems to be disabled.

![image](https://user-images.githubusercontent.com/22660140/78531219-b07a9700-77ed-11ea-97a8-3e8db30303fd.png)

**Comment by sclassen** [comment]
applets are not officially supported in OWS.
They work most of the time, because we build upon icedtea-web but non of our paying customer is using applets.
We recommend to migrate the applet to an application.

**Comment by mvw** [comment]
Just to let you know that our applets do not work anymore since 1.1.7.
(Yes I it was unofficial, that is why commen there and not in a new issue)

I just tried our branch, where the ports to JFrame are tested, and this test succeeded.

**Comment by Mannclaudiu** [comment]
Hello,

We began the process of converting our applets to applications, so we are getting rid of them soon.

Thanks for the information !
