### ISSUE TITLE
Display startup logo for longer time.

### ISSUE THREAD

**Issue by reinpeter** [karakun/OpenWebStart#240]
Currently the startup logo disappears after very short period.
If downloading/verifying the application takes long, then a progress bar/info is shown in lower right corner. This is however quite small and disappears now and then.
For a larger application, this leads some users to believe that nothing happend and is confusing. Worse, it is causing them to click shortcut again and again, even slowing down evth more.
Request: (option to) show the logo until application is actually started.
Note, it seems (not verified by me) that ITW shows a logo until started

**Comment by janakmulani** [comment]
@reinpeter  Please try with OWS 1.2.0 to be released next week. It has the fix for this issue.

**Comment by Jamila891** [comment]
new version 1.2.0 has been released and will fix this issue.
