### ISSUE TITLE
Allow custom logo during startup

### ISSUE THREAD

**Issue by reinpeter** [karakun/OpenWebStart#241]
Would be nice to have a custom logo or icon during startup, Even combined with OWS logo would be fine. Just to give user a clue that it started the right application.

**Comment by sclassen** [comment]
There are no plans to offer custom logos at startup.
We offer customized splash screens for premium support customers.
But the splash screen is still a static image and does not contain any info about the application which is started.

please contact us on openwebstart@karakun.com if you are interested in premium support
