### ISSUE TITLE
You can allow the usage of the server specified in the JNLP file by enabling the option “Allow server from JNLP file”

### ISSUE THREAD

**Issue by yuvraj18yadav** [karakun/OpenWebStart#247]
How to configure jnlp file to download open jdk build from custom server / custom url link . 
I dont want to use the azul/adopt open jdk built . I want to host my open jdk built on a server and provide that details in jnlp file such that my custom ope jdk is download my Open jws plugin .

**Comment by sclassen** [comment]
The `href` of the j2se/java tag must contain an URL pointing to a json which lists the available JVMs.
See https://github.com/karakun/OpenWebStart/blob/master/documentation/guide/OWSGuide.adoc#setup-a-custom-download-server
You can also take a look at the json of the default download location: https://download-openwebstart.com/jvms.json

**Comment by yuvraj18yadav** [comment]
Thanks a lot .

Regards
yuvraj Singh

**Comment by yuvraj18yadav** [comment]
Thanks man
