### ISSUE TITLE
remote debugging on random port needed when running multiple applications

### ISSUE THREAD

**Issue by undergraver** [karakun/OpenWebStart#248]
Currently, for remote debugging, the option offered by OWS is to specify a port as the message says:

"Applications will be started with '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005'.
**Only one application can be started in parallel while debugging is active!**"

Our solution for this was not to specify any port, so the command would look something like this:

"-agentlib:jdwp=transport=dt_socket,server=y,suspend=n" (that is without address parameter)

You don't have to worry about the port used as this can be easily found out with tools like process explorer under windows quite easily.

This allows developers to debug multiple applications at the same time without having the issue that once an application starts under a defined port others cannot be started in debug mode anymore.

Can you please include this option when, for example, leaving the field empty?

**Comment by undergraver** [comment]
Also, can you please also offer the option to configure suspend? We want to have the option suspend=y in order to debug the startup of the application.

**Comment by hendrikebbers** [comment]
Hi undergraver. I can understand your idea. Maybe you can do a PR for this new feature. I assume that we currently do not have time to work on it.

**Comment by undergraver** [comment]
Hi @hendrikebbers ,

Sure. Just let me know where that part of code is because I was thinking exactly the same. I have quite some experience with remote debugging in java under some weird conditions that I believe will help solve many of the debugging requests in the future, including ours.

**Comment by hendrikebbers** [comment]
Cool :)

The settings dialog can be found here: `com.openwebstart.debug.DebugPanel`
The app starter (that uses the settings) can be found here: `com.openwebstart.launcher.OwsJvmLauncher`

You can check where `com.openwebstart.config.OwsDefaultsProvider.REMOTE_DEBUG_PORT` is used to find the correct code blocks.

**Comment by undergraver** [comment]
Hi @hendrikebbers ,

I've completed the main work on the configuration. 
Two questions: how can I test this, currently? I only did the UI part - which works ok. But OpenWebStart from the system is still used. How can I make use of the openwebstart compiled by me?

**Comment by undergraver** [comment]
Hi,

I created pull request #252 for this. Please have a look and let me know if it needs some corrections.

Thanks,
Iulian

**Comment by sclassen** [comment]
Thank you for your contribution.
We will change the default for "suspended" to `true` in order to keep the current behavior.

**Comment by undergraver** [comment]
Thanks for the cleanup.
