### ISSUE TITLE
Alert when loading from remote locations won't accept responses

### ISSUE THREAD

**Issue by Pheil** [karakun/OpenWebStart#25]
![image](https://user-images.githubusercontent.com/1458226/64348813-d7f15300-cfc3-11e9-8661-6af508416bc5.png)

Clicking yes or no doesn't seem to do anything except scroll more code in the cmd window.  Also, minor issue, but the text is truncated.

**Comment by sclassen** [comment]
We know of a similar issue.
Tomorrow we will release 0.3.1 with a fix.
Could you please retest once the new version is out.
I will inform you here when the release is ready

**Comment by sclassen** [comment]
0.3.1 has been released

**Comment by Pheil** [comment]
This issue looks fixed.  I've got some other issue, but I'll enter a new issue for it.
