### ISSUE TITLE
Secure JVM-Download from JNLP-provided servers

### ISSUE THREAD

**Issue by abrensch** [karakun/OpenWebStart#253]
really appreciate your work on OpenWebStart. Was involved in rich client districbution and JavaWebStart fo 20 years now and nice to see that it's coming to a good end.

But of course there's a "but" :-)

We want a tight coupling between an application and the JDK, just to reduce any version- and proxy-hassle to the possible minimum.

So going with JNLP-provided download server and vendor is clearly the way to go.

But from a security perspective it's a no-go. Just to easy to inject malicous code via a JVM-download, just from clicking on a jnlp-link.

Even a server whitelist is not a solution. Server whitelist is not applied for jvm-download url's. In addition, server whitelists cannot handle domain-wildcards.

I can imagine 2 possible solutions:

- add a second server whitelist for JVm-Downloads

- or better: add an optional signature to the JRE-description in the jvms-json, so that the JVM-Manager can check that signature using a public key from it's configuration properties

I could try a pull-request for one or both if you think it's a good thing but do not have the time  for that. Let me know.

thanx, Arndt

**Comment by sclassen** [comment]
Thank you for the interest in the project.

We also take security serious. This is why we do the following:
- use https by default
- provide a fixed URL to a download server
- disable URLs from JNLP by default.

Most of our customers use OWS in a corporate settings and do not enable downloads from a JNLP.

Your point about JNLP-provided download is more than valid.
As a first step we will add a warning to the option so users are aware of the risk they take when enabling this option.

We also consider adding the proposed whitelist to allow limiting the possible download locations.
The PKS authentication is much harder to integrate both in OWS and in the environment of the application provider.

You can also reach us at openwebstart@karakun.com if you feel like discussing security issues in private

**Comment by Jamila891** [comment]
implemented with version 1.2.1. see documentation: https://github.com/karakun/OpenWebStart/blob/master/documentation/guide/OWSGuide.adoc#allowing-jvm-server-in-jnlp-and-defining-a-jvm-server-whitelist
