### ISSUE TITLE
JNLP application is not launched in first invoke

### ISSUE THREAD

**Issue by yuvraj18yadav** [karakun/OpenWebStart#259]
I am opening JNLP application using open java web start plugin in MAC OS. Sometimes the application does not open in first invoke. I have to open the application again and in second invoke the application opens successfully. Can you please help me in this regard. Do we need to tweak any configurations?

**Comment by sclassen** [comment]
Can you turn on logging to file and then try to reproduce the issue.
If you can reproduce please attach the log files (there are 2-3 per launch) and the JNLP to this issue.

Alternatively you can send them to openwebstart@karakun.com if you do not want to make them public. In that case please mention the issue number in the mail

**Comment by yuvraj18yadav** [comment]
attaching 2 logs files . The one in which application is not launching logs have captured the following exception : UIDefaults.getUI() failed: no ComponentUI class for: javax.swing.plaf.basic.BasicComboBoxEditor$BorderlessTextField[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,caretColor=,disabledTextColor=,editable=true,margin=,selectedTextColor=,selectionColor=,columns=0,columnWidth=0,command=,horizontalAlignment=CENTER]

Please find attached the both the files[

](url)
[2020May13_014958.LOG](https://github.com/karakun/OpenWebStart/files/4618283/2020May13_014958.LOG)
[2020May13_012749.LOG](https://github.com/karakun/OpenWebStart/files/4618284/2020May13_012749.LOG)

**Comment by sclassen** [comment]
those are logs from your application.
Do you also have logs from OpenWebStart
See https://board.karakun.com/viewtopic.php?f=10&t=17

**Comment by Gr33nbl00d** [comment]
could be related to
https://github.com/karakun/OpenWebStart/issues/201

**Comment by Jamila891** [comment]
closed due to inactivity
