### ISSUE TITLE
Intermittent classloading problem

### ISSUE THREAD

**Issue by johjar** [karakun/OpenWebStart#265]
Hi,

We're experiencing an intermittent problem in our application when JAXB (javax.xml.bind:jaxb-api:2.3.1) is loading a file on the classpath. Our application needs `JAXBContext`  to read an XML file and it is loaded by the JAXB API by looking for `META-INF/services/javax.xml.bind.JAXBContext` on the classspath and using the contents of that file (which is a fully qualified classname) to load the class. The file exists in `jaxb-runtime-2.3.1.jar` which is on the classpath.

Sometimes, but not always, this fails and the classloader can't find `META-INF/services/javax.xml.bind.JAXBContext` and we get an error in our application.  If it fails, it will always fail until the application is restarted.

It seems to us that when the classloding is successful, the `JNLPClassLoader` is used, but when it fails `jdk.internal.loader.ClassLoaders$AppClassLoader` is used.

We're using OpenWebStart 1.1.7 and Redhat Open JDK 11.0.6.10-2 (windows.redhat.x86_64). We also tried using OpenWebStart 3.0.0-alpha1 but then the error _always_ occurs - the `JNLPClassLoader` doesn't seem to be present there.

Any clues?

Best regards,

/John Harelius

**Comment by sclassen** [comment]
Yes with 3.0.0 we try to replace the existing class loader as it has some limitations regarding lazy downloading.

Coming back to your specific problem:
It all depends. Whenever a Java application is executed there are several classloaders involved. The most often used ones are `getClass().getClassLoader()` and `Thread.currentThread().getContextClassLoader()`. There is also the SystemClassLoader and the BootstrapClassLoader.

You need to find out which classloader JAXB is using. This may depend on one or more of the following:
- The method of JAXB are you are calling
- The class you are calling JAXB from
- The thread you are calling JAXB from

Have a look at the following Stackoverflow: https://stackoverflow.com/a/36228195

**Comment by johjar** [comment]
Thanks for the reply.

JAXB is using `Thread.currentThread().getContextClassLoader()` in this situation. This is the sourcecode: https://github.com/javaee/jaxb-spec/blob/2.3.1/jaxb-api/src/main/java/javax/xml/bind/ContextFinder.java#L561. Most of the time this returns the `JNLPClassLoader` in my application, but sometimes the `jdk.internal.loader.ClassLoaders$AppClassLoader` is returned and I get an error. I do exactly the same thing in my application in both situations.

BTW: I coped the JAXB code and created a small application that executes classloadning and then exits. I ran it using OpenWebStart, both 1.1.7 and 3.0.0 but I haven't been able to reproduce the error in that application yet. 

Best regards,

/John Harelius

**Comment by sclassen** [comment]
Yes. I guess in your main application you also make use of background threads for doing the work.
It is in one of these background threads where the wrong context class loader is present.

Maybe you can do a `Thread.currentThread().setContextClassLoader(this.getClass().getClassLoader())` before you call the JAXB code

**Comment by johjar** [comment]
Yes! Now it works!

I added your code setting the classloader right before my call to JAXB. I verified by checking the classloader right before "your code". The check returned the wrong classloader, but running the call to JAXB after "your code" it works!

Thanks for the quick support, and have a nice weekend!

/John Harelius
