### ISSUE TITLE
Allow setting the path to the JVM automatically

### ISSUE THREAD

**Issue by berbiche** [karakun/OpenWebStart#272]
###### Problem

I am currently trying to package this application for the [NixOS](/NixOS/nixpkgs) Linux distribution.

NixOS is unique in that there is no `/bin`, `/sbin`, `/usr` or `/etc`.
Instead, packages are built and added within  a global store under `/nix/store/${computed_package_hash}-${package_name}-${package_version}`.
When a user boots NixOS, a profile describing the state of all installed packages is activated and binaries are resolved by the Nix daemon.
Everything within the store is  readonly.

Because of this design, it is impossible to use the prepackaged JVM from the remote distributions because dynamic libraries are not under `/usr/lib`. Binaries are traditionally `patchelf`ed to fix their RPATH and change the interpreter.

Manually adding a JVM using a path in the settings is not an option either because the *real path* of the package can change between updates to the package.

###### Changes requested

I have read #126 and disagree with the choice of the manual workflow.

As such, I am asking for one of the options below:
1. Allow hardcoding the JVM path within the `response.varfile`
2. Respect the JAVA_HOME variable and use it to open JNLP files
3. Default the JVM to use to the one in use by the program itself when no JVM is configured in the settings (or none can be found) and `ows.jvm.manager.updateStrategy` is set to `NO_REMOTE`.

###### Additional notes

My efforts toward packing this application live [here](/berbiche/nixpkgs/blob/openwebstart/pkgs/applications/misc/openwebstart/default.nix). I am wrapping the debian package because the 1.1.7 release cannot be built with Maven (missing dependency on icedtea-web-all-something).

On a different note, I would like to thank all the contributors for this application. My university is still using JNLP for their course registration and OpenWebStart has allowed me to use their crappy JNLP without hassle (its a meme within my university).

**Comment by hendrikebbers** [comment]
Hi @berbiche and THX for working on such integration. I can understand your use case. Since we do not want to change any default behaviour of OWS I assume that only 1) (config in `response.varfile`) would be a possible solution. We could support 2) (usage of `JAVA_HOME`)  with an additional parameter on the `response.varfile`. 

The biggest problem is that we currently do not have the time to work on such issue. But maybe we can find some time in future to work on it.

At which university do you study? Is OWS used there by many students for the tool?

**Comment by sclassen** [comment]
Also if your main concern is the way OWS is choosing the JVM to execute the applications you may want to look at icedtea-web (https://github.com/AdoptOpenJDK/icedtea-web).
OWS uses ITW in its core and only adds some extra features (like JVM management) on top.
Maybe it is easier to crate a NixOS package from ITW.

Also if you want to compile OWS yourself you need to compile ITW first.
Build steps are thus:
1. Checkout ITW and run `mvn clean install`
2. Checkout OWS and run `mvn clean install`

**Comment by berbiche** [comment]
Hi, thanks for the quick response.

> At which university do you study? Is OWS used there by many students for the tool?

I am enrolled at [École des Technologies Supérieures in Montreal](https://www.etsmtl.ca/en).
The school does not officially endorse, recommend or mention this software. I found it as a cross-platform alternative to using a Docker container wrapping icedtea-web and using a bind mount on the X11 server (a big hack in other words).

My school recommends installing Oracle JRE 8, which now requires an account. The closest alternative, OpenJDK, does not ship with Java Web Start to my knowledge.

> OWS uses ITW in its core and only adds some extra features (like JVM management) on top.

That's good to know. I won't need OWS for my use on NixOS (still very useful on Windows) as icedtea-web is already packaged.

> The biggest problem is that we currently do not have the time to work on such issue. But maybe we can find some time in future to work on it

Using icedtea-web fixes my use case, as such I don't know whether I should close this issue, I'll leave it to your discretion.

**Comment by sclassen** [comment]
@hendrikebbers I vote for closing
