### ISSUE TITLE
Locked properties documentation issue

### ISSUE THREAD

**Issue by jlindwall** [karakun/OpenWebStart#273]
The documentation found in the following urls suggests that locking property PROPNAME is accomplished  by defining a property PROPNAME.locked=true

- https://openwebstart.com/configuration/
- https://github.com/karakun/OpenWebStart/blob/master/documentation/guide/OWSGuide.adoc

This is technically correct but the implementation is a bit surprising, in that I assumed that the PROPNAME.locked property was a boolean-valued property when in fact it is not.  The following constructs are equivalent and all serve to lock the PROPNAME property:

- PROPNAME.locked=true
- PROPNAME.locked
- PROPNAME.locked=GiBBerish
- PROPNAME.locked=false

That last example was the most surprising as I was assuming I could use false to indicate "no lock" but that does not work.

I suggest either adjusting the documentation to clearly specify the behavior or adjust the implementation to be a true boolean property.

**Comment by sclassen** [comment]
This is a legacy issue from IcedTea-Web. It only looks at the key and not the value.
For backwards compatibility we decided not to change the behavior.

**Comment by sclassen** [comment]
We will update the documentation to reflect this
