### ISSUE TITLE
Function with low priority

### ISSUE THREAD

**Issue by TonyTsang1992** [karakun/OpenWebStart#276]
Hi, 

I want to ask if these two functions are available in OpenWebStart?

SEC-4 | Trusted Environment(j2ee-application-client) | 2 | OpenWebStart allows to start an application in an j2ee-application-client environment.JSR-56, Ch. 5.6JSR-56, Ch. 5.3
-- | -- | -- | --
SEC-5 | Deployment Rule Set (Certificates) | 2 | Provide deployment rule set as white list for SHA256 hashes/certificates.

**Comment by sclassen** [comment]
They are marked as low prio and are not available in the current version.
If we find sponsors for the low prio features we will implement them faster.
