### ISSUE TITLE
Start a Java Application offline

### ISSUE THREAD

**Issue by boesi** [karakun/OpenWebStart#277]
I have a Java application that I need to start in online and offline mode: online for getting updates and the actual use case is offline. 

With Java Webstart and the JRE 8 from Oracle this works online and offline. But with OpenWebStart it only works online. In offline mode I get this error: 

    net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file at '<url of jnlp file>'. You can try to download this file manually and send it as bug report to IcedTea-Web team.

Well, downloading a file when you are offline could be somewhat difficult.

The target of the shortcut created on the desktop, shows `<path to javaws.exe> "<url of jnlp file>"`. No hint to the cache, so I guess this can't work offline. What am I doing wrong? Or is it not possible to start a java application in offline mode with OpenWebStart?

My system: 

- Windows 10 1909
- OpenWebStart 1.1.8 32bit
- JRE 1.8.0_242 Azul Systems, Inc.

The JNLP file:

    <jnlp spec="7.0+" codebase="..." href="...">
      <information>
        <title>...</title>
        <vendor>...</vendor>
        <icon kind="shortcut" href="icon/logobeta32.png"/>
        <icon kind="default" href="icon/logobeta64.png"/>
        <homepage href="..."/>
        <description>...</description>
        <description kind="short">...</description>
        <offline-allowed/>
        <shortcut online="true" install="true">
          <desktop/>
          <menu submenu="..."/>
        </shortcut>
      </information>
      <security>
        <all-permissions/>
      </security>
      <resources>
        <j2se version="1.8*" java-vm-args="-Xmx256m"/>
        <jar href="..." main="true" download="eager"/>
        <jar href="..." main="false" download="eager"/>
        [many jar files]
      </resources>
      <application-desc main-class="..."/>
      <update check="timeout" policy="always"/>
    </jnlp>

I experimented with the attributes online, install and check for shortcut and update, but with no effect.

Thanks for your help.

**Comment by sclassen** [comment]
yes, you need to explicitly start OWS in offline mode by passing `-Xoffline` in the shortcur

**Comment by boesi** [comment]
Is this option somewhere documented? 

It works most of the time (I can't see a pattern, when it does or does not), if I start the application from commandline:

    javaws.exe -Xoffline [url of jnlp file]

But when I use this command in a shortcut from the desktop, the application doesn't start offline and the argument `-Xoffline` is removed from the shortcut.

If the application doesn't start with `-Xoffline` it always stops at this line:

    Cached desktop shortcut icon: ...\.config\icedtea-web\icons\logobeta32.ico ,  With source from: ...\.cache\icedtea-web\cache\0\46\logobeta32.png

So how is this supposed to work?

**Comment by sclassen** [comment]
@janakmulani please have a look

**Comment by janakmulani** [comment]
Hi,

I tried your scenario. Create short cut for command javaws -Xoffline xyz.jnlp. It works for me. I have attached the screenshot of the short cut's properties:
![OWSOfflineShortCut](https://user-images.githubusercontent.com/655389/85140905-98021080-b263-11ea-99d6-ce7bc0ccfa7e.PNG)
