### ISSUE TITLE
"Cookies must be enabled" with Cisco ASDM (Adaptive Security Device Manager)

### ISSUE THREAD

**Issue by NeilHanlon** [karakun/OpenWebStart#278]
I don't have any real logs to show, as I can't get it to print any, but the application seems to be launching fine with AdoptOpenJDK 1.8.0_212 -- all jars are downloaded, it starts up as it does with Oracle JDK -- but when I enter the login credentials, the app spits out a message saying that 'Cookies must be enabled' and doesn't let me get any further.

I enabled debug logging, but nothing is printed anywhere except a default message about OWS not using a proxy.

Is there some config I need to add to support cookies while _inside_ an application?

Oddly I've tried a few different firewalls and only one of them is not giving me this issue (of the four I've tested). Could it perhaps be something to do with certs, maybe? (I know, hard to say with absolutely no logging..)

Probably a different issue, but supplying -noupdate to OWS's javaws has no effect... as it constantly prompts me to install Azul JDK 11.06

**Comment by sclassen** [comment]
If you get to the login screen of your application then OWS is mostly done.
The current version (1.1.8) downloads all resources before launching the main method of the application.
So if you see any screen of your app it means you are in the application code.
Only class loading and the JNLP services are still active.

So sorry but you need to contact the devs of the application about this cookie issue.
Maybe you can try different JVMs as they sometimes behave a little different and could be the cause of this issue.

The -noupdate command line argument only affects the updating of the application resources not the JVM. If you want to disable the JVM update you can do this in the settings under "JVM Manager"
On the bottom right you find a button "settings" and in the new popup there is a dropdown for the update strategy. Select "never download" to prevent OWS from ever trying to download a JVM.

**Comment by sclassen** [comment]
Could you give the logging another try:
https://github.com/karakun/OpenWebStart/blob/master/documentation/faq/FAQ.adoc#debugging-and-error-reporting

**Comment by NeilHanlon** [comment]
Hi -- Sorry this took me a bit to respond to. I had some things going on yesterday.

I agree that it feels much like an application-layer and/or JDK vesion thing, so I did some tests.

With AdoptOpenJDK 1.8.0_212 -- I get the cookie message.
With Oracle JDK 1.8.0_231 -- I get the cookie message

If I launch javaws directly from Oracle JDK 1.8.0_231 -- I don't get this message.

This is leading me to believe perhaps that I have some sort of property set in my java config that is not being loaded by OpenWebStart. Any ideas where to look?

**Comment by janakmulani** [comment]
@NeilHanlon  Any update on this?

**Comment by Jamila891** [comment]
closed due to inactivity
