### ISSUE TITLE
-Xnosplash is ignored

### ISSUE THREAD

**Issue by jastax** [karakun/OpenWebStart#283]
We'd like to supress the OWS splash screen. 

It seems that -Xnosplash does not work yet. Is there another way or is it possible to implement that flag?

**Comment by sclassen** [comment]
The splash can currently not be disabled in OWS.
Also we have no plans to support such a feature in the near future.

**Comment by dbottonadn** [comment]
Hi, Any news about the possibility to disable splash screen, 4 years later ?
thank you
best regards
