### ISSUE TITLE
Stoped at: Cached desktop shortcut icon...  With source from...

### ISSUE THREAD

**Issue by ywuliu** [karakun/OpenWebStart#284]
Platform: Windows 10

Condition:  if the shortcut were installed before and deleted it before install new short cut, deployment.javaws.shortcut=ALWAYS in deployment.properties
 Problem: 
Program Stopped at: Cached desktop shortcut icon...  With source from... line, menu icon created, desktop icon is not created

**Comment by janakmulani** [comment]
Thanks for reporting this issue. We will fix it in a future release.

**Comment by janakmulani** [comment]
@ywuliu Would it be possible to share your jnlp file?

**Comment by janakmulani** [comment]
I tested with OWS 1.1.8. Reported usecase CANNOT be reproduced.
Steps:
1. Setting to Always and run jnlp => Short cuts created
2. Delete Shortcuts
3. Run jnlp => Shortcuts created.
