### ISSUE TITLE
Not able to run jnlp file using Java 11

### ISSUE THREAD

**Issue by hendrikebbers** [karakun/OpenWebStart#287]
Created this issue based on https://github.com/AdoptOpenJDK/IcedTea-Web/issues/667
It looks like the issue is related to OpenWebStart and not to IcedTeaWeb since it is a Java 11 specific issue.

@neelambatra can you please attach screenshots from the "Logging" section of the OpenWebStart settings.

**Comment by neelambatra** [comment]
Thanks. Find attached the screenshot of logging section, let me know if any other details are required.
<img width="936" alt="Screenshot 2020-07-06 at 12 27 27 PM" src="https://user-images.githubusercontent.com/67742811/86564657-34c2ee80-bf84-11ea-8085-61116bb7a838.png">

**Comment by hendrikebbers** [comment]
Hi, I just wanted to doublecheck that the config is correct. Based on the configuration you should have multiple log files under` C:\Users\administrator\.confic\icedtea-web\log`. As far as I understood your previous comments that is not the case, right?

**Comment by neelambatra** [comment]
Attaching the screenshot and the log files which I have.
<img width="801" alt="Screenshot 2020-07-06 at 12 34 19 PM" src="https://user-images.githubusercontent.com/67742811/86565292-3214c900-bf85-11ea-94b8-96cb3f678722.png">
[itw-javantx-2020-07-03_23_52_44.765.log](https://github.com/karakun/OpenWebStart/files/4877271/itw-javantx-2020-07-03_23_52_44.765.log)
[itw-javantx-2020-07-05_23_56_08.964.log](https://github.com/karakun/OpenWebStart/files/4877272/itw-javantx-2020-07-05_23_56_08.964.log)

**Comment by hendrikebbers** [comment]
The behaviour is really strange...

In the first log I can see the following line (120):
`[MESSAGE_ALL][Fri Jul 03 23:52:46 PDT 2020] About to launch external with commands: '[C:\Users\Administrator\.cache\icedtea-web\jvm-cache\azul_11.0.7\bin\java.exe, "-Xbootclasspath/a:C:\Program Files\OpenWebStart\openwebstart.jar", -Xms128m, -Xmx512m, -Xincgc, -Djnlp.feature.cutThroughComment.required=false, -Djnlp.zebedee.keySize=256, -Djnlp.zebedee.compression=zlib:9, -Djnlp.java.naming.factory.initial=org.apache.activemq.jndi.ActiveMQInitialContextFactory, -Djnlp.java.security.auth.login.config=https://10.106.126.231/auth.conf, -Djnlp.core.version=10.1.1.0.35 (Linux) , -Djnlp.zebedee.idleTimeout=5400, -Djnlp.java.naming.provider.url=tcp://10.106.126.231:61616, -Djnlp.vpn_sm_launch=https://10.106.126.231:8880/voyence/voyence/vpn/?ALI=, -Djnlp.org.netbeans.ProxyClassLoader.level=1000, -Djnlp.zebedee.bufferSize=8192, -Djnlp.ui.instances=500, -Djnlp.help_base_url=https://10.106.126.231/help/, -Djnlp.unix.telnet.var=$VC_TELNET_VAR, -Djnlp.ui_jms_topic_name=dynamicTopics/topic/UIEvents, -Djnlp.deviceservices.version=28.0.0.0.35, -Djnlp.topic_conn_factory_jndi_name=ConnectionFactory, -Djnlp.DISABLEDcustomer=hp, -Djnlp.feature.autoLogin.enabled=false, -Djnlp.netbeans.user=ncm, -Djnlp.reports_advisor_url=http://vmwbgc231:58080/APG/, -Djnlp.log.file.destination=/VoyenceControl/logs/10.106.126.231/uiClient.txt, -Djnlp.legacy_reports_advisor_url=https:///web/, -Djnlp.use.client.default.telnet=true, -Djnlp.java.naming.factory.url.pkgs=org.jnp.interfaces, -Djnlp.zebedee.serverPort=11965, -Djnlp.server_ip=10.106.126.231, -Djnlp.cc.remoting.servlet.base=http://10.106.126.231:8881/ncm-webapp/remoting/, -Djnlp.netbeans.mainclass=org.netbeans.core.startup.VoyenceMain, -Djnlp.sun.java2d.noddraw=true, -Djnlp.sun.java2d.d3d=false, --add-exports=java.base/sun.net.www.protocol.jar=ALL-UNNAMED,java.desktop, --add-exports=java.base/jdk.internal.util.jar=ALL-UNNAMED,java.desktop, --add-exports=java.base/com.sun.net.ssl.internal.ssl=ALL-UNNAMED,java.desktop, --add-reads=java.naming=ALL-UNNAMED,java.desktop, --add-exports=java.desktop/sun.awt.X11=ALL-UNNAMED,java.desktop, --add-exports=java.desktop/sun.applet=ALL-UNNAMED,java.desktop,jdk.jsobject, --add-exports=java.base/sun.security.action=ALL-UNNAMED,java.desktop, --add-reads=java.base=ALL-UNNAMED,java.desktop, --add-exports=java.base/sun.net.www.protocol.http=ALL-UNNAMED,java.desktop, --add-exports=java.naming/com.sun.jndi.toolkit.url=ALL-UNNAMED,java.desktop, --add-exports=java.base/sun.security.util=ALL-UNNAMED,java.desktop, --add-reads=java.desktop=ALL-UNNAMED,java.naming, --add-exports=java.desktop/sun.awt=ALL-UNNAMED,java.desktop, --add-exports=java.base/sun.security.x509=ALL-UNNAMED,java.desktop, --add-exports=java.desktop/javax.jnlp=ALL-UNNAMED,java.desktop, --add-exports=java.base/sun.security.provider=ALL-UNNAMED,java.desktop, --add-exports=java.base/sun.security.validator=ALL-UNNAMED,java.desktop, net.sourceforge.jnlp.runtime.Boot, -Xnofork, -verbose, C:\Users\Administrator\Downloads\powerup (3).jnlp]'`

This line shows the command of the Java process that will be started to execute your application. Based on this information it is possible to create a BAT on windows and call the process with the given parameters by hand again. Can you do that? Maybe we will see more information on the command line by doing so.

**Comment by neelambatra** [comment]
Thanks, I ran it from the command line and finally got the issue, this was due to VM argument -Xincgc which doesn't work from java 9 onwards. Got the same issue listed below 
"JNLP with vm args "-Xincgc" fails to get loaded silently from jre9-b42" https://bugs.openjdk.java.net/browse/JDK-8068775

Thanks for the support. This issue can be closed.
