### ISSUE TITLE
question: is there a restriction related to the JRE used?

### ISSUE THREAD

**Issue by undergraver** [karakun/OpenWebStart#292]
In our environment we have multiple applications that we want to convert to work with openwebstart.

Most of them will need to be run with java 1.8.
Other may even run with newer versions of java.

Is there a restriction related to the minimum java version required?

We specify the JRE version in JNLP files ( jnlp/resources/j2se tag if that is relevant). Hopefully openwebstart takes into account these settings.

**Comment by hendrikebbers** [comment]
Hi,
OpenWebStart works with Java 8+. We already have customers that use OpenWebStart to manage and Start Java 11 based applications. OpenWebStart provides some nice mechanisms to specify the needed Java version (even with a specific vendor) for each JNLP based application. You can find more information here:

- [OWS Guide](https://github.com/karakun/OpenWebStart/blob/master/documentation/guide/OWSGuide.adoc)
- [OWS FAQ](https://github.com/karakun/OpenWebStart/blob/master/documentation/faq/FAQ.adoc)

Next to this we provide commercial support & Consulting (like a remote call) for OWS. You can find more information [here](https://openwebstart.com/support/#paid-support-packages).
