### ISSUE TITLE
Adding . editorconfig file

### ISSUE THREAD

**Issue by hendrikebbers** [karakun/OpenWebStart#302]
**🆕🐥 First Timers Only**

This issue is reserved for people who never contributed to OpenWebStart or Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

**👾 Description of the issue**

We should add a .editorconfig file to OpenWebStart. See https://editorconfig.org/ for he definition. This is based on a discussion in https://github.com/AdoptOpenJDK/IcedTea-Web/pull/679 <- The PR contains the info how to create it in IntelliJ.

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] Claim this issue: Comment below.
- [ ]  Fork the repository in github by simply clicking the 'fork' button.
- [ ]  Check out the forked repository
- [ ]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [ ]  Commit your changes.
- [ ]  Start a Pull Request.
- [ ]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the master branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🎉 Contribute to Hacktoberfest**

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a change to receive cool goodies like a T-Shirt. 🎽

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by sonechca** [comment]
Hi,

I would like to add .editorconfig file. Can I fork and PR for this issue? I really want to be a contributor 
Thank you

**Comment by sclassen** [comment]
Hi @sonechca great to have you here !!
Please go ahead and start working on this issue.

**Comment by r-sreesaran** [comment]
@sonechca can i pick this up ?

**Comment by Jamila891** [comment]
@sonechca hey, you have not signed the contributer license agreement. @r-sreesaran you can create a new pull-request if you want.
