### ISSUE TITLE
No Java runtime present

### ISSUE THREAD

**Issue by rishabhdeepsingh** [karakun/OpenWebStart#303]
Getting error even though I have Java installed.
```
➜ javaws ContestAppletProd.jnlp
No Java runtime present, requesting install.
Unable to locate a Java Runtime to invoke.
```
<img width="326" alt="Screenshot 2020-08-02 at 2 34 57 AM" src="https://user-images.githubusercontent.com/28526643/89110517-e57bbb00-d468-11ea-9048-8294db568cf1.png">
<img width="416" alt="Screenshot 2020-08-02 at 2 35 04 AM" src="https://user-images.githubusercontent.com/28526643/89110518-e6145180-d468-11ea-9195-888814b36a27.png">

<img width="1546" alt="Screenshot 2020-08-02 at 2 34 13 AM" src="https://user-images.githubusercontent.com/28526643/89110511-e01e7080-d468-11ea-80bc-fddd5b86b43f.png">

**Comment by sclassen** [comment]
The middle screenshot looks like it is not from OpenWebStart.

Maybe there is still a webstart from oracle on the path.

Which OS are you using?

Can you make sure OWS is used by passing the absolute path to the executable (javaws) when launching the jnlp.

**Comment by rishabhdeepsingh** [comment]
I am using macOS Catalina (10.15.6).
How do I check which `javaws` is my system using?

**Comment by sclassen** [comment]
On the console you can enter `which javaws`

In the UImaybe @hendrikebbers knows how to check this

**Comment by rishabhdeepsingh** [comment]
```
which javaws
/usr/bin/javaws
```

**Comment by hendrikebbers** [comment]
At the moment it is not possible to call `javaws` from the shell / terminal since OpenWebStart does not provide a `javaws` process for MacOS. The `javaws` process on your machine is still the old process that comes from Oracle WebStart.

You can try 
`
open ContestAppletProd.jnlp
`

**Comment by rishabhdeepsingh** [comment]
`open` is working but how do I know which Java is it using? can I safely delete Java `1.8` if I want to?

**Comment by hendrikebbers** [comment]
OpenWebStart manages Java versions on you system. Open the OpenWebStart settings and have a look at the JVM manager. Next to this you can find information [here](https://github.com/karakun/OpenWebStart/blob/master/documentation/guide/OWSGuide.adoc) on our[ free webinar in 2 weeks](https://board.karakun.com/viewtopic.php?f=9&t=125).

**Comment by rishabhdeepsingh** [comment]
Thank a lot.
