### ISSUE TITLE
Downloading files from JNLP using open web start plugin takes longer as compared to downloading the same JNLP using java web start

### ISSUE THREAD

**Issue by yuvraj18yadav** [karakun/OpenWebStart#304]
The Standalone setup(.exe,.dmg) consisting of Approx 750 MBS of jar gets downloading in 2-3 mins with a high internet speed connection. The same set of files that are generally jars downloaded using JNLP technology using existing java web start launch technology takes almost the same time which is 2-3 mins. 
Now when we tried launching the application using the same JNLP file using open web start plugin it took 10-12 mins for the same set of jars/files. 
Can you please help why downloading speed is affecting when we use open web start plugin for downloading the resources/files/jars and launching the application.

**Comment by sclassen** [comment]
OWS uses different caching strategies than oracle web start. This can lead to different performance.

To further analyse your situation we would need logs and the jnlp.

**Comment by FelixJongleur42** [comment]
How many Jars? Maybe this has to do with the slow progress dialog (which is being reworked).

**Comment by yuvraj18yadav** [comment]
> OWS uses different caching strategies than oracle web start. This can lead to different performance.
> 
> To further analyse your situation we would need logs and the jnlp.


[site_manager.pdf](https://github.com/karakun/OpenWebStart/files/5013238/site_manager.pdf)
[itw-javantx-2020-08-03_05:20:56.835.log](https://github.com/karakun/OpenWebStart/files/5013239/itw-javantx-2020-08-03_05.20.56.835.log)
[itw-clienta-2020-08-03_05:22:51.631.log](https://github.com/karakun/OpenWebStart/files/5013240/itw-clienta-2020-08-03_05.22.51.631.log)

Hi please find attached the JNLP file with name site_manager.pdf . Kindly rename the file to .jnlp extension and also find attached the logs which were generated while loading the resources from server and then launching the system over the machine .

**Comment by yuvraj18yadav** [comment]
around 40 jars and total size of the downloaded jars comes around 730 MB
approx.
please find attached the jnlp which contains info about the jars .
plus logs as well

**Comment by hendrikebbers** [comment]
We are currently working on a new download mechanism. The first changes will be part of the next release of OpenWebStart that will be released in around 2 weeks. Maybe that release already helps. @yuvraj18yadav please return to this issue once OWS 1.2 is available and you have tried the application with that version. If you still have problems with 1.2 this will be a good input for us.

**Comment by yuvraj18yadav** [comment]
Thanks for the update. If you can share what is the difference between the
download mechanism of existing java web start tech in comparison to open
web start plugin.
Any setting/tweak to increase the download of files for the time being.

**Comment by sclassen** [comment]
Oracle Web Start is closed source.
So we do not know how its internals are working.
We are constantly improving on OWS both in features and in performance.
The next release will be out shortly and will contain performance improvements for the download of resources.

If you are in a real need for a fix consider one of our paid support contracts
https://openwebstart.com/support/

**Comment by hendrikebbers** [comment]
Hi @yuvraj18yadav we released OpenWebStart 1.2 yesterday. It supports parallel download of application resources. Can you please give it a try.

**Comment by Th3WalkingDad** [comment]
Hi @yuvraj18yadav 



At first I was only answering you to try latest OWS:

> IMHO, you will have a great improvement, as you have relatively few jars and a huge amount of data to load that will be now parallelized.
> OWS 1.1.8 was using 1 connection.
> JWS looks to use 4 .
> OWS 1.2.1 is now using 6... so it may even be faster than JWS !?  Tell us !  (Indeed I'm eager to have another feedback :-p).
> 



But by curiosity, I had a look into your logs and several things puzzle me :
a) all the resources have the same **lastModified: 1593624726000** (except the first [image/jpeg] ... OK this could be),  but very unlikely to have the *SAME* **Content-Length=[21258240]** for all the further **[application/x-java-pack200]** !!!
	Maybe that's only a log display bug ???
	
b) application/x-java-pack200 ? Oh... you are using pack200 ? That's maybe a hint : unusual used feature (IMHO).

c) The log following  
	`com.openwebstart.proxy.pac.PacBasedProxyProvider: PAC Proxies found for 'socket://10.184.22.66:443' : [DIRECT]`
	is very often (77 out of 81) 10-11 seconds *AFTER* that one. Sometimes (4 out of 81) even 20-24 seconds.  (some 10 seconds timeout ? linked with PAC Proxies ?)
	Adding all of this and you get at minimum 77*10+4*20=**850 seconds** 

**20min30** is the whole loading based on the logs (**1230 seconds**)
==> I feel at least 2/3 of the time is spent waiting for a reply ?

**Could you tell more about your network architecture /  your PAC based proxy ?**
Or try (with OWS 12.1) without PAC to exclude its impact ?!
	
d) Following the HEAD requests, the log 
	`net.adoptopenjdk.icedteaweb.resources.cache.CacheEntry: isCached: `
	contains remote and cached size.
  By adding the 40 sizes (see tab below)... I only end-up to 29 MB !?!? 
  You talked about 730 MB for the standalone setup (maybe with embedding JVM ?). Even in this case that's a too big difference. 
  Could you confirm by summing the files in cache in `/Users/ysingh/.cache/icedtea-web/cache/0/`  (supposely you have only 1 cached app otherwise you'll need to find the good folder or clear everything and start from scratch)


5043
6222
6245
6678
8272
8630
12047
12382
19258
22352
31344
33087
35120
72765
75464
125924 
133380 
135845 
156491 
197593 
200922 
206935 
241484 
250469 
321811 
423385 
538765 
589256 
599224 
756499 
822382 
861986 
1010997
1054611
1511522
2351554
2364705
2513474
4407998
7344352
SUM = 29476473   roughly "Only" 29MB

**Comment by yuvraj18yadav** [comment]
Hi sorry for the late reply.
I was out of town for little vacation .
Let me try the new open jws setup and will get back to you soon .
Secondly will provide you other details as soon as possible.

Regards
Yuvraj Singh

**Comment by yuvraj18yadav** [comment]
Hi @Th3WalkingDad 
I tried the setup with the updated setup of the open web start plugin. It is indeed fantastic and I am able to launch application considerably faster as well. Earlier it used to take 12 mins around, now the same is getting launched within 7 mins which is quite a lot of improvement . 

Secondly, the UI looks neat & clean as well. 
Thanks a lot, guys, you are doing great work. 

Do you still need the paramters/info which you have requested to me in last thread . if yes then i will share that as well . 

Regards
Yuvraj Singh

**Comment by Th3WalkingDad** [comment]
Hi @yuvraj18yadav ,

Glad to see the improvement. If your happy with your loading time, no need to send me back requested info.

I'm just thinking that if you are really "only" loading 29MB, that looks a bit slow to me, but I don't know **your line speed / latency**. 
And there's also those many 10 seconds wait (?) now maybe spread on 6 cnx. You may gain >2 min there by removing them IMHO.

my 2 cents ! :-)


==================

Comparing the smallest and biggest file loading log, 
- **slf4j-nop-1.7.7.jar** (6 222)  (there https://repo1.maven.org/maven2/org/slf4j/slf4j-nop/1.7.7/slf4j-nop-1.7.7.jar it's only 4090, but I suppose you have signed it)
- **base.jar**        (7 344 352)

**slf4j-nop-1.7.7.jar** :
first log : 05:34:23
last log  : 05:34:44
diff      :       21 sec (including 20 sec of "wait")

**base.jar :**
first log : 05:23:55
last log  : 05:24:47
diff      :       52 sec (including 21 sec of "wait")

So max avg DL speed is 1.9 Mbps / 240KB/sec.
There's often a ramp-up in TCP speed, so max possible speed is probably higher.


Checking with second biggest files :
ome12720aa01_omedefaultDescription.jar (4 407 998)
05:41:35 --> 05:42:33 = 58sec ( including 10 +11=21 sec of wait).  
There avg DL speed is only  1Mbps / 125 KB/sec

To give a **rough idea** to DL your jars (say 29 MB IMHO), I think you would need between 2 min (124" = 29MB / 240KB/sec) and 4 mins (29MB / 125KB/sec).
