### ISSUE TITLE
After opening the JNLP file using Open Web Start plugin , clicking on close button the launch is not aborted 

### ISSUE THREAD

**Issue by yuvraj18yadav** [karakun/OpenWebStart#311]
We download the JNLP from the server . Now we open the JNLP file using open web start plugin. 
Post opening the JNLP file open webstart window is launched, it does some processing for some time, and after that 2 small windows are launched one depicting the application to be launched and second one showing the progress of jars/files which are getting downloaded from Server. On clicking the Cancel button of both the pop-ups the launch of the application is not aborted although ideally it should get aborted as the user has clicked on cancel icon/button. 

Kindly suggest why it is behaving like this.

**Comment by hendrikebbers** [comment]
Hi,
can you please add the version of OpenWebStart that you are using and maybe a screenshot.
