### ISSUE TITLE
JVM Server Whitelist not possible via unattended installation

### ISSUE THREAD

**Issue by abrensch** [karakun/OpenWebStart#313]
The config-property "ows.jvm.manager.server.allowFromJnlp.whitelist" (new in version 1.2.0 ) is not included in  InitialConfigurationCheck.KEYS_OF_PROPERTIES_TO_TAKE_FROM_RESPONSE_VAR_FILE and so cannot be configured in an unattended installation.

**Comment by sclassen** [comment]
Thank you for reporting this.
We will check and if missing make a patch release.
