### ISSUE TITLE
Set a system property for the launched Java process containing the path of the javaws executable

### ISSUE THREAD

**Issue by martinhickson** [karakun/OpenWebStart#316]
It's useful for a launched JNLP application to know the javaws executable that it was started with.  In that way, it can use the Process API to launch another JNLP application without having to guess the OpenWebStart home directory.

For example, the properties could be similar to:

openwebstart.home=<path to AppData>\Local\Programs\OpenWebStart\
openwebstart.javaws=<path to AppData>\Local\Programs\OpenWebStart\javaws.exe

**Comment by sclassen** [comment]
If you are using windows we store the installation directory in the registry. You can find it under:
HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\OpenWebStart
