### ISSUE TITLE
OWS / IcedTea-Web confuses (cached) JNLP files coming from the same IP, but two different virtual hosts

### ISSUE THREAD

**Issue by FelixJongleur42** [karakun/OpenWebStart#317]
Using OWS 1.2.1 under Windows

**Scenario:**
https://a/file.jnlp - has https://a as codebase in its file
https://b/file.jnlp - has https://b as codebase in its file

Crucial !? **a and b resolve to the same IP.**
Possibly crucial? a and b are accessed through outbound company proxy.

**Steps to reproduce:**
1. clear cache, like this: `del /q /s %USERPROFILE%\.cache\icedtea-web\cache`
2. run a - OK
3. run b - WRONG: effectively runs a

**Other way around:**
1. clear cache, like this: `del /q /s %USERPROFILE%\.cache\icedtea-web\cache`
2. run b - OK
3. run a - WRONG: effectively runs b

**This works:**
1. clear cache
2. run a
3. clear cache
4. run b

Looks like something is cached by IP and not hostname?

Why bother resolving DNS? related? https://github.com/AdoptOpenJDK/IcedTea-Web/issues/110

Any suggested workarounds that are more efficient than deleting the (whole) cache between two calls?

**Comment by sclassen** [comment]
you can take a look at the %USERPROFILE%\.cache\icedtea-web\cache\recently_used file
It contains the keys (x-y.href) which are used to check if a resource is in the cache.

are the keys the ones you expect or are you seeing unexpected values?
If you see unexpected values, can you please provide an example of actual and expected values.

**Comment by FelixJongleur42** [comment]
> you can take a look at the %USERPROFILE%.cache\icedtea-web\cache\recently_used file

Again, I am afraid I currently don't have time to look into those files, I would really like to.

**Comment by sclassen** [comment]
We are ready to take a look at this whenever you find time to give us more information

**Comment by Jamila891** [comment]
closed due to inactivity
