### ISSUE TITLE
disable shortcut terminal server

### ISSUE THREAD

**Issue by JBtosch** [karakun/OpenWebStart#320]
Hi,
I was wondering if it is possible to disable the shortcut message you get when opening an application with OWS. Every time a terminal server user opens the application, he gets this message. I tried to disable this message to set the desktop intergration on Never Create but this was not the solution.

![error](https://user-images.githubusercontent.com/70642594/91981058-8be90380-ed28-11ea-894b-df1c4f1976f5.jpg)

**Comment by sclassen** [comment]
Thank you for your interest in OpenWebStart

You already have found the option to disable the create dialog. You mention that in your setup you have a Terminal Server.
Thus I assume there are many different users executing OpenWebStart
OpenWebStart saves the configuration in the user folder. Thus every user can have different settings.
There is a possibility to define a system wide configuration.
You can find a step by step guide here:
https://github.com/karakun/OpenWebStart/blob/master/documentation/guide/OWSGuide.adoc#system-configuration

**Comment by sclassen** [comment]
@JBtosch did it solve your problem?
