### ISSUE TITLE
Openwebstart will not detect on Nvidia's Auto update website

### ISSUE THREAD

**Issue by MChang1984** [karakun/OpenWebStart#324]
Hello,

I Installed the latest version of Openwebstart and tried to run java on NVidia's Auto Update website with URL https://www.nvidia.com/Download/Scan.aspx?lang=en-us

The webpage never shows up and instead asks for Java to run.

The browser used is Google Chrome Version 85.0.4183.102 (Official Build) (64-bit)

Lots of people use NVidia for Driver updates and this should be looked at to resolve this issue with Openwebstart to detect Java and work on NVidia's site.

![NVidiaJava](https://user-images.githubusercontent.com/14915154/93534097-410ae680-f8f9-11ea-9027-a7ce2407443a.PNG)

**Comment by sclassen** [comment]
Sorry to disappoint you but OpenWebStart does not include any browser plugin.
All modern browser have ceased to support Java applets running in them. Thus we have also dropped this feature.

I am currently on Linux and the message from the site I see is a little different:
```
We're sorry, the NVIDIA Smart Scan does not support your system at this time.
Supported operating systems: Microsoft Windows 98, 98SE, ME, 2000, XP, 2003, Media Center, Vista and Windows 7
Supported browsers: Internet Explorer, Firefox & Netscape. 
```
All of the above (except for Firefox) are not actively maintained any more.
Maybe you can contact NVidia if there is an alternative way on obtaining the right driver for your hardware
