### ISSUE TITLE
Provide Factory and constants for general Layout components

### ISSUE THREAD

**Issue by hendrikebbers** [karakun/OpenWebStart#329]
**🆕🐥 First Timers Only**

This issue is reserved for people who never contributed to OpenWebStart or Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

**👾 Description of the issue**

For the panels of the OpenWebStart settings several layout are reused at a lot of places at the code. Concrete examples are the gap of the layouts (for example `new Borderlayout(12, 12)`) and borders (see `BorderFactory.createEmptyBorder(12, 12, 12, 12)`). We should provide a `LayoutUtils` / `LayoutFactory` class at `com.openwebstart.ui` that provides constants and static factory methods for such layouts.

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] Claim this issue: Comment below.
- [ ]  Fork the repository in github by simply clicking the 'fork' button.
- [ ]  Check out the forked repository
- [ ]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [ ]  Commit your changes.
- [ ]  Start a Pull Request.
- [ ]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the master branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🎉 Contribute to Hacktoberfest**

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a change to receive cool goodies like a T-Shirt. 🎽

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by r-sreesaran** [comment]
I am working on this issue

**Comment by r-sreesaran** [comment]
Will the Layout Factory class will also contain instances of BoxLayout GridBag Layout and the other classes that has implemented LayoutManager2 ?.

**Comment by hendrikebbers** [comment]
No, we do not use that layout managers in the application. Based on your question it would make sense to dicuss your solution before you do a lot of work that is not needed :) Maybe you can describe in a few sentences how you plan to solve this issue?

**Comment by r-sreesaran** [comment]
I would create a class LayoutFactory class with static methods that would return the instances of Borderlayout class. 
This would cover all the constructors that are available in BorderLayout class. 

Thanks
R.Sreesaran
