### ISSUE TITLE
Could not start JNLP on Linux

### ISSUE THREAD

**Issue by ortmeier** [karakun/OpenWebStart#33]
- OpenWebStart 3.0.2
- Ubuntu 18.04.3
- Java 11.0.4

When I launch the jnlp file I get this error:
`
java.lang.RuntimeException: Can not provide or find runtime for version '11.0.4+', vendor 'AdoptOpenJDK' and operating system 'LINUX64'
    at com.openwebstart.jvm.JavaRuntimeSelector.lambda$getRuntime$1(JavaRuntimeSelector.java:77)
    at java.util.Optional.orElseThrow(Optional.java:290)
    at com.openwebstart.jvm.JavaRuntimeSelector.getRuntime(JavaRuntimeSelector.java:77)
    at com.openwebstart.jvm.JavaRuntimeSelector.getJavaRuntime(JavaRuntimeSelector.java:49)
    at com.openwebstart.launcher.OwsJvmLauncher.getJavaRuntime(OwsJvmLauncher.java:57)
    at com.openwebstart.launcher.OwsJvmLauncher.launchExternal(OwsJvmLauncher.java:47)
    at net.sourceforge.jnlp.Launcher.launchExternal(Launcher.java:321)
    at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:406)
    at net.sourceforge.jnlp.Launcher.access$400(Launcher.java:70)
    at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:782)
`

**Comment by AndreasEhret** [comment]
From which vendor is your "Java 11.0.4" installation? Could you give us more details on your JVM Manager settings (https://openwebstart.com/jvm-manager)? Looks like you have installed a Oracle Java 11.0.4 but in your OWS Settings you restrict your JVMs to the ones from vendor 'AdoptOpenJDK'. Please also check if in the list of JVMs at least one JVM is activated.

**Comment by ortmeier** [comment]
Maybe I should explain my situation first.

The PC where OWS is installed has no Internet because of security arrangements of my company.

I do not really know how OWS works or if it needs internet.
The program I have programmed and the JNLP file is located on an internal server of my company (intranet).

I have been able to fix the last error but now I get a new one.
I have not changed the settings and have only one jvm activated.

The error message: https://hastebin.com/tifecumore.sql
JVM manager settings: https://imgur.com/a/2LT0kTJ

**Comment by AndreasEhret** [comment]
is it possible to also have a look at your .jnlp file?

**Comment by ortmeier** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<jnlp
  spec="1.0+"
  codebase="http://placeholder.de/test"
  href="test.jnlp">
  <information>
    <title>Test</title>
    <homepage href="http://placeholder.de/"/>
    <description>Description</description>
    <offline-allowed/>
  </information>
  <resources>
    <j2se version="1.11+"/>
    <jar href="Program.jar"/>
  </resources>
  <application-desc main-class="Main"/>
</jnlp>
`

**Comment by sclassen** [comment]
What sticks out immediatly is your j2se version.
This should be 11+ as java has changed its versioning scheme after 1.8.x swtiching to 9.x, 10.x, 11.x

Also the log seams to be incomplete but it contains the following line:
```
Trying to find local Java runtime. Requested version: '11.0+' Requested vendor: 'AdoptOpenJDK' requested os: 'LINUX64'
```
Your screenshot lists an openjdk (by Ubuntu). In the current version the JVM Manger only supports a hard-coded list of vendors. We will change this in an upcoming version
For now you can change the vendor in your JVM manager settings to `*` indicating any vendor (which also includes Ubuntu).

**Comment by ortmeier** [comment]
Thanks!

**Comment by sclassen** [comment]
Your welcome
can you close the issue if it is working for you.
