### ISSUE TITLE
New download dialog shouldn't take focus

### ISSUE THREAD

**Issue by jastax** [karakun/OpenWebStart#333]
The new download dialog takes focus for every jar that is loaded. Downloading many jars means the users computer is more or less unusable for that time. Could it become one dialog that doesn't take the focus for every new jar?

**Comment by sclassen** [comment]
@hendrikebbers can you take this up

**Comment by janakmulani** [comment]
Hi,

I hope you are using OWS 1.2.0 or greater.

I tried downloading many large jars from [here](https://download-openwebstart.com/download-test-hendrik/webstart-monitor.jnlp).

There is one dialog (see picture) that shows progress of each jar being downloaded. This dialog does not take away focus i.e I can continue working on a word doc while OWS is downloading jars and displaying progress in the dialog.

![Jar-Download-Dialog](https://user-images.githubusercontent.com/655389/95821959-a1e6dc80-0d48-11eb-9dd8-c65bbeb3fc89.PNG)

**Comment by jastax** [comment]
Hi,

I'm using 1.2.1 on Linux with no parallel downloading.

**Comment by jastax** [comment]
![Uploading video.gif…]()

**Comment by jastax** [comment]
![video](https://user-images.githubusercontent.com/1672178/95831999-08b0c980-0d3a-11eb-929e-2ee7a3b31ea0.gif)

**Comment by jastax** [comment]
The file you provided above does work like you describe. Maybe the multiple download dialogs happen on extensions only?

**Comment by janakmulani** [comment]
Thanks for confirming.

So you have a jnlp with extensions which have additional jars. 

I will try to reproduce your issue by creating an extension jnlps.

**Comment by janakmulani** [comment]
I created [jnlp with extensions](https://download-openwebstart.com/download-test-hendrik/manyjars_with_ext.jnlp). 

For each ext jnlp and the main jnlp the download  progress dialog comes up. However it does not take away focus from other apps such as word or file explorer. It only takes focus away from the OWS consoles (which is OK). 

![DownloadDlgFocus](https://user-images.githubusercontent.com/655389/95992829-03dc3a80-0e4c-11eb-9fde-30c0fc713010.PNG)

**Comment by jastax** [comment]
On Linux (in my case Ubuntu it takes the focus from any app

**Comment by jastax** [comment]
I pressed x the whole time 

![video](https://user-images.githubusercontent.com/1672178/96703868-a6884200-1393-11eb-8459-687ebe520c47.gif)

**Comment by janakmulani** [comment]
I tested on Windows. 

@sclassen can you please test [jnlp with extensions](https://download-openwebstart.com/download-test-hendrik/manyjars_with_ext.jnlp) on Linux?

**Comment by jastax** [comment]
I'm testing 1.3.1 on Windows and am running into the same issue. Focus is taken away

**Comment by janakmulani** [comment]
Did you use [jnlp with extensions](https://download-openwebstart.com/download-test-hendrik/manyjars_with_ext.jnlp)?

**Comment by jastax** [comment]
Yes, focus is taken away when using that JNLP. 
Windows 10 Enterprise, Version 1809

**Comment by janakmulani** [comment]
@jastax So what is different between your set up and mine? I have Windows 10 Pro 10 build 18363. Which JRE is being used in your case? In my case it is Oracle JRE 11.0.9.

**Comment by jastax** [comment]
It's running either Oracle JDK8 or AdoptOpenJDK 8, but I can only confirm in January

**Comment by jastax** [comment]
Y:\>java -version
openjdk version "1.8.0_265"

**Comment by janakmulani** [comment]
@jastax I tested  with AdoptOpenJDK 1.8.0_275 on Windows but I cannot reproduce the issue, i.e. focus is not lost from Word app while OWS is displaying progress dialog for downloading multiple jars in multiple extensions.

**Comment by sclassen** [comment]
I can reproduce this on Linux. Looks like it is OS dependent

**Comment by jastax** [comment]
> I can reproduce this on Linux. Looks like it is OS dependent

Thanks for confirming.

I also lost focus on Windows, but that might be due to the bug I reported for ITW and you already fixed. I will re-test on Windows after the patch is available.

**Comment by jastax** [comment]
OWS 1.3.2 Windows, launching the JNLP (https://download-openwebstart.com/download-test-hendrik/manyjars_with_ext.jnlp) -> Focus is still taken away.

**Comment by janakmulani** [comment]
I tried on my Windows 10 machine. I cannot reproduce the issue => Focus remains with Word while the OWS download progress is shown:

![image](https://user-images.githubusercontent.com/655389/106251938-a5d93480-623b-11eb-9ee6-f2493d83eb56.png)

**Comment by sclassen** [comment]
Yes Janak, this is OS dependent. It is reproducible on Linux. We also need to check it on Mac

**Comment by jastax** [comment]
> Yes Janak, this is OS dependent. It is reproducible on Linux. We also need to check it on Mac

On Windows I also lose focus.

First, the splash screen shows for a short time.

After that the downloads start. I'm losing focus for each extension, I think.

Some of the time there is no dialog to see at all (which is the reason why I launched multiple instances (https://github.com/AdoptOpenJDK/IcedTea-Web/issues/744).

I will try to make a screen recording
