### ISSUE TITLE
jnlp <java version="1.8*"> is starting java 11

### ISSUE THREAD

**Issue by detmar-krause** [karakun/OpenWebStart#334]
using openwebstart 1.2.1

1. configured openjdk 1.8 and 11 in JVM Manager
2. starting jnlp with version 1.8* 
3. application is started with openjdk11

How can I start an application with such configuration with java 1.8.
The only option at the moment is to remove java 11 from JVM Manager

**Comment by sclassen** [comment]
in the JNLP a version of `1.8*` means Java 1.8 or any bigger version.
As such Java 11 is bigger than 1.8

If you want to say any java 1.8 version you can express this by setting the version in the JNLP to `1.8+`
Details are in the appendix of JSR-56

**Comment by detmar-krause** [comment]
<java version="1.8+"> is also starting the app with java 11

**Comment by sclassen** [comment]
it is not sufficient to change the version in the local copy of the JNLP file as OpenWebStart will download the current version from the server and use this to start the application.
You need to make sure that the JNLP on the server is updated

**Comment by detmar-krause** [comment]
when I start the app direct using the browser url to the jnlp (...<j2se version="1.7+" java-vm-args="-Xmx1024m -Xms256m -Xss8m" />...) openwebstart is starting the app with java 11

**Comment by sclassen** [comment]
Is the application public available such that we can try it out?

**Comment by detmar-krause** [comment]
okay, version 1.8* is working, changing on the server side was the right answer, thanks.

**Comment by detmar-krause** [comment]
configuration error on my side, can be closed

**Comment by msmolka** [comment]
Hello, I also have this issue. Application will not work with JDK 11. And even if I manually specify version 1.8 in jnlp file as well as I remove ALL other VMs except 8. It always asks me to install new version 11. 

> https://www.bt747.org/webinstall
> http://soft.bt747.org/BT747_J2SE.jnlp

Even if it stats with 11 it won't connect to device. The only way to run is use version 8. However I cannot force **open web start** to use it. Even if file inside is 1.5+. Setting it manually is running but always popup new version is available even if I set in setting to never run it.

![obraz](https://user-images.githubusercontent.com/6661461/98656195-b4046c80-2340-11eb-9a5f-09bc62852644.png)

**Comment by sclassen** [comment]
You can set the version in the JNLP file to `1.8.*` which means any 1.8 but nothing newer

**Comment by sclassen** [comment]
The screenshot you attach is for the update of openwebstart itself.
The update of the JVM is handled in the tab `JVM Manager` and then in the bottom left there is a button `Settings`

**Comment by sclassen** [comment]
Set the version in the JNP file to `1.8.*`
Be sure to also do this in the JNLP file in the server as OWS will download the file and use the version from the server instead of the local one.

**Comment by msmolka** [comment]
`<j2se version="1.8.*" max-heap-size="192m"/>`
creates fatal exception:
`net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file at 'file:/D:/BT747_2.2.1/BT747_J2SE.jnlp'. You can try to download this file manually and send it as bug report to IcedTea-Web team.`

**Comment by sclassen** [comment]
Sorry my bad. there should not be a `.` after the 8.
Correct is: `1.8*`
