### ISSUE TITLE
Native libraries on MAC doesn't works

### ISSUE THREAD

**Issue by arturkanclerzCGM** [karakun/OpenWebStart#336]
Hello,

I'm using OpenWebStart 1.2.2 and LibericaJDK 11. I've trying to run my app with included native libraries ( with .jnilib extension) on MacOS, but it's doesn't works. The aplication doesn't see included libraries: Exception in thread "AWT-EventQueue-1" java.lang.UnsatisfiedLinkError: no opencv_java in java.library.path

The same jnlp file running with Java Web Start works finese

**Comment by sclassen** [comment]
This has been fixed with https://github.com/AdoptOpenJDK/IcedTea-Web/pull/695 and will be available with version 1.3.0 most likely mid of November

**Comment by sclassen** [comment]
Temporary workaround described in #323
