### ISSUE TITLE
Does OWS support proxy authentication with NTLM or Kerberos authentication method?

### ISSUE THREAD

**Issue by alslw** [karakun/OpenWebStart#338]
Hi
      When we set proxy type to be "System proxy" that it will use IE Proxy. Is this proxy authentication with NTLM or Kerberos authentication method ? or IF we want to use proxy authentication with NTLM or Kerberos authentication method. Can OpenWebstart support proxy authentication with NTLM or Kerberos authentication method ?

**Comment by janakmulani** [comment]
@alslw  Unfortunately OWS does not support this at present. If this is high priority for you would you be interested in sponsoring this feature?

**Comment by bruste** [comment]
@janakmulani How is it today? Does OWS now support Kerberos Authentication?

**Comment by AndreasEhret** [comment]
Currently there are still no plans to support Kerberos.

**Comment by bruste** [comment]
@AndreasEhret : Thanks for the Info
