### ISSUE TITLE
jvms.json is trying to be downloaded even if "never update JVM" is set - fails on machines with no internet

### ISSUE THREAD

**Issue by in-fke** [karakun/OpenWebStart#353]
We are using OWS on a machine while there is no internet, thus a locally managed JVM which was downloaded previously.
Under "JVM Settings" we set "Never update JVM".

**The JNLP launch fails because OWS still tries to download (the first?) "jvms.json".**

**Workaround:**
"Pre-Fetch" jvms.json in some way, while in the internet, then go back to VPN Dial-In and go the actual launch

**Suggestions:**
1. OWS should try to download "jvms.json" during install
2. OWS should come with a preshipped jvms.json in order to be happy
3. **OWS should really honor "Never update JVM" and be happy with a manually installed JVM**

(I would prefer the last)
I hope I did not produce any duplicates because there are some Whitelist tickets out there.

**Comment by sclassen** [comment]
Could you give us the stacktrace from the logs so we can make sure that we do not miss the case you are encountering

**Comment by in-fke** [comment]
I will try to reproduce it, but it should go as follows:
1. Vanilla install
2. Install one JVM manually
3. Turn JVM Management / Settings / to "Never update JVM"
4. turn off internet
5. run a JNLP Launch (e.g. within the LAN, or to localhost)
6. OWS tries and fails to download jvms.json
