### ISSUE TITLE
OpenWebStart certificate issue

### ISSUE THREAD

**Issue by Mannclaudiu** [karakun/OpenWebStart#355]
Hello,

While working at a client-server application (client on Windows, server on Linux) that uses certificates, when I open that application through OpenWebStart, it is giving me an error saying that _**java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty**_

Now, this error is due to not being able to find _trusted.cacerts_ on client machine (even if the file exists there !)

In order to verify that is not an issue on our side, I did the same with IcedTea-Web. Now, things are a bit different. When I launch the application through IcedTea-Web, the following window is displayed (I have hidden certificate data).

![Untitled](https://user-images.githubusercontent.com/22660140/99060467-bec13a80-25a8-11eb-9a83-b8080f55678e.png)

Once I click on _Yes_ , the _trusted.cacerts_ gets updated and the error is gone. So, I suppose that something goes wrong with OpenWebStart, because it is not updating the trusted.cacerts file. I was looking for an option in settings and I couldn't find something suggestive over there.

I am using AdoptOpenJDK 1.8 on both OWS and ITW. On OWS I have checked out with Azul Systems 1.8, same issue

**Comment by sclassen** [comment]
Could you please attach a the log from OpenWebStart

**Comment by Mannclaudiu** [comment]
[Uploading 2020-11-13_12_21_00.740-ows-stage2.log…]()

**Comment by sclassen** [comment]
Sorry the log is somehow missing.

**Comment by Mannclaudiu** [comment]
Please try again now, my fault

**Comment by Mannclaudiu** [comment]
This is the way that I specify the trusted cert
` System.setProperty("javax.net.ssl.trustStore", System.getProperty("deployment.user.security.trusted.cacerts"));`

It simply points to the following path C:\Users\user\.config\icedtea-web\security

**Comment by sclassen** [comment]
This means you are taking the trus store from %USER_HOME%/.config/icedtea-web/security

**Comment by Mannclaudiu** [comment]
Yes indeed. And that trust store is not updated by OWS, the way it is updated with ITW

**Comment by Mannclaudiu** [comment]
I was trying now something. 
- deleted cache
- ran application
- it downloaded jvm (I was trying with both AdoptOpenJDK 8, and 11
- after a while the window shown in my post appeared, I pressed YES
- trusted.cacerts still not updated, and app gives same error

**Comment by sclassen** [comment]
Ok, this is a guess:
The difference between OWS and ITW is that ITW will run only one JVM where OWS will always run two JVM (one for the initialization, and one for the application). Since now both JVMs are using the same trustStore maybe they are preventing each other from modifying it.

There are 2 ways to verify this theory:
1) make a copy of the trust store and let your application point to the copy. If the error does not appear then this indicates a mutual lockout.
2) change the JNLP by adding an initial heap size `initial-heap-size="64m"` to the java/j2see element. And then execute it using ITW. The initial heap size will force ITW to also start a second JVM. If the error now also appears with ITW this again indicates a mutual lockout. But be sure to remove the `href` attribute from the `<jnlp>` element as otherwise ITW will re-download the JNLP and overwrite the initial heap size

**Comment by Mannclaudiu** [comment]
Sure, I will try and will let you know about the results. Thank you !

**Comment by Mannclaudiu** [comment]
I was trying the first approach and got the following results:
- if application points to copy of trust store, error is gone
- if I delete the copy of trust store, so the application is unable to find it, the error is gone
From above two scenarios, I concluded that setting that property who leads to trusted store generated the error. So, I erase the following line from my code `System.setProperty("javax.net.ssl.trustStore", System.getProperty("deployment.user.security.trusted.cacerts"));` and no more error.

Now it works on OWS, just like I wanted.

It doesn't work anymore on Icedtea-web now. It complains about a different error saying that it can't find a path to a trust store 
**_Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target_** . 

At this moment, I am not interested in IcedTea-Web, I just keep it in order to have an additional tool which can run my application.

**Comment by sclassen** [comment]
Is this issue ressoved for you or should we look into it further?

**Comment by Mannclaudiu** [comment]
Is resolved. Thank you for your time and help ! :)
