### ISSUE TITLE
Any way to add a local JVM via response.varfile?

### ISSUE THREAD

**Issue by filipdimkin** [karakun/OpenWebStart#357]
Hi team,

I'm currently looking to package this up for my organization (Windows 10) and was wondering whether there is a way for me to automatically specify a local JVM in JVM Manager through the response.varfile?
E.g. C:\Program Files\AdoptOpenJDK\jre-11.0.8.10-hotspot

Thanks.

**Comment by sclassen** [comment]
This will be possible with the next version (1.3.0) which will be released this week.

**Comment by rafik777** [comment]
@sclassen 
I see that OWS 1.3.0 is released here:
https://github.com/karakun/OpenWebStart/releases

but I don't see this version here:
https://openwebstart.com/download/

Why?

**Comment by sclassen** [comment]
Official announcement will be this afternoon. Then also the homepage is updated and the newsletter will be sent

There is a webinar if you care to join.
https://board.karakun.com/viewtopic.php?f=9&t=234

**Comment by filipdimkin** [comment]
This still doesn't seem possible, any news or instructions I'm missing?

**Comment by sclassen** [comment]
https://openwebstart.com/docs/OWSGuide.html#_searching_for_local_jvm
