### ISSUE TITLE
java.lang.ClassNotFoundException Caused by: java.lang.NoClassDefFoundError Caused by: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by elbosso** [karakun/OpenWebStart#359]
Hi, I just stumbled over OpenWebstart auf found it terrific. HoweverI stumbled over an issue i can't get my head around. I have - for historic reasons - many webstart apps lying around. I tested all those and all bar one of them worked. The reason for the failure of the one app is a ClassNotFoundException  related to one of the classes i wrote myself. 

I attached the log and the jar file in question as well as the jnlp (the jar and jnlp inside the attached zip).

What irritates me is that i use this class in several others of the apps that worked and it does not seem to have anything to do with the package either - or with the jar as such as in the app that fails there are some more classes loaded from that jar file - but all those work and it fails at that specific class.

i tested this on an ubuntu 18.04 LTS - i use 
```
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)
```

[sqlshell_jnlp_openwebstart.log](https://github.com/karakun/OpenWebStart/files/5581448/sqlshell_jnlp_openwebstart.log)
[ressources.zip](https://github.com/karakun/OpenWebStart/files/5581451/ressources.zip)

**Comment by sclassen** [comment]
Hi and thanks for trying out OpenWebStart

Unfortunately the log does not contain the stacktrace. But what currently stands out are the following errors:
```
Error flag set for resource 'http://tomcat8:8080/sqls/app/geronimo-stax-api_1.0_spec.jar'. Can not return a local file for the resource
Error flag set for resource 'http://tomcat8:8080/sqls/app/jasper-compiler-jdt.jar'. Can not return a local file for the resource
Error flag set for resource 'http://tomcat8:8080/sqls/app/xml-apis.jar'. Can not return a local file for the resource
```
To get more complete log files could you please open the settings (itw-settings executable in the installation folder, default is /opt/OpenWebStart) then find the logging settings and make sure both debuglevel and log to file are checked.
In the same window you can see the folder where OpenWebStart will write the logfiles into.

Please clean the log folder and run the faulty app. This will produce 1-3 files. Would be great if you could attach them to this issue

**Comment by elbosso** [comment]
Hi, thanks for the feedback. I too saw the lines starting with Error flag set for resource - i fixed my launch.jnlp but to no avail...
I attached the logfiles and took some time out of my lunch break (ahh - the joys of home office)  to comb through it. I saw that the class loader is set on three threads - may this be the root of the problems? 
[2020-11-23_12:12:51.13-ows-stage1.log](https://github.com/karakun/OpenWebStart/files/5582596/2020-11-23_12.12.51.13-ows-stage1.log)
[2020-11-23_12:12:51.13-ows-stage2.log](https://github.com/karakun/OpenWebStart/files/5582597/2020-11-23_12.12.51.13-ows-stage2.log)
[2020-11-23_12:13:44.96-ows-settings.log](https://github.com/karakun/OpenWebStart/files/5582598/2020-11-23_12.13.44.96-ows-settings.log)

**Comment by elbosso** [comment]
I added some more application level logging and attached the resulting logfile  here. mainly I added output to follow my hunch about the classloader...
[2020-11-23_12:38:27.878-ows-stage2.log](https://github.com/karakun/OpenWebStart/files/5582687/2020-11-23_12.38.27.878-ows-stage2.log)

**Comment by sclassen** [comment]
Yes the log files show nothing abnormal. So there is a good chance the error is caused somehow by the application and how it does class loading.
One last thing you could try is to update to the newest OpenWebStart version 1.3.0.
But since we did only very little change on the classloading since 1.2.0 I see the chances for an improvement as very low.

If you need to get this application up and running we can offer more help in combination with one of our support packages.
If you want to debug this yourself I can help you setting up your environment to do so.

**Comment by elbosso** [comment]
Thanks for your feedback and thank you for offering help in tracking the error down. I did some digging on my own and I know now what causes the problem: The root cause seemed to be that a class could not be found. I therefore changed the main program down to one line seeming to cause that problem. Then, I edited the launch.jnlp - eliminating more and more jar files. And at some point - just by removing jar files from the launch.jnlp - the error was gone. I tried to find the exact jar file that seemed to trigger the problem and I found it. What stymied me was that that jar did not contain any class files - it was a jar holding only resources: data files, images,... But then it dawned on me - one of the resources was a jar file. So I had a jar file inside a jar file. And that is where it gets interesting: the inner jar file contained the class file for the class that could not be found. 

That means that such a jar holding another jar confuses the class loader used in OpenWebstart - it is to eager and extracts jars inside jars also and puts their content on the classpath too. In my case - that caused the class in question being there twice - loaded by different classloaders i presume. 

I suggest therefore to correct the class loading behaviour and not to extract the content of jars inside jars.

If you need any more information and the jarfile that caused al this, please dont hesitate to ask...

**Comment by sclassen** [comment]
Interesting finding.
We actually do not do any of the extracting and class loading ourselves but delegate all of it to the UrlClassloader which comes with Java.
OpenWebStart will only provide the UrlClassloader with all the URLs to the jar files (in the local cache) from the JNLP.

**Comment by sclassen** [comment]
Are you able to get your application to run now?
We are currently very low on funding and man power and therefore cannot guarantee any action on this item if it is not critical.

**Comment by elbosso** [comment]
> Interesting finding.
> We actually do not do any of the extracting and class loading ourselves but delegate all of it to the UrlClassloader which comes with Java.
> OpenWebStart will only provide the UrlClassloader with all the URLs to the jar files (in the local cache) from the JNLP.

Well - thats intriguing. Because i started the tests with a war that i had sitting around unchanged since i used it with oracles and then the icedtea webstart implementation - and it did work back then. That would mean the implementation of URLClassLoader has changed since then. Well, maybe when the days get shorter and the weather forecast is bleak I will take a look into that

**Comment by elbosso** [comment]
> Are you able to get your application to run now?
> We are currently very low on funding and man power and therefore cannot guarantee any action on this item if it is not critical.

Yes, actually all I had to do was to rename the inner jar (it now has suffix ".jar_") and the reference to it. That way it is no longer recognized by the classloader and the classes inside it no longer irritate the classloader.

Many thanks again for the support and a great tool! I think you can close this issue now.
