### ISSUE TITLE
ScriptFactory is Reason for .desktop-files not working in (at least) ubuntu 

### ISSUE THREAD

**Issue by elbosso** [karakun/OpenWebStart#363]
* installed via official deb version 1.3 under Ubuntu 18.04
* deployed several webstart applications
* always answered "yes" when asket wether to instlal shortcuts
* shortcuts created on Desktop but not working
* inspection showed that the exec key pointed to a wrong location for the executable: was "/opt/javaws" where a simple "javaws" would have sufficed (after installing via ,deb - javaws is included in the search path PATH
* culprit seems to be com.openwebstart.os.ScriptFactory::createStartScript

**Comment by sclassen** [comment]
Where is the javaws executable installed on your machine?

**Comment by elbosso** [comment]
`which javaws`: _/usr/local/bin/javaws_
`ls -l /usr/local/bin/javaws`: `lrwxrwxrwx 1 root root 24 Nov 23 19:48 /usr/local/bin/javaws -> /opt/OpenWebStart/javaws`

**Comment by sclassen** [comment]
Thanks for reporting this.
We cannot simply take the `javaws` from the path as some users also have Oracle JDKs installed which might have their javaws on the path.

**Comment by elbosso** [comment]
The renaming of the executable in 3.0.0 should resolve the path issue

**Comment by sclassen** [comment]
yes, unfortunately there is no timeline for the 3.0.0 version
