### ISSUE TITLE
When install OpenWebstart 1.2.1 on Windows 10, it will change file permission for all files in C:\Users%USERNAME%.config\icedtea-web\security and C:\Users%USERNAME%.cache\icedtea-web\cache

### ISSUE THREAD

**Issue by alslw** [karakun/OpenWebStart#366]
When install OpenWebStart 1.2.1 on Windows 10 Enterprise by "runAs Administrator" on local machine. It will install OpenWebStart at "C:\Program Files\OpenWebStart" and it will change file permission for all files in C:\Users%USERNAME%\.config\icedtea-web\security and C:\Users%USERNAME%\.cache\icedtea-web\cache, I found OpenWebStart installer remove permission of %USERNAME% user to access all files in these directory and change owner to be "Administrators" group, then %USERNAME% user run OpenWebStart without "RunAs Administrator", it cannot launch all jar files from cache that exist in their home directory. it will show about KeyStor Error "Invalid password" and "Access is denied" in Java Console and popup Windows to Enter password to verify Certificate because %USERNAME% user don't have permission on C:\Users%USERNAME%\.config\icedtea-web\security
![image](https://user-images.githubusercontent.com/12932352/101118652-1d179100-361c-11eb-9976-979de3f4d6d7.png)
![image](https://user-images.githubusercontent.com/12932352/101118700-34ef1500-361c-11eb-8b5b-670639bf2024.png)
If I install OpenWebStart 1.2.1 on Windows 10 Enterprise without "RunAs Administrator", it will install OpenWebStart at "C:\Users\%USERNAME%\AppData\Local\Programs\OpenWebStart" and it can launch all jar files from cache that exist in their home directory.
**Is this expectation for OpenWebStart installer behavior ?**

**Comment by janakmulani** [comment]
Hi,

When your ran the installer what option did you choose for installation mode? Current User or All Users? This will determine the permissions on the .cache and .config folders:

![CurrentOrAllUsers](https://user-images.githubusercontent.com/655389/101773908-6d5a8b80-3b13-11eb-80af-127aa014dbff.PNG)

I am not sure if running the installer itself with "Run as administrator" is required and whether that affects the permission. I have not tried this.

**When install OpenWebStart 1.2.1 on Windows 10 Enterprise by "runAs Administrator"** 

The 64 bit installer installs in C:\Program Files\OpenWebStart

**If I install OpenWebStart 1.2.1 on Windows 10 Enterprise without "RunAs Administrator"**

The 32 bit installer installs in C:\Users%USERNAME%\AppData\Local\Programs\OpenWebStart

So which installer did you use 64 bit or 32 bit?

What installation mode do you want, for only current user of the machine or for all users of the machine?

**Comment by yasao139** [comment]
将文件安装至启动，依然无法运行文件，会提示无访问权限。

**Comment by sclassen** [comment]
Above comment translated by google:
```
After installing the file to startup, the file still cannot be run, and there will be a prompt of no access permission.
```

**Comment by janakmulani** [comment]
I am sorry I cannot understand your reply. Can you please provide step-by-step details to reproduce the issue: For example: 
1. install 32 bit OWS for current user, 
2. start some jnlp file by dbl-clk on it, 
3. leads to no access permission error

**Comment by yasao139** [comment]
I installed OpenWebStart 1.2.1 in win10 home edition, the installation location is C:\Users\(user)\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup, when opening the jnlp file, a pop-up window requires a password, prompting No access

**Comment by sclassen** [comment]
@yasao139 this sounds like a different issue. can you please open a new ticket and describe your case there. also please include a screenshot of the prompt you see

**Comment by yasao139** [comment]
好的，我复现一下安装步骤，并提供故障截图。重新发一个新帖

**Comment by sclassen** [comment]
OK, I will delete the comments in this ticket after you have opened a new issue

**Comment by yasao139** [comment]
Hello, the problem has been solved after I initialized the system. No need to open a new issue, thank you.

**Comment by alslw** [comment]
Hi
We install OWS 1.2.1 in unattended mode for Win 10 (64 bits)  and we don't setting about you mention, then we think it should to be default. we login user to run this installer with "RunAs Administrator".

**Comment by alslw** [comment]
We don't see configuration item about how to set option "For all users" in response file page. Could we install unattended mode with option "For all users" ?  If we could, please tell us how to set it in response file. Could it fix this issue ?

Thanks

**Comment by janakmulani** [comment]
In the response.varfile you could specify the following properties:

userMode$Integer=1  : Install For All Users
userMode$Integer=0  : Install For Current User
---
sys.adminRights$Boolean=false : Run the Installer without admin rights
sys.adminRights$Boolean=true : Run the installer with admin rights
