### ISSUE TITLE
Exiting Boot.mainWithReturnCode() with 0

### ISSUE THREAD

**Issue by griand** [karakun/OpenWebStart#370]
On jre 8+ my applet works fine but I can't to run it on OWS 1.3.1 - ows splash just closed and nothing happens.
I not see any errors in log file excepting **Exiting Boot.mainWithReturnCode() with 0**. 

Actual [JNLP file](https://websocket.yburlan.ru:8443/jnlp/akms0rhlgb4f8eerh321v7k7f3/1590321758272/yburlan.jnlp) for testing.
OS: MacOS BigSur 11.0.1
[Log file](https://gist.github.com/griand/1e928e0a2cb672b30cf9d28a1f444083)

**Comment by Jamila891** [comment]
applets are not supported in OpenWebStart. You would need to migrate to an application.

**Comment by griand** [comment]
> applets are not supported in OpenWebStart. You would need to migrate to an application.

@Jamila891 , thanks for reply, you right, after migrating to application all works fine now.
