### ISSUE TITLE
Non versioned jar files download every time application is launched.

### ISSUE THREAD

**Issue by macgibbon** [karakun/OpenWebStart#371]
Is there a particular format expected for the "Last-Modified" header? 

_HEAD /HD05Portfolio/HD05Portfolio.jar HTTP/1.1
Accept-Encoding: pack200-gzip, gzip
User-Agent: Java/11.0.7
Host: ec2-52-15-32-25.us-east-2.compute.amazonaws.com:8080
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive_

**HTTP/1.1 200 
Last-Modified: Wed, 09 Dec 2020 15:46:10 GMT
Content-Type: application/java-archive
Content-Length: 26888131
Date: Thu, 10 Dec 2020 01:35:58 GMT
Keep-Alive: timeout=20
Connection: keep-alive**

_GET /HD05Portfolio/HD05Portfolio.jar HTTP/1.1
User-Agent: Java/11.0.7
Host: ec2-52-15-32-25.us-east-2.compute.amazonaws.com:8080
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive_

**HTTP/1.1 200 
Last-Modified: Wed, 09 Dec 2020 15:46:10 GMT
Content-Type: application/java-archive
Content-Length: 26888131
Date: Thu, 10 Dec 2020 01:36:00 GMT
Keep-Alive: timeout=20
Connection: keep-alive**

**Comment by sclassen** [comment]
To help you resolve this we need log files.
Please open the OpenWebstart Settings and go to the logging tab.
Make sure that both "debug level" and "log to file" are active.
On the same screen you see the directory where the log files are written to.

We only need the file called xxx-ows-stage2.log

**Comment by macgibbon** [comment]
Thank you for the prompt response, the issue has resolved itself as we updated and migrated our server to Amazon web services.
