### ISSUE TITLE
javaws remains open after application has been closed

### ISSUE THREAD

**Issue by undergraver** [karakun/OpenWebStart#372]
Hi,

I saw the javaws.exe executable is not closed after the application has finished. Do we need to perform something special in our applications in order to make javaws process started by OpenWebStart close properly?

Thanks!

**Comment by sclassen** [comment]
Which OS are you running?

**Comment by undergraver** [comment]
Windows 10, OWS 1.3.0.

**Comment by janakmulani** [comment]
>  application has finished.

Does the app terminate (System.exit) on closing its window?

**Comment by undergraver** [comment]
Not in every case from what I can see. Does this need to be explicitly done?

**Comment by janakmulani** [comment]
Yes. OWS starts a Java process  that runs the application specified in the JNLP file. This application must terminate for the process to terminate. If the app keeps running the process will not terminate. For example, in case of a Swing app closing the main window must call System.exit() or DefaultCloseOperation must be set to JFrame. EXIT_ON_CLOSE. this will ensure that the app and hence the JVM process will terminate thus allowing _OWS javaws_ to terminate.

**Comment by undergraver** [comment]
Thanks for the explanation. It is solved now
