### ISSUE TITLE
OWS stumbles upon password-protected system-defined trusted.certs that should not be used in the first place

### ISSUE THREAD

**Issue by in-fke** [karakun/OpenWebStart#376]
We are having an issue where a system-installed JRE interferes with OWS where we don't want to use the system-installed JRE for OWS.
On the target system, the file
`C:\Windows\Sun\Java\Deployment\trusted.certs`
seems to be password-protected (not "changeit").

Upon verifying jars, or within OWS Settings, we get the following error, prompting us for the password:
"Keystore was tampered with, or password was incorrect"

![image](https://user-images.githubusercontent.com/73228413/104340449-fc830680-54f8-11eb-9e17-dc5f76b28626.png)

In all (?) JVMs (is this per JVM?) the path C:\Windows\Sun\Java\Deployment\ is used!?
Is this some implementation-specific path that's being used by all JVMs?
We tried to "turn off" this path by setting JAVA_HOME pointing to a portable install of Amazon Corretto, but this change had no effect.
Are there any system properties or tweaks available to tell OWS NOT to use 
`C:\Windows\Sun\Java\Deployment\trusted.certs`
?
Where is the (file-based?) configuration to tell OWS which system(?) JRE is to be used!? (JAVA_HOME seemed to have no effect)

Trouble is, we don't have access to the target system so easily (and the user does not have admin rights).

**Comment by sclassen** [comment]
You can try to set a different trust store with the following deployment property:
`deployment.system.security.trusted.certs`

You need to set this in either the global or the user local deployment.properties file

**Comment by in-fke** [comment]
Thank you for the reply. I guess you mean this: https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/properties.html
We will have to have a look at the target system to see how it can be changed.

**Comment by sclassen** [comment]
Yes, there is also a documentation for OpenWebStart about he configuration:
https://openwebstart.com/docs/OWSGuide.html#_configuration
https://openwebstart.com/docs/OWSGuide.html#_configuration_properties_overview

**Comment by in-fke** [comment]
I did not quite understand yet, which files are relevant, we may got two files (besides) the system deployment.properties under windows

1. %USERPROFILE%\.config\icedtea-web\deployment.properties, first line starts with "#Netx deployment configuration"
2. %LOCALAPPDATA%\..\LocalLow\Sun\Java\Deployment\deployment.properties

Neither contained a property deployment.system.security.trusted.certs but the system deployment.properties does:
`deployment.system.security.trusted.certs=C:\\Windows\\Sun\\Java\\Deployment\\trusted.certs`
this points to the troublesome file that is password-protected.

We wonder which of the two is relevant for OWS?
If I don't change anything on a system that does NOT have the "systems" deployment.properties, OWS Settings points to:
c:\users\fke\appdata\local\programs\openwebstart\jre\lib\security\trusted.certs
So I guess this is Java's default, if `deployment.system.security.trusted.certs` is not set at all.

Changing the first file (under .config) DOES affect OWS Settings.
Changing the second file (under LocalLow) does NOT affect OWS Settings.

So I wonder:
1. How does OWS Settings know to use %USERPROFILE%\.config\icedtea-web\deployment.properties ?
2. Is this also the relevant file when running the JRE for the actual application, or does the second file has to be changed as well?

And possibly in a consequence: So is it desirable that OWS Settings / OWS has different deployment.properties than the actual application?

**Comment by sclassen** [comment]
The fiel 2) in LOCALAPPDATA is not read by OpenWebStart.

OpenWebStart will read the file `<Windows Directory>\Sun\Java\Deployment\deployment.config`
If inside this file a deployment.properties is specified then OpenWebStart will load these properties as the system wide property.
See https://openwebstart.com/docs/OWSGuide.html#_system_configuration

The configuration is loaded with the same code and from the same files regardless of the JRE.
But when it comes to the trust stores then the JRE has an influence. OpenWebStart builds a chain of trust stores and will search each one of them until it finds a trusted CA. And the trust store of the JRE is included in this chain, so is the trust store defined in the system properties and the trust store located within %USERPROFILE%.config\icedtea-web\security

**Comment by in-fke** [comment]
Thank you for following up on this topic and for clarifying - we will let you know how it went.

**Comment by in-fke** [comment]
It is now confirmed that changing the first file under
https://github.com/karakun/OpenWebStart/issues/376#issuecomment-767447358
works in order to point to a different trusted.certs file.
