### ISSUE TITLE
Cannot create menu entry for app

### ISSUE THREAD

**Issue by HashRaygoza** [karakun/OpenWebStart#386]
Greetings

I'm getting  a message where Open JavaWebstart cannot find the javaws executable to create the menu entry and the desktop shortcut, where that executable should be to fix this, this happens with both Oracle JRE and Azul JRE.

Thank you

![Captura de pantalla 2021-01-27 11 01 38](https://user-images.githubusercontent.com/19654490/106030602-f7df5600-6093-11eb-8948-9f3788147c79.png)

**Comment by sclassen** [comment]
Judging from the screenshot we assume you are running in a virtual environment.
Can you give us some more details about your setup.

If possible also provide a log file.
https://openwebstart.com/docs/FAQ.html#_does_ows_write_log_files_and_where_do_i_find_them

**Comment by sclassen** [comment]
Is this related to #243

**Comment by sclassen** [comment]
fixed in #393
