### ISSUE TITLE
"prefer https" mechanism should have an "early bail" if HTTPS is not available

### ISSUE THREAD

**Issue by in-fke** [karakun/OpenWebStart#387]
The "prefer https" mechanism should have an "early bail" (or maybe even ave user interaction) if HTTPS is not available.
Otherwise the startup may be awfully slow since for every referenced jar (e.g. 200) https is tried, yet to revert to http every single time.
Also, proxies might answer with 503 confusing the client.
Maybe, OWS could do a single test and if positive, continue with https, continue with the original url (http) otherwise.
In this case, OWS might even be so friendly and pop up a dialag, hinting the user it should use the https in the first place.

**Comment by in-fke** [comment]
"Probing" the Endpoint is related to: https://github.com/karakun/OpenWebStart/issues/226

**Comment by sclassen** [comment]
There is a switch in the settings under "security" to disable the HTTPS first.

**Comment by in-fke** [comment]
I know there is this switch, but the preset (trying https although http was specified in the URL) is also something that can be optimized, like I described above.
I'd prefer not having to tell every user to toggle that switch.

**Comment by sclassen** [comment]
If you are in a corporate environment there is the possibility of unattended installations where you can set some config at installation time.
There is also the possibility to have a global config which is loaded from a server.
If you need more details on these options please come back to us.

**Comment by in-fke** [comment]
That is really nice of you wanting to help with unintended install. My Issue is about improving OWS as a product in the way it works „out of the box“ without having to change the default configuration.

My suggestion for HTTP URLs would be: 
Probe the JNLP URL for HTTPS - if that does not work, don‘t try „preferring“ HTTPS for any other URL.

**Comment by sclassen** [comment]
We discussed this in the team and came to the conclusion that we value security over usability in this case.
Thank you for your suggestion and your interest in OpenWebStart.
