### ISSUE TITLE
application crashes during the start with openwebstart but with the latest version of iced tea it works well

### ISSUE THREAD

**Issue by JoergW24** [karakun/OpenWebStart#399]
We have an application that crashes during the start with openwebstart (latest version 1.3.3) but it works well with the latest version of iced tea (1.8.4 - https://adoptopenjdk.net/icedtea-web.html). I can't found a reason for the problem in the log.
The application is here: http://mulco2.gwj.de/calculation/jnlp_de/power/MulcoPower.jnlp or an other application here https://www.eassistant.eu/fileadmin/dokumente_web/eassistant/jnlp/ShaftDim.php?lang=de

Best regards
Joerg

**Comment by sclassen** [comment]
OpenWebStart does no longer support applets.
You will need to change this from an applet to an application if you want to use OpenWebStart
