### ISSUE TITLE
 Property 'ows.install4j.propertyUpdate' is unknown.

### ISSUE THREAD

**Issue by theBiggerKnows** [karakun/OpenWebStart#403]
Getting this error when trying to start up:

[ITW-CORE][2021-03-08 13:22:54.265 EST][INFO ][net.sourceforge.jnlp.config.DeploymentConfiguration] Loading USER level properties from: file:/Users/maya/.config/icedtea-web/deployment.properties
[ITW-CORE][2021-03-08 13:22:54.270 EST][INFO ][net.sourceforge.jnlp.config.DeploymentConfiguration] Property 'ows.install4j.propertyUpdate' is unknown.

**Comment by sclassen** [comment]
Fixed the issue.
But this was only a "unnecessary" log line. Nothing that would stop your application from running
