### ISSUE TITLE
Ubuntu 20.04 - Desktop icon no longer works

### ISSUE THREAD

**Issue by HannahBrown** [karakun/OpenWebStart#406]
I recently upgraded from Ubuntu 18 to Ubuntu 20. On Ubuntu 18, the desktop icon works as expected. However, on Ubuntu 20, nothing happens when I click on the icon, and I am not allowed to select 'OpenWebStart' to run the application. Additionally, a '.desktop' file ending is added to the application name, and the custom icon does not show up (it shows a default system icon instead).

Running the .jnlp directly still works as expected.

**Comment by sclassen** [comment]
Can you try to delete and recreate the desktop shortcut?

**Comment by HannahBrown** [comment]
I ensured I have the latest version of OWS, deleted the shortcut, and readded it. The same thing happened.

**Comment by sclassen** [comment]
Can you attach the file to this issue.
Also can you paste the output of `ls -la` on the file.

**Comment by HannahBrown** [comment]
I removed the file location, for security reasons. If you need it, please give me a secure location to send it. Also, I needed to zip it because github does not accept that file type.
[fulcrum.zip](https://github.com/karakun/OpenWebStart/files/6118255/fulcrum.zip)
![Screenshot from 2021-03-10 13-02-22](https://user-images.githubusercontent.com/8837759/110682808-fc258580-81a0-11eb-9979-11f237b15335.png)

**Comment by sclassen** [comment]
Sorry for the delay.
I tried to reproduce this on my Kubuntu 20.04 LTS with one of our demo apps.
Unfortunately I failed to do so.
Here the output from my machine:

```
~/Desktop $ ls -la
total 16
drwxr-xr-x  2 scl scl 4096 Mär 18 22:33 ./
drwxr-xr-x 41 scl scl 4096 Mär 18 21:49 ../
-rw-r--r--  1 scl scl   50 Nov  2 13:20 .directory
-rwx------  1 scl scl  311 Mär 18 22:31 demo.desktop*
```

```
~/Desktop $ cat demo.desktop 
[Desktop Entry]
Version=1.0
Name=Demo Application
GenericName=Java Web Start Application
Comment=
Type=Application
Icon=/home/scl/.config/icedtea-web/icons/47306333-f1b7-490d-8bd2-9a35553bce1c
X-Vendor=Karakun AG
Exec="/opt/OpenWebStart/javaws" "<url of jnlp>"
```

This might be an Gnome issue (I have KDE).
Can you please checkout this https://askubuntu.com/questions/1237042/desktop-files-not-launching-from-desktop-in-ubuntu-20-04-lts

If you are able to get it to run I would appreciate if you can report back what changes you made to the file.
Then we can implement a fix for the next OWS version.

**Comment by HannahBrown** [comment]
Using this: https://askubuntu.com/a/1237057, I selected 'Allow launching'. It now works. Thank you for your help.
