### ISSUE TITLE
Cannot unattend install if no user is logged in

### ISSUE THREAD

**Issue by filipdimkin** [karakun/OpenWebStart#407]
Hi team,

I'm currently deploying OpenWebStart via SCCM to various workstations and I've run into an issue where if no user is logged into the machine and the install is triggered it won't succeed, however if a user is logged in and the deployment triggers the installation works fine.

Command is: openwebstart_windows_x64_1_2_1.exe -q -varfile response.varfile

Copy of my response file can be seen below, any ideas? Is there any way of enabling logging in the command seen above?

# install4j response file for OpenWebStart 1.2.1
installationDate$Long=1605519424448
sys.adminRights$Boolean=true
sys.fileAssociation.extensions$StringArray="jnlpx"
sys.fileAssociation.launchers$StringArray="313"
sys.installationDir=C\:\\Program Files\\OpenWebStart
sys.languageId=en
userMode$Integer=1
ows.jvm.manager.customSearchLocation=C:\\Program Files\\Java\\jdk-11.0.8\\bin\\server
ows.jvm.manager.updateStrategy=NO_REMOTE
deployment.proxy.type=0
deployment.log.file=true
deployment.javaws.shortcut=NEVER

**Comment by eduni** [comment]
Hi,

have you found any solution for this?

We have the same problem with deploying OWS with SCCM.
Installation is fine if triggered manually through Software Center but not installed automatically.
The difference i could find the install4j log:

`[1:52] tempFile is C:\Windows\TEMP\e4j3E08.tmp
[1:692] Exit Code 1
[1:693] couldn't get version`

whille it says

`[0:907] tempFile is C:\WINDOWS\TEMP\e4j4285.tmp
[1:394] Exit Code 0
[1:395] Java version: 1.8.0_292`

in the working version.
