### ISSUE TITLE
deployment.manifest.attributes.check is ignored in response.varfile

### ISSUE THREAD

**Issue by RedPeace** [karakun/OpenWebStart#408]
Hi,

deployment.manifest.attributes.check is ignored in response.varfile

So the generated deployment.properties does not include the value.

Greetings.
Gero

**Comment by sclassen** [comment]
Can you please post your `response.varfile`

**Comment by RedPeace** [comment]
Sure:

---------
# install4j response file for OpenWebStart 1.3.3
deployment.assumeFileSystemInCodebase=true
deployment.proxy.bypass.local=true
deployment.proxy.http.host=53.100.33.248
deployment.proxy.http.port=8080
deployment.proxy.same=true
deployment.proxy.type=1
installationDate$Long=1615399951040
ows.checkUpdate=false
ows.checkUpdate.locked=true
ows.jvm.manager.maxDaysUnusedInJvmCache=999
ows.jvm.manager.maxDaysUnusedInJvmCache.locked=true
ows.jvm.manager.server.allowFromJnlp=true
ows.jvm.manager.server.default=https\://DEACTIVATED
ows.jvm.manager.updateStrategy=AUTOMATICALLY_DOWNLOAD
ows.update.activated=false
ows.update.activated.locked=true
ows.update.strategy.launch=NEVER
ows.update.strategy.launch.locked=true
ows.update.strategy.settings=NEVER
ows.update.strategy.settings.locked=true
sys.adminRights$Boolean=true
sys.fileAssociation.extensions$StringArray="jnlp","jnlpx"
sys.fileAssociation.launchers$StringArray="313","313"
sys.installationDir=C\:\\Program Files\\OpenWebStart
sys.languageId=de
userMode$Integer=1
---------

If i add:

deployment.manifest.attributes.check= CODEBASE,TRUSTED,ENTRYPOINT,PERMISSIONS

to the response.varfile this line is not taken over in the user deployment.properties

Greetings!
Gero

**Comment by sclassen** [comment]
ok, everything looks good so far.
Do you add the line before or after you installed OWS?

**Comment by RedPeace** [comment]
I've added the Line after update from 1.2.2 to 1.3.0.
Now we have 1.3.3

**Comment by sclassen** [comment]
ok, and how do you update?
Are you using the auto update functionality or do you download the new installer and run it with `<OpenWebStart_windows_Setup.exe> -q -varfile response.varfile` ?

**Comment by RedPeace** [comment]
Hmm. Honestly i have only updated with doubleklick the installer .exe file...

For claryfing.

We have a server 2019 TS farm based on Citrix XenApp.
If a user start an java application, a deployment.properties file is automatic generated and stored in %userprofile%\.config\icedtea-web

In this deyployment.config user file all values i've added to response.varfile in the OWS main install directory
-----
deployment.proxy.http.host=53.100.33.248
deployment.proxy.http.port=8080
deployment.proxy.same=true
deployment.proxy.type=1
------
are added.

Except the "deployment.manifest.attributes.check= CODEBASE,TRUSTED,ENTRYPOINT,PERMISSIONS" line.

**Comment by sclassen** [comment]
Yes this is true for the first time a user starts the application. If the user starts OWS the second time a deployment.properties already exists. OWS then goes and compares the timestamp in the deployment.properties and the timestamp in the response.varfile and only updates the deployment.properties if the response.varfile is newer.
The timestamp in the response.varfile is in the key 'installationDate$Long', in the deployment.properties it is `ows.install4j.propertyUpdate`.


For Citrix environment there is another approach you can take to distribute settings to all users:
https://openwebstart.com/docs/OWSGuide.html#_system_configuration

A system configuration allows to tune the settings for all users and even lock certain settings to prevent an overwrite by the user.

**Comment by RedPeace** [comment]
Thank you for the hint with "System Configuration"!
I'will give this a try.

I suspect a combination of "System Configuration" and "Customize Application Cache and User Config Location" makes no sense, right? Correct is to use either system or customize with environment variables?

**Comment by sclassen** [comment]
It is no problem to mix and match system config and customized cache and config location.
but I would avoid sharing the application cache between multiple users (you can share the JVM cache if you need this)

**Comment by RedPeace** [comment]
Thank you.

Last question:
Is it possible to activate logging per user or only global?
We have some users where applications wont start. Noting happens, no window etc. Only the OWS splash screen is showing for some seconds and then nothing further happens. We can see java.exe, javaw.exe and javaws.exe processes in taskmanager hanging.
If we kill the processes and delete user cache directory the applications can be startet and are running fine.

**Comment by sclassen** [comment]
By default there is a per user config in %userHome%\.config\icedtea-web folder.
So you can turn logging to file and debug logging on and off for each and every user.
Docu about logging is here: https://openwebstart.com/docs/OWSGuide.html#_logging

**Comment by RedPeace** [comment]
Thank you!
