### ISSUE TITLE
Could not launch second JNLP file on Mac OS

### ISSUE THREAD

**Issue by rsnw** [karakun/OpenWebStart#41]
Using the following: 
        •      OpenWebStart 0.3.2
	•	Mac OS 10.14.5
	•	Tested with both of the following JVM’s:
	     ⁃	1.8.0_212 Oracle Corporation
	     ⁃	1.8.0_212 BellSoft

Issue:
	•	JNLP files launch without issue with Oracle WebStart
	•	1st JNLP file launches without issue with OpenWebStart 0.3.2
	•	2nd JNLP file fails without error

After second JNLP file is launched, the debugging log is:
[name][ITW-JAVAWS-CLIENT][ERROR_ALL][Mon Sep 30 16:34:22 PDT 2019][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 480bdb19, name AWT-EventQueue-0:     at net.adoptopenjdk.icedteaweb.launch.JvmLauncherHolder.setLauncher(JvmLauncherHolder.java:44)
[name][ITW-JAVAWS-CLIENT][ERROR_ALL][Mon Sep 30 16:34:22 PDT 2019][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 480bdb19, name AWT-EventQueue-0: Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: JvmLauncher already set. 
[name][ITW-JAVAWS][MESSAGE_ALL][Mon Sep 30 16:34:22 PDT 2019][com.openwebstart.launcher.OpenWebStartLauncher] NETX Thread# 480bdb19, name AWT-EventQueue-0: ITW Boot called with custom OwsJvmLauncher and args [-verbose, -jnlp, /Applications/OpenWebStart/application1.jnlp, /Users/name/Desktop/application2.jnlp].

**Comment by sclassen** [comment]
solved by #36
