### ISSUE TITLE
How to disable auto shortcut in response file of OWS ?

### ISSUE THREAD

**Issue by alslw** [karakun/OpenWebStart#410]
I try to install OWS ver 1.2.1 on Win10 (64bits) in Unattended Installation and want to disable auto shortcut from jnlp by adding line "deployment.javaws.shortcut=NEVER" into response file and create shortcut from script to load our jar file but it did not work.
After I install OWS in Unattended Installation and check C:\Users\<user name>\.config\icedtea-web\deployment.properties, I don't see this line. **How to disable auto shortcut in response file of OWS ?**
<img width="620" alt="disable_auto_shortcut" src="https://user-images.githubusercontent.com/12932352/112296374-6e30bb00-8cc7-11eb-8c89-7addb2679536.png">

**Comment by sclassen** [comment]
This is currently not possible as we are not grabbing all of the properties which can potentially exist.

**Comment by janakmulani** [comment]
@alslw We will fix this in the next release

**Comment by sclassen** [comment]
fixed in #417
