### ISSUE TITLE
OwsJvmLauncher.java cannot find local java runtime to load jar file

### ISSUE THREAD

**Issue by alslw** [karakun/OpenWebStart#416]
Hi
  I am not sure this is issue or not. **Could you advise this ?** I install OWS 1.3.3 on Win 10 (64 bits) and I try to use OWS to load local jar on local drive by setting jnlp file and json as following
<img width="819" alt="jnlp_json_cfg" src="https://user-images.githubusercontent.com/12932352/115331194-abea0c00-a1bf-11eb-8ea8-d234518615a2.png">
When I try to use OWS to load jar from local jnlp file, there are some error about "No suitable JVS was found to start the application" in OwsJvmLauncher.java (line 81) as show in the picture in below.
<img width="885" alt="error_loadlocal_jar" src="https://user-images.githubusercontent.com/12932352/115331582-5d893d00-a1c0-11eb-92e5-387375f43719.png">
Line 81 of OwsJvmLauncher.java:
<img width="560" alt="Line81OwsJvmLauncher" src="https://user-images.githubusercontent.com/12932352/115332454-0b491b80-a1c2-11eb-8f9c-a01e85ffdadc.png">
Then, I check log of this error and it show message "No local runtime found, will try to find remote runtime" when it try to find this runtime in "file:/C:/Users/Public/[CompanyName]/RTA/jvms/jvms.json", please see the picture in below.
<img width="891" alt="ows_logOfload_jar_fail" src="https://user-images.githubusercontent.com/12932352/115332030-439c2a00-a1c1-11eb-8752-27220e79ac44.png">

**Comment by sclassen** [comment]
Have you enabled server URL from the JNLP file in the settings of the JVM Manager?

**Comment by alslw** [comment]
Hi
    This is deployment.properties file of this error.
<img width="445" alt="deployment_propertyOfLoadlocaljarissue" src="https://user-images.githubusercontent.com/12932352/115487547-1c0d9600-a283-11eb-895c-7dba4917c0e5.png">

**Comment by sclassen** [comment]
You are missing
`ows.jvm.manager.server.allowFromJnlp=true`

**Comment by alslw** [comment]
Hi
     I try to set "ows.jvm.manager.server.allowFromJnlp=true" as you mention but it still fail the same error.
<img width="907" alt="ows_offline_issue01" src="https://user-images.githubusercontent.com/12932352/115653481-724d0880-a359-11eb-9e96-6c361b1465b3.png">
<img width="904" alt="ows_offline_issue02" src="https://user-images.githubusercontent.com/12932352/115653828-1931a480-a35a-11eb-8213-cdd092368672.png">

**Comment by sclassen** [comment]
Sorry we only support HTTP requests for the `jvm.json`.
Since all your JVMs are located on you comupter (the href in the json all start with file://) you could simply install these and then use the JVM manager to select/import them.

If you are trying to setup a corporate solution for managing/deploying to a larger number of clients then please contact us openwebstart@karakun.com

**Comment by alslw** [comment]
Hi
     I think you mean manual to install jvm and use JVM manager to import them but there are some question.
How must I change jnlp file and deployment.properties to load jar and jvm from local ?

**Comment by sclassen** [comment]
There is only little effort to do this.
First you need to import the locally installed JVMs into the JVM Manager. This can either be done in the settings UI or automatically at using some settings. See https://openwebstart.com/docs/OWSGuide.html#_searching_for_local_jvm

Once this is done all that is left is to have the JNLP request a JVM which is locally installed. You can see the version and the vendor of all JVMs known to the JVM Manager in the settings UI.

If you want you can also disable the downloading of JVMs from the internet. Simply choose "Do not download" as the update strategy of the JVM Manager.

**Comment by alslw** [comment]
Hi
     I try to follow step as you mention but It still show the same error "No suitable JVS was found to start the application".
I check in log file it show java api function "com.openwebstart.jvm.LocalRuntimeManager" cannot find local jvm runtime. Please see the picture in below. Could you advise this ?
<img width="908" alt="OWS_CannotFindLocalJVM" src="https://user-images.githubusercontent.com/12932352/117283229-ca265c00-ae8f-11eb-8754-aa001d9d8818.png">

**Comment by sclassen** [comment]
ok, i think the problem is that OWS does not recognize `amazon corretto` as only amazon is the vendor and corretto is the name of their jvm build.
Can you change this in the JNLP to be only `amazon` or `amazon inc.`

**Comment by sclassen** [comment]
or to be on the save side use `Amazon.com Inc.` as this is the value displayed in the JVM Manager.
This value is read from the JVM and outside of our control. We have some basic logic to recognize different names of the same vendor but can never guarantee 100% coverage

**Comment by sclassen** [comment]
A list of all valid vendor names can be found at https://openwebstart.com/docs/OWSGuide.html#_specify_a_specific_vendor_in_the_jnlp_file
