### ISSUE TITLE
JVM versioning, updating and compatibility consideration

### ISSUE THREAD

**Issue by maniel** [karakun/OpenWebStart#429]
Currently OWS is trying to upgrade my installation of JRE (Java 8) to absoluty newest version, which is, at the time of writing this issue, Java 11. In many cases it causes some compatibility problems. Please consider option for updating without raising Java version, for example suggest an update from jre8.0.265 to jre8.0.292 not jre11. As far as I know would be consistent with Oracles updater update policy (it didn't suggest upgrading from java 8 to java 9back when i was using it) also it's how Java packages are managed in many distributions (for example Ubuntu has openjdk-11-jre and openjdk-8-jre packages to prevent automatic update to potentially incompatible version)

**Comment by sclassen** [comment]
This can be done in the JNLP by setting the version to `1.8*` which defines that the application should be run with an Java 1.8 and nothing else

**Comment by maniel** [comment]
local copy of jnlp, it's not my app

**Comment by maniel** [comment]
thanks, it works, but as you pointed out it could be potentially problematic workaround, i imagine the update policy i suggested may be beneficial for a only small part of OWS users, we use only couple of apps which work best on java 8 but we want to have most up to date java 8 too

**Comment by sclassen** [comment]
Best is to ask the app devs to update their JNLP or to offer two versions (one for 1.5-1.8 and one for 9+)
