### ISSUE TITLE
java3d

### ISSUE THREAD

**Issue by douglaslyon** [karakun/OpenWebStart#433]
Hi All,
I have been able to get Java3D to run on a mac using oracle webstart.
Openwebstart, for some reason, does not work.
A video of the issue is seen here:
https://vimeo.com/568975294
Thanks!
 - Doug

**Comment by AndreasEhret** [comment]
when looking at the .jnlp in your video, you have specified Java9 VM arguments but want to run on Java 1.8. Can you try the following: change your java version from 1.8+ to 1.8* (means anything at or higher than 1.8 but less than Java 9).
1.8+ means anything 1.8 or higher (including 1.8, 9 or 11). And remove the Java9 VM args, they do not make sense when you run it with JVM 1.8.

In your video when you click away the OWS Error Message dialog, at video position 01.02), you can see in the console log window in the background two red error messages "External launch error: Could not launch JNLP file. (Can not specify Java9 JVM args with Java 1.8: ...").

**Comment by douglaslyon** [comment]
Hi Andreas,
Thank you for your kind attentions!
Your point is well taken, I have modified the jnlp, as suggested, and new errors emerged;
https://vimeo.com/569322355
Illustrated the issue.
Not sure, but is ows ok with nested jnlps loading JNA-based resources? If that is an unimplemented feature
it might account for the error that I am seeing. Any ideas you might have are much-appreciated.
Thanks!
 - Doug

**Comment by sclassen** [comment]
Hi

We were able to run the Gears demo from https://jogamp.org/jogl-demos/www/
This is not exactly the same app as you show in the video.

Can you post a link to your application for us to try it out.
Thanks

**Comment by douglaslyon** [comment]
Hi And thank you for your prompt response.

I have been playing around with OpenWebstart more to determine what 
could the problem be.

Here is what works:
https://www.docjava.com/book/cgij/code/jnlp/joglquad.jnlp
https://www.docjava.com/book/cgij/code/jnlp/j3d.examples.boids.Main.jnlp

Here is what does not work:
https://www.docjava.com/book/cgij/code/jnlp/j3d.examples.ballGrid.Main.jnlp

The stuff that works uses:
<extension name="Java3D"  href="jogl.jnlp"></extension>

The stuff that does not work uses:
<extension name="Java3D"  href="jogl.jnlp"></extension>

The stuff that does not work says there is no java3d in the path, but 
the stuff that works has no such compliant.

Investigation continues...I must be doing something dumb...

Thank you for your efforts!
Regards,
  - Doug

**Comment by douglaslyon** [comment]
Just as a follow-up;
The failure appears in:
javax.media.j3d.MasterControl.loadLibraries(MasterControl.java:888)
as illustrated below.
    /** 

      * Method to create and initialize the rendering Pipeline object, 

      * and to load the native libraries needed by Java 3D. This is 

      * called by the static initializer in VirtualUniverse 
<i>before</i>
      * the MasterControl object is created. 

      */
     static void loadLibraries() {

So, we are failing during a load, but only on OWS....Are we correctly 
mapping to the dylib files?

cp libJ3D.jnilib libJ3D.dylib
cp libJ3DAudio.jnilib libJ3DAudio.dylib
cp libJ3DUtils.jnilib libJ3DUtils.dylib

Is the fix for those who do a manual installation.

Thanks!
  - Doug

P.S. Error detail follows


net.sourceforge.jnlp.LaunchException: Fatal: Launch Error: Could not 
launch JNLP file. The application has not been initialized, for more 
information execute javaws/browser from the command line and send a bug 
report.
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:408)
	at net.sourceforge.jnlp.Launcher.access$200(Launcher.java:70)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:654)
Caused by: java.lang.reflect.InvocationTargetException
	at 
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native 
Method)
	at 
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at 
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:401)
	... 2 more
Caused by: java.lang.UnsatisfiedLinkError: no J3D in java.library.path: 
[/Users/lyon/Library/Java/Extensions, /Library/Java/Extensions, 
/Network/Library/Java/Extensions, /System/Library/Java/Extensions, 
/usr/lib/java, .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at javax.media.j3d.MasterControl$22.run(MasterControl.java:891)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javax.media.j3d.MasterControl.loadLibraries(MasterControl.java:888)
	at javax.media.j3d.VirtualUniverse.<clinit>(VirtualUniverse.java:233)
	at j3d.utils.Gutils.getCanvas3D(Gutils.java:74)
	at j3d.examples.cube.gui.CubePanel.<init>(Main.java:48)
	at j3d.examples.cube.gui.Main.main(Main.java:32)
	... 7 more

**Comment by douglaslyon** [comment]
Hi All,

Java3d problem is solved with a work-around (just figured this out!).
https://vimeo.com/573344484

It is all about the JVM. not sure which ones work, yet.

Thanks!
  - Doug

**Comment by douglaslyon** [comment]
Hi All,
I know now why OWS is failing;

Hi Riley,
Here is why OWS works on select JVMS:
pwd
/Library/Java/JavaVirtualMachines
mini{lyon}38: find . | grep jogl
./jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/jogl-all-android-natives-macosx-universal.jar
./jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/jogl-all-mobile-natives-macosx-universal.jar
./jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/jogl-all-natives-macosx-universal.jar
./jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/jogl-all-noawt-natives-macosx-universal.jar
./jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/jogl-cg-natives-macosx-universal.jar
./jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/jogl-natives-macosx-universal.jar
./jdk1.8.0_51.jdk/Contents/Home/jre/lib/ext/jogl-all-android-natives-macosx-universal.jar
./jdk1.8.0_51.jdk/Contents/Home/jre/lib/ext/jogl-all-mobile-natives-macosx-universal.jar
./jdk1.8.0_51.jdk/Contents/Home/jre/lib/ext/jogl-all-natives-macosx-universal.jar
./jdk1.8.0_51.jdk/Contents/Home/jre/lib/ext/jogl-all-noawt-natives-macosx-universal.jar
./jdk1.8.0_51.jdk/Contents/Home/jre/lib/ext/jogl-cg-natives-macosx-universal.jar
./jdk1.8.0_51.jdk/Contents/Home/jre/lib/ext/jogl-natives-macosx-universal.jar

The JOGL was already installed on those jvms, so OWS worked.

OWS is NOT loading the JOGL extensions the way jdk1.8 JAWS is.

Not sure why OWS will not load the JOGL extensions...but it is now
a little bit more clear what is going on.

Any ideas what the problem might be?

Thanks!
  - Doug

**Comment by douglaslyon** [comment]
Hi All,
After a bit of a deep dive I suspect a bug in the way in which native
methods are loaded. OWS is not finding native methods in Jar files, 
while the proprietary version of JWS is working fine.

Debugging this properly will require that I identify
exactly where JWS is different from OWS when loading native methods.

Is there someone who is knowledgeable in this area?

Thanks!
  - Doug

**Comment by sclassen** [comment]
We do have some knowledge of the code which loads the native libraries. So please ask any question you have here.

**Comment by douglaslyon** [comment]
The multithreaded load for the extensions are not being loaded in time:

https://vimeo.com/576823818

This leads to inconsistent errors (a race condition).

  - Doug
