### ISSUE TITLE
Cannot build project because Bintray is not available anymore

### ISSUE THREAD

**Issue by ingokegel** [karakun/OpenWebStart#436]
A project import in IntelliJ IDEA fails with 

    Could not find artifact net.adoptopenjdk:icedtea-web-all-dependencies:pom:2.0.0-SNAPSHOT in jcenter (https://jcenter.bintray.com/)

**Comment by sclassen** [comment]
Yes, there are currently no JARs for ITW in any repository. You need to check out the source and build the jar yourself

https://github.com/AdoptOpenJDK/IcedTea-Web
