### ISSUE TITLE
More information about jnlpx

### ISSUE THREAD

**Issue by btreut** [karakun/OpenWebStart#439]
as far as I can understand the jnlpx mime type has been added to allow for a parallel installation of Java Webstart and OpenWebstart and targetting each one of both directly. But this information cannot be found in the documentation (at least searching for jnlpx does not find anything except two occurrences in examples). There is a hint in the feature list, explaining, what I have rephrased in my first sentence. 

I think there should be some more information available about jnlpx (especially since it appears to be a dstinct feature of OpenWebstart).

**Comment by janakmulani** [comment]
Thanks for pointing this out. We will update the documentation.

**Comment by AndreasEhret** [comment]
I've started a PR  #440 with some information on .jnlpx and JWS/OWS in parallel in the FAQs. @janakmulani @sclassen feel free to add some more noteworthy details on this topic

**Comment by AndreasEhret** [comment]
FAQ and Guide updated on noteworthy details on .jnlpx and system config specific diffs between OWS and JWS.

**Comment by btreut** [comment]
Merci Vielmals
