### ISSUE TITLE
certificate of java.exe and javaw.exe in C:\Program Files\OpenWebStart\jre\bin is expired

### ISSUE THREAD

**Issue by alslw** [karakun/OpenWebStart#442]
Hi 
    We install OWS 1.3.3 on Windows 10 (64 bits) at 23/07/2021 and we check certificate of java.exe and javaw.exe after install OWS 1.3.3 in folder C:\Program Files\OpenWebStart\jre\bin and we found it is expired at 08/09/2020. Could it impact OWS to process jar file? and Does it require to update certificate of OWS installer ? Please see the picture in below.
<img width="573" alt="OWS_cert_Expired" src="https://user-images.githubusercontent.com/12932352/127595853-bb3b2364-dc1b-4367-b9e5-553d75f0fe43.png">

**Comment by AndreasEhret** [comment]
These certificates are from the underlying JDK, so we cannot do anything here. In 1.4.0 we have upgraded the internally bundled JRE, so could you give it a try?
