### ISSUE TITLE
Error "Could not determine codebase host for resource at file:/<location of local jar file> while generating URLPermissions"

### ISSUE THREAD

**Issue by alslw** [karakun/OpenWebStart#446]
Hi
We install OWS 1.3.3 on Windows 10 (64bits) and try to load local jar file by set codebase in jnlp file to be local drive that keep jar file and other resource file. When we try to load jar file from local jnlp file by command "C:\Program Files\OpenWebStart\javaws.exe" "C:\temp\RTA_installer_offline\scripts\RTA\jar\RTA.jnlp", it show popup Windows to confirm to load local jar file and show error "Could not determine codebase host for resource at file:/[location of local jar file] while generating URLPermissions" in OWS log but it can load our jar when we confirm to load local jar file in Windows popup. 
**Could we suppress Windows popup and this error when we load jar file ?** Please see this example error at the picture in below.
<img width="757" alt="load_local_jar_error" src="https://user-images.githubusercontent.com/12932352/129316342-d2e638fe-4565-482e-ad60-cf75ce30984c.png">

**Comment by FelixJongleur42** [comment]
The file URI scheme usually has three slashes:
https://en.m.wikipedia.org/wiki/File_URI_scheme
see examples.
Maybe it would help to make it a file URI in the first place, or there is an internal error constructing it.

**Comment by alslw** [comment]
Hi
     I try to change codebase="file:///C:/temp/RTA_installer_offline/scripts/RTA/jar" in jnlp file, it can suppress windows popup but it still show error "Could not determine codebase host for resource at file:/<location of local jar file> while generating URLPermissions" in OWS log.   
**Would you have any advise for this error ?**

**Comment by sclassen** [comment]
Try 2 slashes.
This should fix the URI parse error.

**Comment by FelixJongleur42** [comment]
https://en.wikipedia.org/wiki/File_URI_scheme#How_many_slashes?
Have you tried:
`codebase="file://localhost/C:/temp/RTA_installer_offline/scripts/RTA/jar"`

Someone should problaby have a look at:
https://github.com/AdoptOpenJDK/IcedTea-Web/blob/668cbca58d7c62992c4669157ad5b1634172871a/core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/security/SecurityDesc.java#L401
for the case it's a file URL!?

**Comment by alslw** [comment]
Hi 
    Thanks, When I try to use codebase="file://localhost/C:/temp/RTA_installer_offline/scripts/RTA/jar" , It can suppress windows popup and this error and it can work for now. 
However, when I try to use codebase="file://C:/temp/RTA_installer_offline/scripts/RTA/jar", it will show error "net.sourceforge.jnlp.LaunchException: Fatal: Launch Error: Could not launch JNLP file. The application has not been initialized, for more information execute javaws/browser from the command line and send a bug report." in OWS log. See the picture in below.
<img width="806" alt="two_slashes_error" src="https://user-images.githubusercontent.com/12932352/129668590-32440316-4591-446e-af05-f27046cd8faa.png">
