### ISSUE TITLE
Slow download of resources via https

### ISSUE THREAD

**Issue by sehenst** [karakun/OpenWebStart#448]
With Open Webstart 1.4.0 it takes us around 30 seconds to download 115 resource files (89,5 MB in total). Caching has been enabled.

I've tried to increase
```
deployment.cache.parallelDownloadCount=24
```
but that doesn't seem to improve the download time. 

Are there any other options that I can try?

**Comment by sclassen** [comment]
Does your JNLP contain `http` or `https` resources?
You should see this in the attribute `codebase` in the `<jnlp>` tag

**Comment by sehenst** [comment]
We use `https`. 

```
<?xml version="1.0" encoding="UTF-8"?><jnlp codebase="https://..." version="...">
    <information>
        <title>...</title>
        <description>...</description>
        <vendor>...</vendor>
        <homepage href="http://..."/>
        <icon href="icon.ico" kind="shortcut"/>
        <icon href="splash.jpg" kind="splash"/>
        <offline-allowed/>
        <shortcut online="true">
            <desktop/>
            <menu submenu="..."/>
        </shortcut>
    </information>
    <security>
        <all-permissions/>
    </security>
    <update check="always" policy="always"/>
    <resources>
        <j2se version="11+"/>
        <property name="jnlp.versionEnabled" value="true"/>
        <jar href="..." main="true" version="..."/>
        <jar download="lazy" href="..." version="..."/>
        // long list of .jar resources
    </resources>
    <application-desc main-class="..."/>
</jnlp>
```

**Comment by sclassen** [comment]
Ok, in that case it is best to create a debug log and either attach it here or send it to openwebstart@karakun.com.
Check out the guide and faq for instructions about creating log files https://openwebstart.com/support/

Also mention the github issue in any mail to help us relate things between channels

**Comment by sehenst** [comment]
[ows_log.zip](https://github.com/karakun/OpenWebStart/files/7019905/ows_log.zip)

**Comment by sclassen** [comment]
Thanks for the log.
So far every looks OK. The cache is working as expected as only the JNLP and a singel JPG is downloaded. All the jars are fetched from the local cache. This explains why increasing the number of parallel downloads does not help as there are only two files downloaded.

Unfortunately the log file you sent does not include timestamps. Maybe they will give a hint where the 30 seconds are spent.

We recommend logging to files as this will always include the time stamps. If you prefer the OWS console you can use the "show Details" button to configure the information shown for every log line.

**Comment by sehenst** [comment]
> We recommend logging to files as this will always include the time stamps

Ah, I did not know that. Thanks for the info. Here are some new logs.

[ows_logs.zip](https://github.com/karakun/OpenWebStart/files/7020714/ows_logs.zip)

**Comment by sehenst** [comment]
I see this pattern in the log for all resources:

```
...
[ITW-CORE][2021-08-20 11:35:55.452 CEST][DEBUG][net.adoptopenjdk.icedteaweb.resources.ResourceTracker] Will add resource 'fop.jar'
[ITW-CORE][2021-08-20 11:35:55.452 CEST][DEBUG][net.adoptopenjdk.icedteaweb.resources.ResourceHandler] Will check and maybe put into cache: fop.jar
[ITW-CORE][2021-08-20 11:35:55.452 CEST][DEBUG][net.adoptopenjdk.icedteaweb.resources.ResourceHandler] Download for fop.jar has not been started until now
[ITW-CORE][2021-08-20 11:35:55.452 CEST][DEBUG][net.adoptopenjdk.icedteaweb.resources.ResourceHandler] Checking download state of fop.jar
[ITW-CORE][2021-08-20 11:35:55.452 CEST][DEBUG][net.adoptopenjdk.icedteaweb.resources.ResourceHandler] Download has not been started yet: fop.jar
...
[ITW-CORE][2021-08-20 11:35:55.853 CEST][INFO ][net.adoptopenjdk.icedteaweb.resources.cache.LeastRecentlyUsedCache] isCached: https://*** REDACTED ***/fop.jar - (v: 2.1) = true
...
[ITW-CORE][2021-08-20 11:35:57.011 CEST][DEBUG][net.adoptopenjdk.icedteaweb.resources.ResourceHandler] Will check and maybe put into cache: fop.jar
[ITW-CORE][2021-08-20 11:35:57.011 CEST][DEBUG][net.adoptopenjdk.icedteaweb.resources.ResourceHandler] Download for fop.jar has already been started.
[ITW-CORE][2021-08-20 11:35:57.026 CEST][DEBUG][net.adoptopenjdk.icedteaweb.resources.initializer.BaseResourceInitializer] Use cached version of resource location=https://*** REDACTED ***/fop.jar version=2.1 state=DOWNLOADED
[ITW-CORE][2021-08-20 11:35:57.026 CEST][DEBUG][net.adoptopenjdk.icedteaweb.resources.ResourceTracker] Download done. Shutting down executor
...
[ITW-CORE][2021-08-20 11:36:07.080 CEST][INFO ][net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader] Permission added: ("java.io.FilePermission" "C:\Users\sehenst\.cache\icedtea-web\cache\2\50\fop.jar" "read")
...
[ITW-CORE][2021-08-20 11:36:13.564 CEST][WARN ][net.sourceforge.jnlp.JNLPFile] Application title was not found in manifest. Check with application vendor
[ITW-CORE][2021-08-20 11:36:13.564 CEST][DEBUG][com.openwebstart.download.ApplicationDownloadIndicator] DownloadServiceListener for test.*** REDACTED ***.com-*** REDACTED *** will be created
[ITW-CORE][2021-08-20 11:36:13.595 CEST][DEBUG][net.adoptopenjdk.icedteaweb.resources.ResourceHandler] Will check and maybe put into cache: fop.jar
[ITW-CORE][2021-08-20 11:36:13.595 CEST][DEBUG][net.adoptopenjdk.icedteaweb.resources.ResourceHandler] Download for fop.jar has already been started.
[ITW-CORE][2021-08-20 11:36:13.595 CEST][DEBUG][net.adoptopenjdk.icedteaweb.resources.ResourceTracker] Download done. Shutting down executor
[ITW-CORE][2021-08-20 11:36:13.595 CEST][DEBUG][com.openwebstart.download.ApplicationDownloadIndicator] DownloadServiceListener will be disposed
[ITW-CORE][2021-08-20 11:36:13.611 CEST][DEBUG][net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader] Activate jar: file:/C:/Users/sehenst/.cache/icedtea-web/cache/2/50/fop.jar
[ITW-CORE][2021-08-20 11:36:13.611 CEST][INFO ][net.sourceforge.jnlp.cache.NativeLibraryStorage] Activate native: https://*** REDACTED ***/fop.jar
[ITW-CORE][2021-08-20 11:36:13.611 CEST][DEBUG][net.sourceforge.jnlp.runtime.CachedJarFileCallback] Class-Path attribute cleared for C:\Users\sehenst\.cache\icedtea-web\cache\2\50\fop.jar
[ITW-CORE][2021-08-20 11:36:13.649 CEST][DEBUG][com.openwebstart.download.ApplicationDownloadIndicator] Closing DownloadServiceListener
...
```

- Why are there 3 `Will check and maybe put into cache: fop.jar`

```
[ITW-CORE][2021-08-20 11:35:55.452 CEST][DEBUG][net.adoptopenjdk.icedteaweb.resources.ResourceHandler] Will check and maybe put into cache: fop.jar
...
[ITW-CORE][2021-08-20 11:35:57.011 CEST][DEBUG][net.adoptopenjdk.icedteaweb.resources.ResourceHandler] Will check and maybe put into cache: fop.jar
...
[ITW-CORE][2021-08-20 11:36:13.595 CEST][DEBUG][net.adoptopenjdk.icedteaweb.resources.ResourceHandler] Will check and maybe put into cache: fop.jar
...
```

- Why check again, if we already know that we'll use the cached resource?

```
[ITW-CORE][2021-08-20 11:35:57.026 CEST][DEBUG][net.adoptopenjdk.icedteaweb.resources.initializer.BaseResourceInitializer] Use cached version of resource location=https://*** REDACTED ***/fop.jar version=2.1 state=DOWNLOADED
...
[ITW-CORE][2021-08-20 11:36:13.595 CEST][DEBUG][net.adoptopenjdk.icedteaweb.resources.ResourceHandler] Will check and maybe put into cache: fop.jar
[ITW-CORE][2021-08-20 11:36:13.595 CEST][DEBUG][net.adoptopenjdk.icedteaweb.resources.ResourceHandler] Download for fop.jar has already been started.
...
```

- Is the permission always applied, or only once the resouce is downloaded?

```
[ITW-CORE][2021-08-20 11:36:07.080 CEST][INFO ][net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader] Permission added: ("java.io.FilePermission" "C:\Users\sehenst\.cache\icedtea-web\cache\2\50\fop.jar" "read")
```

- Could the warning have anything to do with the issue?

```
[ITW-CORE][2021-08-20 11:36:13.564 CEST][WARN ][net.sourceforge.jnlp.JNLPFile] Application title was not found in manifest. Check with application vendor
```

**Comment by sehenst** [comment]
> - Could the warning have anything to do with the issue?
> ```[ITW-CORE][2021-08-20 11:36:13.564 CEST][WARN ][net.sourceforge.jnlp.JNLPFile] Application title was not found in manifest. Check with application vendor```

According to the code in https://github.com/AdoptOpenJDK/IcedTea-Web the missing manifest title doesn't seem to triggare any additional downloads...

https://github.com/AdoptOpenJDK/IcedTea-Web/blob/d61daea558b27cdb34c8db9c860fae5cd96ef94d/core/src/main/java/net/sourceforge/jnlp/JNLPFile.java#L353
https://github.com/AdoptOpenJDK/IcedTea-Web/blob/d61daea558b27cdb34c8db9c860fae5cd96ef94d/core/src/main/java/net/sourceforge/jnlp/JNLPFile.java#L332

**Comment by sehenst** [comment]
I've also tried to increase the max heap to

```
-Xmx4096m
```
in `C:\Users\sehenst\AppData\Local\Programs\OpenWebStart\javaws.vmoptions` but that does not seem to improve the startup performance.

**Comment by sclassen** [comment]
Changes to the `jvaws.vmoptions` have no effect on the downloading as this config file is only used for the launcher of OpenWebStart and not the actual application.

Looking at the log from the above message there are no errors or other unexpected events.
Most of the time is spent in verifying and checking the JAR files.
This step is to ensure that all JARs comply with the WebStart standard and also to verify signatures of the jar files.

The number of JAR files in your JNLP is rather large and the time spent is noticeable by the users

**Comment by sehenst** [comment]
Ok, thanks for the info.

What are our options in order to improve the startup performance?

**Comment by sclassen** [comment]
Unfortunately there is no simple answer here. The verification of the JARs could use some fine tuning to improve performance but we currently do not have the capacity to tackle this as a community request

**Comment by sehenst** [comment]
> The verification of the JARs could use some fine tuning to improve performance...

Is the verification done sequentially or in parallel?

**Comment by sclassen** [comment]
Most likely this is not done sequentially. But because of the way one jar validation depends on the others (especially regarding certificate validation) it will take a good effort to change to a parallel approach.

**Comment by sehenst** [comment]
Ok. Thank you for the info.

We revisited the required resource files and were able to reduce the amount of required resource files. The startup time is now a couple of seconds.
