### ISSUE TITLE
detect jvm from adoptium.net

### ISSUE THREAD

**Issue by floh96** [karakun/OpenWebStart#462]
adoptopenjdk is moving to adoptium.net see this [blog post](https://blog.adoptopenjdk.net/2021/03/transition-to-eclipse-an-update/).
The newest version is already distributed from adoptium.net see https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot
Unfortunately openwebstart is not detecting the jvm at the moment.
The installation path changed to `C:\Program Files\Eclipse Adoptium\jdk-8.0.312.7-hotspot`

**Comment by janakmulani** [comment]
The installers for v 8.0302 installed it under _C:\Program Files\Eclipse Foundation_ . Now it seems they have changed the name of the installation directory.

**Comment by floh96** [comment]
Fixed by #459
