### ISSUE TITLE
OpenWebStart rejects/discards "--add-opens" java argument (Java 16 and Java 17)

### ISSUE THREAD

**Issue by harbingerofdoom** [karakun/OpenWebStart#474]
Hi, 
I am using 

> <j2se version="17" **java-vm-args="--add-opens=java.desktop/sun.font=ALL-UNNAMED"** max-heap-size="1500m"  />

 in the JNLP file and 
Openwebstart is configured to use Java17. See below screenshot 
![image](https://user-images.githubusercontent.com/59116853/144369646-361e0ebe-f682-4083-a4c5-b803dd71950d.png)

When I execute the JNLP file using openwebstart, I get the following error. 

_Waiting for exception dialog to be closed
Launch exception
netx: Launch Error: Could not launch JNLP file. ( (java.lang.reflect.InvocationTargetException ( (class VisualSim.gui.VSFont (in unnamed module @0x13809252) cannot access class sun.font.FontAccess (in module java.desktop) because module java.desktop does not export sun.font to unnamed module @0x13809252))))
Using NO_PROXY
Using NO_PROXY
Closing DownloadServiceListener
Using NO_PROXY
Using NO_PROXY
Done_

I was hoping that the issue with java arguments is already resolved earlier. **Please look at the issue and let me know, why openwebstart is not importing all the unnamed modules?**

**Comment by janakmulani** [comment]
@harbingerofdoom Can you please provide the OWS log files?

**Comment by harbingerofdoom** [comment]
@janakmulani please find the attached log files
[2021-12-09_16_52_34.799-ows-stage2.log](https://github.com/karakun/OpenWebStart/files/7684635/2021-12-09_16_52_34.799-ows-stage2.log)
[2021-12-09_16_52_34.799-ows-stage1.log](https://github.com/karakun/OpenWebStart/files/7684636/2021-12-09_16_52_34.799-ows-stage1.log)

**Comment by sclassen** [comment]
In the log file there JVM requested is 1.6+ and not 17 as in your initial post.
Are there more than one `<j2se>` or `<java>` elements in the JNLP file?

**Comment by harbingerofdoom** [comment]
@sclassen even if I put 1.6+ as the version, I get the same error because openwebstart is configured to use Java 17. 
No there is only a single statement of j2se and java arguments

**Comment by sclassen** [comment]
OK, next question. Did add the jvm-args in your local file or are they also present in the JNLP file on the server?
Because OWS will use the local file only to download the JNLP from the server and then run that JNLP

**Comment by harbingerofdoom** [comment]
The openwebstart works fine and runs the JNLP file as well on my system, till it is configured for Java 15 but as soon as I configured it for Java 16 or Java 17, it throws the error about unnamed modules, now I added the below line in the JNLP file, but it didnt work. 

> `java-vm-args="--add-opens=java.desktop/sun.font=ALL-UNNAMED"`

**Comment by sclassen** [comment]
if your local JNLP file contains a `href` attribute in the opening <jnlp> tag, can you remove this href attribute and retry it.

**Comment by harbingerofdoom** [comment]
@sclassen  by removing the href attribute, it started working again. 
Thanks a lot

**Comment by sclassen** [comment]
Ok. By removing the `href` you disable the JNLP update mechanism of webstart.
OWS uses the href to fetch the JNLP file from the server. If there is no href OWS cannot fetch it and will use the local one.

So removing the href is only a temporary workaround. The solution is to update the JNLP file on the server.
