### ISSUE TITLE
java 17 support - is this happening?

### ISSUE THREAD

**Issue by guykatz** [karakun/OpenWebStart#485]
Hi all;
i have a webstart app. i am using J8 and in the process of deciding which java version to move to.
will the openwebstart project support J17 in the future? is this in the roadmap?
thanks!

**Comment by sclassen** [comment]
OpenWebStart will stay compatible to Java 8.
And we will ensure that it also works with the latest LTS version of Java. Which is currently 17.
If you encounter any issue with running an application on Java 17 please open a ticket here.
