### ISSUE TITLE
Security Settings cannot be locked

### ISSUE THREAD

**Issue by sevi1603** [karakun/OpenWebStart#490]
Hi,
I'm currently looking into the option to provide OWS as an alternative to Java WebStart in an enterprise environment. From what I can tell there doesn't seem to be a way to configure and lock any of the security settings in OWS. The documentation only mentions _deployment.security.whilelist_ as configurable.
https://openwebstart.com/docs/OWSGuide.html#_configuration_properties_overview

Is there a reason why these security settings are not lockable? What purpose do these security settings have in an enterprise environment if users could just deactivate them?

Thanks a lot for any insights :)

**Comment by sclassen** [comment]
For an enterprise setup we recommend https://openwebstart.com/docs/OWSGuide.html#_system_configuration
This allows you to specify a system config file which can lock properties and thus prevent the user from changing them.

**Comment by sevi1603** [comment]
That seems to be working, thanks a lot!
