### ISSUE TITLE
JNLP file with &quot; fails to start

### ISSUE THREAD

**Issue by manish-kn** [karakun/OpenWebStart#500]
Hello,
We have one property in our JNLP file with contains escaped characters in VALUE attribute.
`<property name="jnlp.com.xxxxxxx" value="&quot; &quot;"/>`

This JNLP files fails to start when using OpenWebStart (version 1.5.2)
The log does not contain any information and no error records - we can not share the log file due to internal constrains.

- This same JNLP file works perfectly when using Oracle javaws.
- OpenWebStart + adoptium JDK 8 (windows x64) -> does not open JNLP and no error is thrown.
- If we change the JNLP file and remove this property -> It works fine with OpenWebStart.

**Comment by sclassen** [comment]
Can you provide the expected value you want to see in the app.
For example:

`<property name="jnlp.com.xxx" value="&quot; abc &quot;"/>` should show up as `" abc "`

**Comment by manish-kn** [comment]
Yes, that would be best to un-escape the data in value.
Because currently the JNLP does not even start - it just stops and no error is shown and nothing shows in the logs also with debug activated.
It seems that the JAVA is started and then it exits without error.

**Comment by sclassen** [comment]
I tried to reproduce the behavior you are seeing.
Unfortunately I cannot do so. Below part of the system properties

```
os.version: 5.10.0-1057-oem
os.name: Linux
os.arch: amd64
line.separator: 
jnlp.com.xxxxxxx: " "
javawebstart.version: javaws-1.8.0_312
java.vm.version: 25.312-b07
java.vm.vendor: Temurin
java.vm.specification.version: 1.8
java.vm.specification.vendor: Oracle Corporation
java.vm.specification.name: Java Virtual Machine Specification
java.vm.name: OpenJDK 64-Bit Server VM
java.vm.info: mixed mode
java.version: 1.8.0_312
java.vendor.url.bug: https://github.com/adoptium/adoptium-support/issues
java.vendor.url: https://adoptium.net/
java.vendor: Temurin
```

As you can see the `jnlp.com.xxxxxxx: " "` is parsed correctly and also I see the application running.

Can you see in the log files the following line (there may be arguments listed in the case of your application):

```
Invoking main() with args: []
```

If so then OWS has passed the control over to the application successfully.

**Comment by manish-kn** [comment]
I have compared now the logs from OWS and Jawaws - hope this helps. 

OWS -> un-escape the data 
`-Djnlp.com.xxxx=" "`

Javaws -> DO NOT un-escape data
`-Djnlp.com.xxxx=&quot; &quot;`
 
![image](https://user-images.githubusercontent.com/67371759/154921631-448134b0-9d88-4745-aee0-199c81edbe06.png)

**Comment by sclassen** [comment]
This is unfortunate because the parsing as OWS is doing seems correct.
I do not see a way of changing this on our side. Can you adapt the application to support both cases?

**Comment by sclassen** [comment]
You can change the JNLP to contain the following entry:

`<property name="jnlp.com.xxxxxxx" value="&amp;quot; &amp;quot;"/>`

**Comment by manish-kn** [comment]
Thanks, will check other options. 
Since you confirm OWS is ok I will close this issue.
