### ISSUE TITLE
Applet type JNLP does not open with OpenwebStart.

### ISSUE THREAD

**Issue by seliinozkan** [karakun/OpenWebStart#523]
I have 2 JNLP files, one of them is applet type and the other is application. However, those of applet type cannot be opened with openwebstart.

The main class of the applet is JHello2JavaExample which implements JApplet.

After the applet's start invoked, I noticed that the applet is closed directly by openwebstart. This situation does not apply to application types, I can open them.

Any Idea to get it working?

When I try with **IcedTeaWeb 1.8.8**, I can open this GUI.

Applet type JNLP:

```
  <resources>
        <!-- Application Resources -->
        <j2se version="1.8+"
            href="http://java.sun.com/products/autodl/j2se" />
        <jar href="clientJars/testApplet.jar" download="eager"/>
    </resources>
    <applet-desc 
         name="Hello Applet"
         main-class="test.JHello2JavaExample"
         width="300"
         height="300">
    </applet-desc>
	
```
	
OpenWebstart log:

[ITW-CORE][2022-12-01 13:13:59.720 TRT][DEBUG][net.sourceforge.jnlp.Launcher] Launching Applet
[ITW-CORE][2022-12-01 13:13:59.739 TRT][DEBUG][net.sourceforge.jnlp.services.ServiceUtil] call privileged method: checkSingleInstanceRunning
[ITW-CORE][2022-12-01 13:13:59.739 TRT][DEBUG][net.sourceforge.jnlp.services.ServiceUtil] arg: net.sourceforge.jnlp.JNLPFile@613f824d
[ITW-CORE][2022-12-01 13:13:59.739 TRT][DEBUG][net.sourceforge.jnlp.services.ServiceUtil] result: null
.
.
[ITW-CORE][2022-12-01 13:14:12.447 TRT][DEBUG][net.sourceforge.jnlp.runtime.Boot] Exiting Boot.mainWithReturnCode() with 0
[ITW-CORE][2022-12-01 13:14:12.447 TRT][DEBUG][net.sourceforge.jnlp.runtime.JNLPRuntime] Releasing shared lock on C:\Users\sozkan\AppData\Local\Temp\sozkan\netx\locks\netx_running
[ITW-CORE][2022-12-01 13:14:12.447 TRT][INFO ][net.sourceforge.jnlp.util.logging.OutputController] Increase polling interval for shutdown phase
[ITW-CORE][2022-12-01 13:14:12.447 TRT][DEBUG][net.sourceforge.jnlp.runtime.JNLPRuntime] Closing channel
[ITW-CORE][2022-12-01 13:14:12.478 TRT][DEBUG][net.sourceforge.jnlp.runtime.JNLPRuntime] Releasing done
[ITW-CORE][2022-12-01 13:14:12.478 TRT][DEBUG][net.adoptopenjdk.icedteaweb.resources.cache.CacheImpl] preparing to cleanup the cache
[ITW-CORE][2022-12-01 13:14:12.478 TRT][INFO ][net.adoptopenjdk.icedteaweb.resources.cache.CacheImpl] No other instances of javaws are running
[ITW-CORE][2022-12-01 13:14:12.479 TRT][DEBUG][net.adoptopenjdk.icedteaweb.resources.cache.CacheImpl] cleanup cache
[ITW-CORE][2022-12-01 13:14:12.480 TRT][DEBUG][net.adoptopenjdk.icedteaweb.resources.cache.CacheImpl] start cleaning the cache
[ITW-CORE][2022-12-01 13:14:12.490 TRT][DEBUG][net.adoptopenjdk.icedteaweb.lockingfile.LockableFile] Created lock file C:\Users\sozkan\.cache\icedtea-web\cache\recently_used.cache.lock
[ITW-CORE][2022-12-01 13:14:12.519 TRT][DEBUG][net.adoptopenjdk.icedteaweb.lockingfile.LockableFile] Deleted lock file C:\Users\sozkan\.cache\icedtea-web\cache\recently_used.cache.lock
[ITW-CORE][2022-12-01 13:14:12.520 TRT][DEBUG][net.adoptopenjdk.icedteaweb.resources.cache.CacheImpl] done cleaning the cache

**Comment by Pheil** [comment]
FYI
https://github.com/karakun/OpenWebStart/issues/26#issuecomment-528898314

**Comment by acsipak** [comment]
OWS does not support applets. [See FAQ](https://openwebstart.com/docs/FAQ.html#_does_openwebstart_support_applets)
