### ISSUE TITLE
JVM Version specification "11.*" chooses Java 17 instead of Java 11

### ISSUE THREAD

**Issue by in-fke** [karakun/OpenWebStart#535]
We have a JNLP tag of the form below to restrict to Java 11 only. Yet, OWS asks whether to update, and if the user does, the application is launched with Java 17 instead of Java 11.
Are we hitting an OWS Bug, or is the specification incorrect?

`<j2se version="11.*" ...`

**Comment by sclassen** [comment]
Correct would be `<j2se version="11*" ...`

Without the `.` after 11

**Comment by in-fke** [comment]
Ok, it looks like our specification does not get picked up at all.
Looking at the code, it seems OWS is reverting to some default "1.8+"

https://github.com/karakun/OpenWebStart/blob/6fd78be916253dbf2986ea40757dd3a577d8bfc0/openwebstart/src/main/java/com/openwebstart/launcher/OwsJvmLauncher.java#L92

> Found JVM JavaRuntime{version=17.0.6, vendor=Eclipse Adoptium, operationSystem=WIN64}
> Local runtime JavaRuntime{version=17.0.6, vendor=Eclipse Adoptium, operationSystem=WIN64} found and will be used
> Trying to find local Java runtime. Requested version: '1.8+' Requested vendor: '*' requested os: 'WIN64' active: 'true'
> Trying to find local Java runtime. Requested version: '1.8+', vendor: '*', os: 'WIN64'
> requested: JRE with version string '1.8+' and vendor '*', require 32 bit = false, from null

Going by the source code, we figured we had `<j2se>` **parallel** to `<resources>`, not nested within.
Moving that tag, would render this error when using "11.*" by the way, which is nice:

`Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: '11.*' is not a valid version-string according to JSR-56, Appendix A.
`

So changing to "11*" and moving the tag **in** the `<resources>` fixed it.
Thank you for the quick reply.
