### ISSUE TITLE
Installer for ARM-based macOS installs x64 version of OpenWebStart

### ISSUE THREAD

**Issue by SaschaLosko** [karakun/OpenWebStart#566]
Hi All

Running the macOS OpenWebStart 1.9 installer distributed with OpenWebStart_macos-aarch64_1_9_0.dmg does in fact install the "Intel" (x64) version. Could you please double-check the packaged installer?

Thank you!

**Comment by janakmulani** [comment]
Hi We could reproduce the issue. We will fix it and make a new release.

**Comment by SaschaLosko** [comment]
Great, thank you!

**Comment by rburgstaller** [comment]
any news? the intel version also insists on downloading the intel JDK

**Comment by janakmulani** [comment]
We will make a new release 1.9.1 next week.

**Comment by janakmulani** [comment]
Fixed in OWS 1.9.1
