### ISSUE TITLE
NoSuchMethodError x509.NetscapeCertTypeExtension with JVM 21 runtime

### ISSUE THREAD

**Issue by berniegsfc** [karakun/OpenWebStart#567]
OpenWebStart 1.9 fails with
```
java.lang.NoSuchMethodError: 'java.lang.Boolean sun.security.x509.NetscapeCertTypeExtension.get(java.lang.String)' 
   at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:681) 
```
if you allow OpenWebStart to update its runtime to 21.0.1 when asked.  A (signed) application that demonstrates this problem is at [skteditor](https://spdf.gsfc.nasa.gov/skteditor/skteditor.jnlp).  With a JVM 17 runtime, openwebstart will start the application.

**Comment by chrisjansen3380** [comment]
An identical issue is logged in the IcedTeaWeb github page (https://github.com/AdoptOpenJDK/IcedTea-Web/issues/922). They wil create a fix for this before the end of the year.
For now, OWS 1.8 should be used (or you can use v1.9 but fixate the JRE version in the jnlp file to v17, this is what I did)

**Comment by janakmulani** [comment]
Closing because it is duplicate of https://github.com/AdoptOpenJDK/IcedTea-Web/issues/922
