### ISSUE TITLE
Deprecated SecurityManager, AccessController, AccessControlContext, AccessControlException

### ISSUE THREAD

**Issue by Horcrux7** [karakun/OpenWebStart#569]
The classes `java.lang.SecurityManager`, `java.security.AccessController`, `java.security.AccessControlContext` and `java.security.AccessControlException` are deprecated since Java 17 and marked `forRemoval=true`

If the JDK remove the classes in the future then the follow typical JNLP code will not compile or run with OpenWebStart.

```
AccessController.doPrivileged( (PrivilegedAction)() -> ... );
```

What is the proposed solution so that we can use modern JDK versions in the future?

**Comment by sclassen** [comment]
There is none.
Once that the SecurityManager or another important class is removed from the JDK then there will be no way to run OWS with this or any future version.

**Comment by Horcrux7** [comment]
Thanks for the information. I had hope that you want implements some alternative solution.
