### ISSUE TITLE
Mac Releases do not have a code signature

### ISSUE THREAD

**Issue by bizzare** [karakun/OpenWebStart#580]
It does not appear that the mac releases are code signed.

https://developer.apple.com/documentation/xcode/creating-distribution-signed-code-for-the-mac

**OpenWebStart**
$ codesign -dr - /Applications/OpenWebStart/OpenWebStart\ javaws.app
Executable=/Applications/OpenWebStart/OpenWebStart javaws.app/Contents/MacOS/JavaApplicationStub
designated => always

**For comparison BBedit**
$ codesign -dr - /Applications/BBEdit.app                           
Executable=/Applications/BBEdit.app/Contents/MacOS/BBEdit
designated => anchor apple generic and identifier "com.barebones.bbedit" and (certificate leaf[field.1.2.840.113635.100.6.1.9] /* exists */ or certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = W52GZAXT98)

**Comment by bizzare** [comment]
Found that If i run a different command i can get more info implying its signed. Just not in the way Im used to.

$ codesign -dv --verbose=4 /Applications/OpenWebStart/OpenWebStart\ javaws.app
Executable=/Applications/OpenWebStart/OpenWebStart javaws.app/Contents/MacOS/JavaApplicationStub
Identifier=com.install4j.9615-4721-3936-4657.313
Format=app bundle with Mach-O thin (arm64)
CodeDirectory v=20100 size=982 flags=0x10000(runtime) hashes=23+5 location=embedded
VersionPlatform=1
VersionMin=720896
VersionSDK=721152
Hash type=sha256 size=32
CandidateCDHash sha256=bb66f8c6c0f7c6ab24214a0f303f494933c5ae08
CandidateCDHashFull sha256=bb66f8c6c0f7c6ab24214a0f303f494933c5ae08352ba7c364ac43d2ce0d3e50
Hash choices=sha256
CMSDigest=bb66f8c6c0f7c6ab24214a0f303f494933c5ae08352ba7c364ac43d2ce0d3e50
CMSDigestType=2
Page size=4096
CDHash=bb66f8c6c0f7c6ab24214a0f303f494933c5ae08
Signature size=8599
Authority=Developer ID Application: Karakun AG (M975RKD6AX)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Dec 20, 2023 at 1:21:25 PM
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources version=2 rules=12 files=3
Internal requirements count=1 size=36

**Comment by sclassen** [comment]
Fixed with [1.10.1](https://github.com/karakun/OpenWebStart/releases/tag/v1.10.1)
