### ISSUE TITLE
JNLP file cleanup

### ISSUE THREAD

**Issue by bjorndarri** [karakun/OpenWebStart#59]
I'm not sure if this is an issue that can be resolved by OpenWebStart, since it's most likely browser related, but here it goes.

When a user clicks a link to a .jnlp file in a browser (Chrome & Firefox) it is downloaded and subsequently run with OpenWebStart, the next time the user clicks the same link another copy of the file is downloaded and run, meaning these .jnlp files start cluttering peoples Downloads folder, app.jnlp, app(1).jnlp, app(2).jnlp etc.

There are a couple of ways to get around this, I've been using nr. 2.

1. Let the user keep a copy of the .jnlp file and use that to run the application, this doesn't seem to have any real drawbacks except the file may eventually become outdated and point to an incorrect version of the application.
2. Create a batch file containing "javaws https://url/app.jnlp", which the user uses instead of the link, the drawback is that it involves work for IT people, creating these shortcuts.

Before Chrome stopped handling .jnlp files it deleted the downloaded .jnlp file after launching the application which seems to be the optimal solution.

So, can OpenWebStart do anything to help with this, that is, allow the user to simply click a link to launch an application, without filling the Downloads folder with .jnlp files?

Just FYI: https://bugs.openjdk.java.net/browse/JDK-8067710

**Comment by sclassen** [comment]
For Option 1:
If the JNLP file contains a `href` attribute in the `jnlp` element then OWS will download the newest JNLP file whenever the appliaction is started

**Comment by sclassen** [comment]
You can try this for yourself with this very minimalistic JNLP file:

```
<?xml version="1.0" encoding="utf-8"?>
<jnlp
  spec="1.0+"
  codebase="https://docs.oracle.com/javase/tutorialJWS/samples/uiswing/AccessibleScrollDemoProject"
  href="AccessibleScrollDemo.jnlp">
  <information/>
  <resources/>
</jnlp>
```

**Comment by bjorndarri** [comment]
Yes, that's true, but the codebase attribute may change at some point, it may contain a version number for example, to allow deployment of multiple versions of the same application.

**Comment by hendrikebbers** [comment]
@bjorndarri if the codebase changes even a bat with `javaws https://url/app.jnlp` would not work anymore since the URL has changed ;)
The workflow should be to create shortcuts (Desktop / start menu) when you start an application for the first time. by doing so you can always start the app by the shortcut (that is more or less similar to the bat file). If the codebase changes you can not really do anything. Maybe the App can inform the user that he needs to download the JNLP from a different location.

**Comment by sclassen** [comment]
As far as I have understood the JSR-56 I would guess a change in the url of the JNLP file can be considered to be a different application.

**Comment by bjorndarri** [comment]
@hendrikebbers heh, you got me there :).
The thing is I don't want my users to have to do anything really. They are used to clicking a link or opening a bookmark to launch applications, which is just super convenient, so any added steps feel like steps backwards in user-friendliness. But I'm actually warming to the idea of letting them save the jnlp file and use that as a shortcut.
