### ISSUE TITLE
Add support for -Xnosplash

### ISSUE THREAD

**Issue by akuhtz** [karakun/OpenWebStart#72]
It would be nice to have support for the ```-Xnosplash``` option in OpenWebStart from here: https://docs.oracle.com/javase/8/docs/technotes/tools/unix/javaws.html

See also https://github.com/AdoptOpenJDK/IcedTea-Web/issues/420

**Comment by akuhtz** [comment]
Update:
```javaws -Xnosplash -jnlp http://localhost:8080/webstart/foo.jnlp```
while 
```javaws -Xnosplash http://localhost:8080/webstart/foo.jnlp``` 
fails.

**Comment by sclassen** [comment]
fixed with OWS 1.1
