### ISSUE TITLE
openjdk homebrew install not detected by jvm manager on macOS

### ISSUE THREAD

**Issue by tiiiecherle** [karakun/OpenWebStart#74]
Hey,

first of all thanks for this project, very much appreciated.

I´m trying to use an already installed homebrew openjdk install as jvm for openwebstart on the latest macOS 10.15.1.

If using 
```
brew install openjdk
sudo ln -sfn /usr/local/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
```
the jvm manager does not detect openjdk on a local search and when trying to add it using the add button it stays greyed out and is not selectable from `/Library/Java/JavaVirtualMachines/openjdk.jdk`. 
Drag and drop is not working either.

Other java apps work as expected and `java --version` outputs
```
openjdk 13.0.1 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9)
OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
```

If using
`brew cask install adoptopenjdk`
adoptopenjdk ist detected by the jvm successfully.

Thanks for looking into it in advance.

Kind regards

**Comment by sclassen** [comment]
If you can tell us where `brew install openjdk` places the java executable we can include this path when searching for local JVMs

Also in which window is openjdk greyed out?
In the file selector?

There you need to select a folder. OWS will den search in this folder and its children for a JVM

**Comment by hendrikebbers** [comment]
We can test this tomorrow on my machine

Von meinem iPhone gesendet

**Comment by tiiiecherle** [comment]
> If you can tell us where `brew install openjdk` places the java executable we can include this path when searching for local JVMs
> 
> Also in which window is openjdk greyed out?
> In the file selector?
> 
> There you need to select a folder. OWS will den search in this folder and its children for a JVM

Thanks for the fast response. 

As you can see from the commands above it places the executable at
`/usr/local/opt/openjdk/libexec/openjdk.jdk`
and links it to `/Library/Java/JavaVirtualMachines/openjdk.jdk`

Yes, in the file selector window the select button is greyd out inside the `/Library/Java/JavaVirtualMachines/` folder. If I select the folder the jvm manager window stays empty.

jvm manager also stays empty if I select `/usr/local/opt/openjdk/`.

**Comment by hendrikebbers** [comment]
This is a mac specific problem.
`/usr/local/opt/openjdk/libexec/openjdk.jdk` is not a simple folder. It is a mac application bundle. You will have the same effect when navigating with the finder to the folder. You can not simply open `openjdk.jdk`. You need to do a right click and choose "Show package content". I have no idea how Mac OS defines a folder to be an application bundle but such bundle can not easily open by a file chooser.

**Comment by tiiiecherle** [comment]
> This is a mac specific problem.
> `/usr/local/opt/openjdk/libexec/openjdk.jdk` is not a simple folder. It is a mac application bundle. You will have the same effect when navigating with the finder to the folder. You can not simply open `openjdk.jdk`. You need to do a right click and choose "Show package content". I have no idea how Mac OS defines a folder to be an application bundle but such bundle can not easily open by a file chooser.

O.k., but I guess the local search should still find a validly installed openjdk.

**Comment by barthel** [comment]
If it is possible you could use the macOS program ```/usr/libexec/java_home``` to list all available Java installations.

```
Usage: java_home [options...]
    Returns the path to a Java home directory from the current user's settings.

Options:
    [-v/--version   <version>]       Filter Java versions in the "JVMVersion" form 1.X(+ or *).
    [-a/--arch      <architecture>]  Filter JVMs matching architecture (i386, x86_64, etc).
    [-d/--datamodel <datamodel>]     Filter JVMs capable of -d32 or -d64
    [-t/--task      <task>]          Use the JVM list for a specific task (Applets, WebStart, BundledApp, JNI, or CommandLine)
    [-F/--failfast]                  Fail when filters return no JVMs, do not continue with default.
    [   --exec      <command> ...]   Execute the $JAVA_HOME/bin/<command> with the remaining arguments.
    [-R/--request]                   Request installation of a Java Runtime if not installed.
    [-X/--xml]                       Print full JVM list and additional data as XML plist.
    [-V/--verbose]                   Print full JVM list with architectures.
    [-h/--help]                      This usage information.
```

**Comment by tiiiecherle** [comment]
This would work here I guess...

`/usr/libexec/java_home`
shows
`/Library/Java/JavaVirtualMachines/openjdk.jdk/Contents/Home`

**Comment by hendrikebbers** [comment]
While I really like the idea I assume that we won't fix this within the next weeks. We currently working on a 1.0 release that will contain all features that are needed by our sponsors.

@tiiiecherle in general you have 2 options if you need a fix within the next weeks:
- Do a PR on your own. We will review it and merge it in OWS once it fits our coding & quality standards. 
- Contact openwebstart@karakun.com and discuss a handling for this issue directly with the team.

**Comment by tiiiecherle** [comment]
@hendrikebbers Thanks for the feedback. As I am not a developer I can not fix it myself. I would leave this issue open hoping you will find the time to fix it soon after the higher priority features and fixes.

Thanks in advance

**Comment by hendrikebbers** [comment]
fix added: https://github.com/karakun/OpenWebStart/pull/94
