### ISSUE TITLE
MSI wrapper for the installer artifact

### ISSUE THREAD

**Issue by zerowaitstate** [karakun/OpenWebStart#98]
It looks like the installer is generated using install4j.  Would it be possible to generate an MSI wrapper from install4j in addition to the EXE?  I have an internal app I would like to try this out on, but need to deploy OWS with Group Policy.

**Comment by hendrikebbers** [comment]
Hi @zerowaitstate 
you are right: we use install4j to create the native installers.

> need to deploy OWS with Group Policy
Can you add a more detailed description about your use case?
`

**Comment by zerowaitstate** [comment]
Sure.  We have an internal company application which uses Webstart.  However, getting webstart onto the company machines would require either an administrator touch or installation via Group Policy, as users do not have permission to install software on machines themselves.  With an EXE, we have to use a powershell script to deploy the EXE.  If the artifact is an MSI, then the artifact can be deployed directly via Group Policy without relying on a script.  One potential hangup is the answer file; with the EXE this is handled via the -varfile option.  I am not familiar enough with install4j to know if the generated MSI would permit manipulation of these same parameters via MST transforms.  If so, that would solve our use case, as we need to specify AdoptOpenJDK as the JVM vendor.

**Comment by hendrikebbers** [comment]
you can find additional information for MSI with Install4J here: https://www.ej-technologies.com/resources/install4j/v/8.0/help/doc/concepts/mediaFiles.html

Based on this I assume that we will not support this in near future. If this is a show stopper for you and you need such support please write a mail to openwebstart@karakun.com and we can discuss this issue.
